// apps/docs/src/components/auth/two-factor/two-factor-challenge.tsx
"use client"

import {
  type TwoFactorAuthClient,
  useAuth,
  useAuthPlugin,
  useSendTwoFactorOtp,
  useVerifyBackupCode,
  useVerifyTotp,
  useVerifyTwoFactorOtp
} from "@better-auth-ui/react"
import { type SyntheticEvent, useEffect, useState } from "react"

import { Button } from "@/components/ui/button"
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle
} from "@/components/ui/card"
import { Checkbox } from "@/components/ui/checkbox"
import {
  Field,
  FieldDescription,
  FieldGroup,
  FieldLabel
} from "@/components/ui/field"
import { Input } from "@/components/ui/input"
import { Spinner } from "@/components/ui/spinner"
import {
  clearTwoFactorMethods,
  readTwoFactorMethods,
  type TwoFactorMethod
} from "@/lib/auth/two-factor-methods"
import { twoFactorPlugin } from "@/lib/auth/two-factor-plugin"
import {
  RESEND_COOLDOWN_SECONDS,
  useResendCooldown
} from "@/lib/auth/use-resend-cooldown"
import { cn } from "@/lib/utils"
import { OtpField } from "../otp-field"
import { useIsHydrated } from "../use-is-hydrated"

/** Challenge surfaces the view can render, in the order they are offered. */
type ChallengeMethod = TwoFactorMethod | "backup"

export type TwoFactorChallengeProps = {
  className?: string
}

/**
 * Second-factor challenge that finishes a pending sign-in.
 *
 * Better Auth answers a password sign-in with `twoFactorRedirect` instead of
 * a session, and the shared sign-in continuation sends the browser here with
 * the enabled methods in session storage. Verifying is what creates the
 * session, after which the original `redirectTo` is resumed.
 *
 * @param className - Additional CSS classes applied to the card.
 */
export function TwoFactorChallenge({ className }: TwoFactorChallengeProps) {
  const {
    authClient,
    basePaths,
    localization,
    navigate,
    redirectTo,
    viewPaths,
    Link
  } = useAuth()
  const {
    backupCodes: backupCodesEnabled,
    codeLength,
    localization: twoFactorLocalization,
    trustDevice: trustDeviceEnabled
  } = useAuthPlugin(twoFactorPlugin)

  const twoFactorClient = authClient as TwoFactorAuthClient
  const isHydrated = useIsHydrated()

  const [methods, setMethods] = useState<TwoFactorMethod[]>(() =>
    isHydrated ? readTwoFactorMethods() : ["totp", "otp"]
  )
  const [method, setMethod] = useState<ChallengeMethod>(
    () => methods[0] ?? "totp"
  )
  const [code, setCode] = useState("")
  const [trustDevice, setTrustDevice] = useState(false)
  const [otpRequested, setOtpRequested] = useState(false)
  const { cooldown, isCoolingDown, startCooldown } = useResendCooldown()

  useEffect(() => {
    const stored = readTwoFactorMethods()
    setMethods(stored)
    setMethod(stored[0] ?? "totp")
  }, [])

  const onVerified = () => {
    clearTwoFactorMethods()
    navigate({ to: redirectTo })
  }

  const { mutate: sendTwoFactorOtp, isPending: isSendingOtp } =
    useSendTwoFactorOtp(twoFactorClient, {
      onSuccess: () => {
        setOtpRequested(true)
        startCooldown(RESEND_COOLDOWN_SECONDS)
      }
    })

  const { mutate: verifyTotp, isPending: isVerifyingTotp } = useVerifyTotp(
    twoFactorClient,
    { onError: () => setCode(""), onSuccess: onVerified }
  )

  const { mutate: verifyTwoFactorOtp, isPending: isVerifyingOtp } =
    useVerifyTwoFactorOtp(twoFactorClient, {
      onError: () => setCode(""),
      onSuccess: onVerified
    })

  const { mutate: verifyBackupCode, isPending: isVerifyingBackupCode } =
    useVerifyBackupCode(twoFactorClient, { onSuccess: onVerified })

  const isPending =
    isSendingOtp || isVerifyingTotp || isVerifyingOtp || isVerifyingBackupCode

  const switchMethod = (next: ChallengeMethod) => {
    setCode("")
    setMethod(next)
  }

  const handleSubmit = (e: SyntheticEvent<HTMLFormElement>) => {
    e.preventDefault()

    const trust = trustDeviceEnabled ? { trustDevice } : {}

    if (method === "backup") {
      const formData = new FormData(e.currentTarget)
      verifyBackupCode({
        code: (formData.get("backupCode") as string).trim(),
        ...trust
      })
      return
    }

    if (method === "otp") {
      verifyTwoFactorOtp({ code, ...trust })
      return
    }

    verifyTotp({ code, ...trust })
  }

  const needsOtpRequest = method === "otp" && !otpRequested

  const description =
    method === "backup"
      ? twoFactorLocalization.backupCodeDescription
      : method === "otp"
        ? twoFactorLocalization.emailedCodeDescription
        : twoFactorLocalization.authenticatorCodeDescription

  const alternatives: { key: ChallengeMethod; label: string }[] = [
    ...(method !== "totp" && methods.includes("totp")
      ? [
          {
            key: "totp" as const,
            label: twoFactorLocalization.useAuthenticator
          }
        ]
      : []),
    ...(method !== "otp" && methods.includes("otp")
      ? [{ key: "otp" as const, label: twoFactorLocalization.useEmailedCode }]
      : []),
    ...(method !== "backup" && backupCodesEnabled
      ? [{ key: "backup" as const, label: twoFactorLocalization.useBackupCode }]
      : [])
  ]

  return (
    <Card className={cn("w-full max-w-sm", className)}>
      <CardHeader>
        <CardTitle className="text-xl">
          {twoFactorLocalization.twoFactor}
        </CardTitle>

        <CardDescription>{description}</CardDescription>
      </CardHeader>

      <CardContent>
        <form onSubmit={handleSubmit}>
          <FieldGroup>
            {method === "backup" ? (
              <Field>
                <FieldLabel htmlFor="backupCode">
                  {twoFactorLocalization.backupCode}
                </FieldLabel>

                <Input
                  id="backupCode"
                  name="backupCode"
                  autoComplete="one-time-code"
                  autoFocus
                  required
                  disabled={isPending}
                />
              </Field>
            ) : (
              <OtpField
                autoFocus
                disabled={isPending || needsOtpRequest}
                label={
                  method === "otp"
                    ? twoFactorLocalization.emailedCode
                    : twoFactorLocalization.authenticatorCode
                }
                length={codeLength}
                name="code"
                value={code}
                onChange={setCode}
              />
            )}

            {trustDeviceEnabled && (
              <Field orientation="horizontal">
                <Checkbox
                  id="trustDevice"
                  name="trustDevice"
                  checked={trustDevice}
                  disabled={isPending}
                  onCheckedChange={(checked) =>
                    setTrustDevice(checked === true)
                  }
                />

                <FieldLabel htmlFor="trustDevice" className="font-normal">
                  {twoFactorLocalization.trustDevice}
                </FieldLabel>
              </Field>
            )}

            <div className="flex flex-col gap-3">
              {needsOtpRequest ? (
                <Button
                  type="button"
                  disabled={isSendingOtp}
                  onClick={() => sendTwoFactorOtp()}
                >
                  {isSendingOtp && <Spinner />}

                  {twoFactorLocalization.sendEmailCode}
                </Button>
              ) : (
                <Button
                  type="submit"
                  disabled={
                    isPending ||
                    (method !== "backup" && code.length !== codeLength)
                  }
                >
                  {isPending && <Spinner />}

                  {twoFactorLocalization.verify}
                </Button>
              )}

              {method === "otp" && otpRequested && (
                <Button
                  type="button"
                  variant="outline"
                  disabled={isPending || isCoolingDown}
                  onClick={() => sendTwoFactorOtp()}
                >
                  {isCoolingDown
                    ? localization.auth.resendIn.replace(
                        "{{seconds}}",
                        String(cooldown)
                      )
                    : localization.auth.resend}
                </Button>
              )}

              {alternatives.map((alternative) => (
                <Button
                  type="button"
                  variant="ghost"
                  key={alternative.key}
                  disabled={isPending}
                  onClick={() => switchMethod(alternative.key)}
                >
                  {alternative.label}
                </Button>
              ))}
            </div>
          </FieldGroup>
        </form>

        <div className="flex flex-col gap-3 items-center w-full mt-4">
          <FieldDescription className="text-center">
            <Link
              href={`${basePaths.auth}/${viewPaths.auth.signIn}`}
              className="underline underline-offset-4"
            >
              {twoFactorLocalization.backToSignIn}
            </Link>
          </FieldDescription>
        </div>
      </CardContent>
    </Card>
  )
}

// examples/start-solid-zaidan-example/src/components/auth/two-factor/two-factor-challenge.tsx
import {
  sendTwoFactorOtpOptions,
  type TwoFactorAuthClient,
  useAuth,
  useAuthPlugin,
  verifyBackupCodeOptions,
  verifyTotpOptions,
  verifyTwoFactorOtpOptions
} from "@better-auth-ui/solid"
import { createMutation } from "@tanstack/solid-query"
import { Link } from "@tanstack/solid-router"
import { createSignal, For, Show } from "solid-js"

import { OtpField } from "@/components/auth/otp-field"
import { Button } from "@/components/ui/button"
import {
  Card,
  CardContent,
  CardDescription,
  CardFooter,
  CardHeader,
  CardTitle
} from "@/components/ui/card"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { Spinner } from "@/components/ui/spinner"
import {
  clearTwoFactorMethods,
  readTwoFactorMethods,
  type TwoFactorMethod
} from "@/lib/auth/two-factor-methods"
import { twoFactorPlugin } from "@/lib/auth/two-factor-plugin"
import {
  RESEND_COOLDOWN_SECONDS,
  useResendCooldown
} from "@/lib/auth/use-resend-cooldown"
import { cn } from "@/lib/utils"

/** Challenge surfaces the view can render, in the order they are offered. */
type ChallengeMethod = TwoFactorMethod | "backup"

export type TwoFactorChallengeProps = {
  class?: string
}

/**
 * Second-factor challenge that finishes a pending sign-in.
 *
 * Better Auth answers a password sign-in with `twoFactorRedirect` instead of
 * a session, and the shared sign-in continuation sends the browser here with
 * the enabled methods in session storage. Verifying is what creates the
 * session, after which the original `redirectTo` is resumed.
 */
export function TwoFactorChallenge(props: TwoFactorChallengeProps) {
  const auth = useAuth()
  const {
    backupCodes: backupCodesEnabled,
    codeLength,
    localization: twoFactorLocalization,
    trustDevice: trustDeviceEnabled
  } = useAuthPlugin(twoFactorPlugin)

  const storedMethods = readTwoFactorMethods()

  const [methods] = createSignal<TwoFactorMethod[]>(storedMethods)
  const [method, setMethod] = createSignal<ChallengeMethod>(
    storedMethods[0] ?? "totp"
  )
  const [code, setCode] = createSignal("")
  const [trustDevice, setTrustDevice] = createSignal(false)
  const [otpRequested, setOtpRequested] = createSignal(false)
  const { cooldown, isCoolingDown, startCooldown } = useResendCooldown()

  const twoFactorClient = () => auth.authClient as TwoFactorAuthClient

  const onVerified = () => {
    clearTwoFactorMethods()
    auth.navigate({ to: auth.redirectTo })
  }

  const sendOtp = createMutation(() => ({
    ...sendTwoFactorOtpOptions(twoFactorClient()),
    onSuccess: () => {
      setOtpRequested(true)
      startCooldown(RESEND_COOLDOWN_SECONDS)
    }
  }))

  const verifyTotp = createMutation(() => ({
    ...verifyTotpOptions(twoFactorClient()),
    onError: () => setCode(""),
    onSuccess: onVerified
  }))

  const verifyOtp = createMutation(() => ({
    ...verifyTwoFactorOtpOptions(twoFactorClient()),
    onError: () => setCode(""),
    onSuccess: onVerified
  }))

  const verifyBackupCode = createMutation(() => ({
    ...verifyBackupCodeOptions(twoFactorClient()),
    onSuccess: onVerified
  }))

  const isPending = () =>
    sendOtp.isPending ||
    verifyTotp.isPending ||
    verifyOtp.isPending ||
    verifyBackupCode.isPending

  const needsOtpRequest = () => method() === "otp" && !otpRequested()

  const description = () => {
    if (method() === "backup")
      return twoFactorLocalization.backupCodeDescription
    if (method() === "otp") return twoFactorLocalization.emailedCodeDescription

    return twoFactorLocalization.authenticatorCodeDescription
  }

  const alternatives = (): { key: ChallengeMethod; label: string }[] => [
    ...(method() !== "totp" && methods().includes("totp")
      ? [
          {
            key: "totp" as const,
            label: twoFactorLocalization.useAuthenticator
          }
        ]
      : []),
    ...(method() !== "otp" && methods().includes("otp")
      ? [{ key: "otp" as const, label: twoFactorLocalization.useEmailedCode }]
      : []),
    ...(method() !== "backup" && backupCodesEnabled
      ? [{ key: "backup" as const, label: twoFactorLocalization.useBackupCode }]
      : [])
  ]

  const submit = (event: SubmitEvent & { currentTarget: HTMLFormElement }) => {
    event.preventDefault()

    const trust = trustDeviceEnabled ? { trustDevice: trustDevice() } : {}

    if (method() === "backup") {
      const formData = new FormData(event.currentTarget)
      verifyBackupCode.mutate({
        code: String(formData.get("backupCode") ?? "").trim(),
        ...trust
      } as Parameters<typeof verifyBackupCode.mutate>[0])
      return
    }

    if (method() === "otp") {
      verifyOtp.mutate({ code: code(), ...trust } as Parameters<
        typeof verifyOtp.mutate
      >[0])
      return
    }

    verifyTotp.mutate({ code: code(), ...trust } as Parameters<
      typeof verifyTotp.mutate
    >[0])
  }

  return (
    <Card class={cn("w-full max-w-sm", props.class)}>
      <CardHeader>
        <CardTitle class="text-xl font-semibold">
          {twoFactorLocalization.twoFactor}
        </CardTitle>

        <CardDescription>{description()}</CardDescription>
      </CardHeader>

      <CardContent>
        <form aria-label={twoFactorLocalization.twoFactor} onSubmit={submit}>
          <div class="grid gap-3">
            <Show
              when={method() === "backup"}
              fallback={
                <OtpField
                  autofocus
                  disabled={isPending() || needsOtpRequest()}
                  id="two-factor-code"
                  label={
                    method() === "otp"
                      ? twoFactorLocalization.emailedCode
                      : twoFactorLocalization.authenticatorCode
                  }
                  length={codeLength}
                  name="code"
                  onInput={setCode}
                  value={code()}
                />
              }
            >
              <Label for="two-factor-backup-code">
                {twoFactorLocalization.backupCode}
              </Label>

              <Input
                autocomplete="one-time-code"
                autofocus
                disabled={isPending()}
                id="two-factor-backup-code"
                name="backupCode"
                required
              />
            </Show>

            <Show when={trustDeviceEnabled}>
              <label
                class="flex items-center gap-2 text-sm"
                for="two-factor-trust-device"
              >
                <input
                  checked={trustDevice()}
                  class="size-4 rounded border-input"
                  disabled={isPending()}
                  id="two-factor-trust-device"
                  name="trustDevice"
                  onChange={(event) =>
                    setTrustDevice(event.currentTarget.checked)
                  }
                  type="checkbox"
                />

                {twoFactorLocalization.trustDevice}
              </label>
            </Show>

            <div class="flex flex-col gap-3">
              <Show
                when={needsOtpRequest()}
                fallback={
                  <Button
                    class="w-full"
                    disabled={
                      isPending() ||
                      (method() !== "backup" && code().length !== codeLength)
                    }
                    type="submit"
                  >
                    <Show when={isPending()}>
                      <Spinner />
                    </Show>

                    {twoFactorLocalization.verify}
                  </Button>
                }
              >
                <Button
                  class="w-full"
                  disabled={sendOtp.isPending}
                  onClick={() =>
                    sendOtp.mutate({} as Parameters<typeof sendOtp.mutate>[0])
                  }
                  type="button"
                >
                  <Show when={sendOtp.isPending}>
                    <Spinner />
                  </Show>

                  {twoFactorLocalization.sendEmailCode}
                </Button>
              </Show>

              <Show when={method() === "otp" && otpRequested()}>
                <Button
                  class="w-full"
                  disabled={isPending() || isCoolingDown()}
                  onClick={() =>
                    sendOtp.mutate({} as Parameters<typeof sendOtp.mutate>[0])
                  }
                  type="button"
                  variant="outline"
                >
                  {isCoolingDown()
                    ? auth.localization.auth.resendIn.replace(
                        "{{seconds}}",
                        String(cooldown())
                      )
                    : auth.localization.auth.resend}
                </Button>
              </Show>

              <For each={alternatives()}>
                {(alternative) => (
                  <Button
                    class="w-full"
                    disabled={isPending()}
                    onClick={() => {
                      setCode("")
                      setMethod(alternative.key)
                    }}
                    type="button"
                    variant="ghost"
                  >
                    {alternative.label}
                  </Button>
                )}
              </For>
            </div>
          </div>
        </form>
      </CardContent>

      <CardFooter class="justify-center">
        <Link
          class="text-sm underline underline-offset-4"
          params={{ path: auth.viewPaths.auth.signIn }}
          to="/auth/$path"
        >
          {twoFactorLocalization.backToSignIn}
        </Link>
      </CardFooter>
    </Card>
  )
}
