// packages/react/src/hooks/auth/use-authenticate.ts
import { useEffect } from "react"
import { useAuth } from "../../components/auth/auth-provider"
import type { AuthClient } from "../../lib/auth-client"
import {
  type UseSessionOptions,
  useSession
} from "../../queries/auth/session-query"

/**
 * Calls `useSession` and redirects unauthenticated users to the sign-in page,
 * preserving the current URL as a `redirectTo` query param.
 *
 * @param authClient - The Better Auth client.
 * @param options - `getSession` params & `useQuery` options.
 */
export function useAuthenticate<TAuthClient extends AuthClient>(
  authClient: TAuthClient,
  options?: UseSessionOptions<TAuthClient>
) {
  const { basePaths, viewPaths, navigate } = useAuth()
  const session = useSession(authClient, options)

  useEffect(() => {
    if (session.data || session.isPending) return

    const currentURL = window.location.pathname + window.location.search
    const redirectTo = encodeURIComponent(currentURL)
    const signInPath = `${basePaths.auth}/${viewPaths.auth.signIn}?redirectTo=${redirectTo}`

    navigate({ to: signInPath, replace: true })
  }, [
    basePaths.auth,
    session.data,
    session.isPending,
    viewPaths.auth.signIn,
    navigate
  ])

  return session
}

// packages/solid/src/hooks/auth/use-authenticate.ts
import { createEffect } from "solid-js"
import { isServer } from "solid-js/web"
import type { AuthClient } from "../../lib/auth-client"
import { useAuth } from "../../lib/auth-provider"
import {
  type UseSessionOptions,
  useSession
} from "../../queries/auth/session-query"

export function useAuthenticate<TAuthClient extends AuthClient>(
  authClient: TAuthClient,
  options?: UseSessionOptions<TAuthClient>
) {
  const config = useAuth()
  const session = useSession(authClient, options)

  createEffect(() => {
    if (session.data || session.isPending) return

    const currentURL = isServer
      ? "/"
      : window.location.pathname + window.location.search
    const redirectTo = encodeURIComponent(currentURL)
    const signInPath = `${config.basePaths.auth}/${config.viewPaths.auth.signIn}?redirectTo=${redirectTo}`

    config.navigate({ to: signInPath, replace: true })
  })

  return session
}
