// examples/start-solid-zaidan-example/src/components/auth/multi-session/switch-account-submenu.tsx
import {
  multiSessionPlugin as coreMultiSessionPlugin,
  type MultiSessionLocalization,
  multiSessionLocalization
} from "@better-auth-ui/core/plugins"
import { useAuth, useSession } from "@better-auth-ui/solid"
import { ArrowLeftRight } from "lucide-solid"
import { Show } from "solid-js"
import {
  DropdownMenuSub,
  DropdownMenuSubTrigger
} from "@/components/ui/dropdown-menu"
import { SwitchAccountSubmenuContent } from "./switch-account-submenu-content"

export type SwitchAccountSubmenuProps = {
  class?: string
}

export function SwitchAccountSubmenu(props: SwitchAccountSubmenuProps) {
  const auth = useAuth()
  const session = useSession(auth.authClient, {
    enabled: !import.meta.env.SSR
  })
  const multiSessionPluginConfig = () =>
    auth.plugins.find((plugin) => plugin.id === coreMultiSessionPlugin.id)
  const multiSessionLabels = (): MultiSessionLocalization => ({
    ...multiSessionLocalization,
    ...(multiSessionPluginConfig()?.localization as
      | Partial<MultiSessionLocalization>
      | undefined)
  })

  return (
    <Show when={session.data}>
      <DropdownMenuSub>
        <DropdownMenuSubTrigger class={props.class}>
          <ArrowLeftRight class="size-4 text-muted-foreground" />
          {multiSessionLabels().switchAccount}
        </DropdownMenuSubTrigger>

        <SwitchAccountSubmenuContent />
      </DropdownMenuSub>
    </Show>
  )
}

// examples/start-shadcn-example/src/components/multi-session/switch-account-submenu.tsx
"use client"

import { useAuth, useAuthPlugin, useSession } from "@better-auth-ui/react"
import { UsersRound } from "lucide-react"

import {
  DropdownMenuSub,
  DropdownMenuSubTrigger
} from "@/components/ui/dropdown-menu"
import { multiSessionPlugin } from "@/lib/multi-session/multi-session-plugin"
import { SwitchAccountSubmenuContent } from "./switch-account-submenu-content"

export type SwitchAccountSubmenuProps = {
  className?: string
}

/**
 * Render a submenu trigger for switching between multiple authenticated sessions.
 *
 * This component renders as a dropdown menu item that opens a submenu containing
 * the switch account menu. It should be rendered inside the UserButton dropdown
 * as a userMenuItem from the multiSessionPlugin.
 *
 * @param className - Optional additional CSS class names
 * @returns The switch account submenu as a JSX element
 */
export function SwitchAccountSubmenu({ className }: SwitchAccountSubmenuProps) {
  const { authClient } = useAuth()
  const { data: session } = useSession(authClient)
  const { localization: multiSessionLocalization } =
    useAuthPlugin(multiSessionPlugin)

  if (!session) {
    return null
  }

  return (
    <DropdownMenuSub>
      <DropdownMenuSubTrigger className={className}>
        <UsersRound className="text-muted-foreground" />

        {multiSessionLocalization.switchAccount}
      </DropdownMenuSubTrigger>

      <SwitchAccountSubmenuContent />
    </DropdownMenuSub>
  )
}
