// examples/start-solid-zaidan-example/src/components/auth/sign-out.tsx
import { useAuth } from "@better-auth-ui/solid"
import { onMount } from "solid-js"
import { Spinner } from "@/components/ui/spinner"
import { cn } from "@/lib/utils"

export type SignOutProps = {
  class?: string
}

const signInHref = (basePath: string, signInPath: string) =>
  `${basePath}/${signInPath}`

export function SignOut(props: SignOutProps) {
  const auth = useAuth()
  let hasRequestedSignOut = false

  onMount(async () => {
    if (hasRequestedSignOut) return
    hasRequestedSignOut = true

    try {
      await auth.authClient.signOut({ fetchOptions: { throw: true } })
    } finally {
      auth.navigate({
        to: signInHref(auth.basePaths.auth, auth.viewPaths.auth.signIn),
        replace: true
      })
    }
  })

  return <Spinner class={cn("mx-auto my-auto", props.class)} />
}

// packages/heroui/src/components/auth/sign-out.tsx
import { useAuth, useSignOut } from "@better-auth-ui/react"
import { cn, Spinner } from "@heroui/react"
import { useEffect, useRef } from "react"

export type SignOutProps = {
  className?: string
}

/**
 * Initiates sign-out on mount and renders a loading card while sign-out proceeds.
 *
 * @returns A Card containing a centered Spinner shown during the sign-out process
 */
export function SignOut({ className }: SignOutProps) {
  const { authClient, basePaths, navigate, viewPaths } = useAuth()

  const { mutate: signOut } = useSignOut(authClient, {
    onError: () => {
      navigate({
        to: `${basePaths.auth}/${viewPaths.auth.signIn}`,
        replace: true
      })
    },
    onSuccess: () =>
      navigate({
        to: `${basePaths.auth}/${viewPaths.auth.signIn}`,
        replace: true
      })
  })

  const hasSignedOut = useRef(false)

  useEffect(() => {
    if (hasSignedOut.current) return
    hasSignedOut.current = true

    signOut()
  }, [signOut])

  return (
    <Spinner className={cn("mx-auto my-auto", className)} color="current" />
  )
}
