// examples/start-solid-zaidan-example/src/components/auth/user/user-button.tsx
import { useAuth, useSession } from "@better-auth-ui/solid"
import { Link } from "@tanstack/solid-router"
import {
  ChevronsUpDown,
  LogIn,
  LogOut,
  Settings,
  User,
  UserPlus2
} from "lucide-solid"
import type { Component, JSX } from "solid-js"
import {
  createMemo,
  createSignal,
  For,
  mergeProps,
  onMount,
  Show
} from "solid-js"
import { Dynamic } from "solid-js/web"
import { ThemeToggleItem } from "@/components/auth/theme/theme-toggle-item"
import { UserAvatar } from "@/components/auth/user/user-avatar"
import { UserView } from "@/components/auth/user/user-view"
import { buttonVariants } from "@/components/ui/button"
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuLabel,
  DropdownMenuSeparator,
  DropdownMenuTrigger
} from "@/components/ui/dropdown-menu"
import { Separator } from "@/components/ui/separator"
import { Skeleton } from "@/components/ui/skeleton"
import { cn } from "@/lib/utils"

const menuLinkClass = "flex w-full items-center gap-1.5"

export type UserButtonLinkVisibility =
  | "authenticated"
  | "unauthenticated"
  | "always"

export type UserButtonLink = {
  href: string
  icon?: JSX.Element
  label: JSX.Element
  variant?: "default" | "destructive"
  visibility?: UserButtonLinkVisibility
}

const isUserButtonLink = (
  link: UserButtonLink | JSX.Element
): link is UserButtonLink =>
  typeof link === "object" && link !== null && "href" in link && "label" in link

const resolveUserLabel = (
  username?: string | null,
  name?: string | null,
  email?: string | null
) => username || name || email || "Account"

const resolveUserSecondaryLabel = (
  username?: string | null,
  name?: string | null,
  email?: string | null
) => (username || name ? email : undefined)

const resolveUserInitials = (
  username?: string | null,
  name?: string | null,
  email?: string | null
) => resolveUserLabel(username, name, email).slice(0, 2).toUpperCase()

type UserMenuItemPlugin = {
  id: string
  userMenuItems?: Component<{ class?: string }>[]
}

export type UserButtonProps = {
  class?: string
  align?: "center" | "end" | "start"
  hideSettings?: boolean
  links?: (UserButtonLink | JSX.Element)[]
  sideOffset?: number
  size?: "default" | "icon"
  variant?:
    | "default"
    | "destructive"
    | "ghost"
    | "link"
    | "outline"
    | "secondary"
}

function UserButtonPendingView() {
  return (
    <div class="flex items-center gap-2 text-left">
      <Skeleton class="size-8 rounded-full" />
      <div class="grid flex-1 gap-1 text-left text-sm">
        <Skeleton class="h-4 w-24" />
        <Skeleton class="h-3 w-32" />
      </div>
    </div>
  )
}

function renderUserLink(link: UserButtonLink | JSX.Element) {
  if (!isUserButtonLink(link)) return link

  return (
    <DropdownMenuItem
      class="gap-1.5 rounded-md px-1.5 py-1 text-sm focus:bg-accent focus:text-accent-foreground"
      variant={link.variant}
    >
      <a class={menuLinkClass} href={link.href}>
        {link.icon}
        {link.label}
      </a>
    </DropdownMenuItem>
  )
}

function MountedUserButton(rawProps: UserButtonProps = {}) {
  const props = mergeProps(
    {
      align: "center" as const,
      size: "default" as const,
      variant: "ghost" as const
    },
    rawProps
  )
  const auth = useAuth()
  const session = useSession(auth.authClient, {
    enabled: !import.meta.env.SSR
  })
  const [isUserButtonHydrated, setIsUserButtonHydrated] = createSignal(false)
  const settingsLabel = () => auth.localization.settings.settings
  const size = () => props.size
  const contentClass = () =>
    cn(
      "w-[--kb-popper-anchor-width] min-w-40 md:min-w-56 max-w-[48svw] rounded-lg bg-popover p-1 text-popover-foreground shadow-md",
      props.align === "end" && "origin-top-right"
    )
  const triggerClass = () =>
    cn(
      buttonVariants({
        size: size() === "icon" ? "icon" : "lg",
        variant: props.variant
      }),
      size() === "icon"
        ? "rounded-full! border-0! p-0"
        : "py-2.5 h-auto font-normal justify-between gap-3 rounded-full",
      props.class
    )

  const userLinks = createMemo(() =>
    props.links?.flatMap((link) => {
      if (isUserButtonLink(link)) {
        const visibility = link.visibility ?? "always"
        if (visibility === "authenticated" && !session.data) return []
        if (visibility === "unauthenticated" && session.data) return []
      }

      return [renderUserLink(link)]
    })
  )
  const pluginUserMenuItems = createMemo(() =>
    (auth.plugins as UserMenuItemPlugin[]).flatMap((plugin) =>
      (plugin.userMenuItems ?? []).map((UserMenuItem, index) => ({
        UserMenuItem,
        id: `${plugin.id}-${index.toString()}`
      }))
    )
  )

  onMount(() => setIsUserButtonHydrated(true))

  const signInPath = auth.viewPaths.auth.signIn
  const signUpPath = auth.viewPaths.auth.signUp
  const signOutPath = auth.viewPaths.auth.signOut
  const settingsPath = auth.viewPaths.settings.account

  const userLabel = () =>
    resolveUserLabel(
      undefined,
      session.data?.user.name,
      session.data?.user.email
    )

  const userSecondaryLabel = () =>
    resolveUserSecondaryLabel(
      undefined,
      session.data?.user.name,
      session.data?.user.email
    )

  const userInitials = () =>
    resolveUserInitials(
      undefined,
      session.data?.user.name,
      session.data?.user.email
    )

  return (
    <Show
      when={isUserButtonHydrated()}
      fallback={
        <div aria-hidden="true" class={triggerClass()}>
          <Show
            when={size() === "icon"}
            fallback={
              <>
                <UserButtonPendingView />
                <ChevronsUpDown class="size-4 text-muted-foreground" />
              </>
            }
          >
            <Skeleton class="size-8 rounded-full" />
          </Show>
        </div>
      }
    >
      <DropdownMenu gutter={props.sideOffset ?? 4} modal={false}>
        <DropdownMenuTrigger class={triggerClass()}>
          <Show
            when={size() === "icon"}
            fallback={
              <>
                <div class="flex min-w-0 items-center gap-3 text-left">
                  <Show
                    when={!session.isPending}
                    fallback={<UserButtonPendingView />}
                  >
                    <UserView
                      image={session.data?.user.image}
                      initials={session.data ? userInitials() : undefined}
                      label={userLabel()}
                      secondaryLabel={userSecondaryLabel()}
                    />
                  </Show>
                </div>

                <ChevronsUpDown class="size-4 text-muted-foreground" />
              </>
            }
          >
            <Show
              when={!session.isPending}
              fallback={<Skeleton class="size-8 rounded-full" />}
            >
              <UserAvatar
                fallback={<User class="size-4" />}
                image={session.data?.user.image}
                initials={session.data ? userInitials() : undefined}
                label={userLabel()}
              />
            </Show>
          </Show>
        </DropdownMenuTrigger>

        <DropdownMenuContent
          class={contentClass()}
          style={{
            "min-width": "min(14rem, 48svw)",
            "max-width": "48svw",
            width: "max-content"
          }}
        >
          <Show when={session.data}>
            <DropdownMenuLabel class="px-2 py-1.5 text-sm font-normal text-foreground">
              <div class="flex items-center gap-3">
                <UserAvatar
                  class="size-10 rounded-full bg-muted text-muted-foreground"
                  image={session.data?.user.image}
                  initials={userInitials()}
                  label={userLabel()}
                />

                <div class="grid min-w-0 flex-1 gap-0.5">
                  <span class="truncate font-medium text-foreground">
                    {userLabel()}
                  </span>
                  <Show when={session.data?.user.email}>
                    <span class="truncate text-xs text-muted-foreground">
                      {session.data?.user.email}
                    </span>
                  </Show>
                </div>
              </div>
            </DropdownMenuLabel>

            <Separator class="my-1" />
          </Show>

          <Show
            when={!session.isPending}
            fallback={
              <DropdownMenuItem class="gap-1.5 rounded-md px-1.5 py-1 text-sm">
                <UserButtonPendingView />
              </DropdownMenuItem>
            }
          >
            <Show
              when={session.data}
              fallback={
                <>
                  {userLinks()}

                  <DropdownMenuItem class="gap-1.5 rounded-md px-1.5 py-1 text-sm focus:bg-accent focus:text-accent-foreground">
                    <Link
                      class={menuLinkClass}
                      params={{ path: signInPath }}
                      to="/auth/$path"
                    >
                      <LogIn class="size-4 text-muted-foreground" />
                      {auth.localization.auth.signIn}
                    </Link>
                  </DropdownMenuItem>

                  <DropdownMenuItem class="gap-1.5 rounded-md px-1.5 py-1 text-sm focus:bg-accent focus:text-accent-foreground">
                    <Link
                      class={menuLinkClass}
                      params={{ path: signUpPath }}
                      to="/auth/$path"
                    >
                      <UserPlus2 class="size-4 text-muted-foreground" />
                      {auth.localization.auth.signUp}
                    </Link>
                  </DropdownMenuItem>

                  <ThemeToggleItem />
                </>
              }
            >
              {userLinks()}

              <Show when={!props.hideSettings}>
                <DropdownMenuItem class="gap-1.5 rounded-md px-1.5 py-1 text-sm focus:bg-accent focus:text-accent-foreground">
                  <Link
                    class={menuLinkClass}
                    params={{ path: settingsPath }}
                    to="/settings/$path"
                  >
                    <Settings class="size-4 text-muted-foreground" />
                    {settingsLabel()}
                  </Link>
                </DropdownMenuItem>
              </Show>

              <For each={pluginUserMenuItems()}>
                {(item) => <Dynamic component={item.UserMenuItem} />}
              </For>

              <ThemeToggleItem />

              <DropdownMenuSeparator class="my-1 bg-border" />

              <DropdownMenuItem class="gap-1.5 rounded-md px-1.5 py-1 text-sm focus:bg-accent focus:text-accent-foreground">
                <Link
                  class={menuLinkClass}
                  params={{ path: signOutPath }}
                  to="/auth/$path"
                >
                  <LogOut class="size-4 text-muted-foreground" />
                  {auth.localization.auth.signOut}
                </Link>
              </DropdownMenuItem>
            </Show>
          </Show>
        </DropdownMenuContent>
      </DropdownMenu>
    </Show>
  )
}

function UserButtonHydrationFallback(rawProps: UserButtonProps = {}) {
  const props = mergeProps(
    {
      align: "center" as const,
      size: "default" as const,
      variant: "ghost" as const
    },
    rawProps
  )
  const size = () => props.size
  const triggerClass = () =>
    cn(
      buttonVariants({
        size: size() === "icon" ? "icon" : "lg",
        variant: props.variant
      }),
      size() === "icon"
        ? "rounded-full! border-0! p-0"
        : "py-2.5 h-auto font-normal justify-between gap-3 rounded-full",
      props.class
    )

  return (
    <div aria-hidden="true" class={triggerClass()}>
      <Show
        when={size() === "icon"}
        fallback={
          <>
            <UserButtonPendingView />
            <ChevronsUpDown class="size-4 text-muted-foreground" />
          </>
        }
      >
        <Skeleton class="size-8 rounded-full" />
      </Show>
    </div>
  )
}

export function UserButton(props: UserButtonProps = {}) {
  const [isMounted, setIsMounted] = createSignal(false)

  onMount(() => setIsMounted(true))

  const content = createMemo(() =>
    isMounted() ? (
      <MountedUserButton {...props} />
    ) : (
      <UserButtonHydrationFallback {...props} />
    )
  )

  return <>{content()}</>
}

// examples/next-shadcn-example/src/components/auth/user/user-button.tsx
"use client"

import {
  type MultiSessionAuthClient,
  useAuth,
  useSession,
  useSetActiveSession
} from "@better-auth-ui/react"
import {
  ChevronsUpDown,
  LogIn,
  LogOut,
  Settings,
  UserPlus2
} from "lucide-react"
import {
  type ComponentType,
  isValidElement,
  type ReactElement,
  type ReactNode
} from "react"

import { Button } from "@/components/ui/button"
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuLabel,
  DropdownMenuSeparator,
  DropdownMenuTrigger
} from "@/components/ui/dropdown-menu"
import { cn } from "@/lib/utils"
import { UserAvatar } from "./user-avatar"
import { UserView } from "./user-view"

/** Auth states a `UserButton` link can be visible in. */
export type UserButtonLinkVisibility =
  | "authenticated"
  | "unauthenticated"
  | "always"

/** A simple link entry rendered as a `DropdownMenuItem` in the `UserButton` menu. */
export type UserButtonLink = {
  /** Visible label. */
  label: ReactNode
  /** Destination URL. */
  href: string
  /** Optional leading icon. Sized/coloured to match built-in items. */
  icon?: ReactNode
  /** Forwarded to the underlying `DropdownMenuItem`. */
  variant?: "default" | "destructive"
  /**
   * When this link is visible based on auth state.
   * @default "always"
   */
  visibility?: UserButtonLinkVisibility
}

export type UserButtonProps = {
  className?: string
  align?: "center" | "end" | "start" | undefined
  sideOffset?: number
  size?: "default" | "icon"
  variant?:
    | "default"
    | "destructive"
    | "ghost"
    | "link"
    | "outline"
    | "secondary"
  /** Additional menu entries rendered above the built-in items. */
  links?: (UserButtonLink | ReactElement)[]
  /** Hide the built-in "Settings" link. Useful when replacing it via `links`. */
  hideSettings?: boolean
}

function renderUserLink(
  link: UserButtonLink | ReactElement,
  Link: ComponentType<{ href: string; children?: ReactNode }>,
  fallbackKey: string
): ReactNode {
  if (isValidElement(link)) return link

  const { label, href, icon, variant } = link
  return (
    <DropdownMenuItem key={fallbackKey} variant={variant} asChild>
      <Link href={href}>
        {icon}
        {label}
      </Link>
    </DropdownMenuItem>
  )
}

/**
 * Render a user dropdown button that shows user info, settings, theme controls, and authentication actions.
 *
 * Includes user profile, settings link, optional multi-session account switching, theme picker,
 * and sign-in/sign-up/sign-out actions depending on authentication state.
 *
 * @param className - Additional CSS classes applied to the button trigger
 * @param align - Alignment of the dropdown menu relative to the trigger
 * @param sideOffset - Offset between the trigger and the dropdown menu
 * @param size - "icon" renders only the avatar; "default" renders a full button with label and chevron
 * @param variant - Visual variant of the trigger button
 * @param links - Additional menu entries rendered above the built-in items
 * @param hideSettings - Hide the built-in "Settings" link
 * @returns The dropdown menu component with user actions
 */
export function UserButton({
  className,
  align,
  sideOffset,
  size = "default",
  variant = "ghost",
  links,
  hideSettings = false
}: UserButtonProps) {
  const { authClient, basePaths, viewPaths, localization, plugins, Link } =
    useAuth()

  const { isPending: settingActiveSession } = useSetActiveSession(
    authClient as MultiSessionAuthClient
  )
  const { data: session, isPending: sessionPending } = useSession(authClient)

  const userLinks = links?.flatMap((link, index) => {
    if (!isValidElement(link)) {
      const visibility = link.visibility ?? "always"
      if (visibility === "authenticated" && !session) return []
      if (visibility === "unauthenticated" && session) return []
    }
    return [renderUserLink(link, Link, `user-button-link-${index.toString()}`)]
  })

  return (
    <DropdownMenu>
      <DropdownMenuTrigger
        className={cn(
          size === "icon" && "rounded-full",
          size === "icon" && className
        )}
        asChild={size === "default"}
      >
        {size === "icon" ? (
          <UserAvatar />
        ) : (
          <Button
            variant={variant}
            className={cn("py-2.5 h-auto font-normal", className)}
            size="lg"
          >
            {session || sessionPending || settingActiveSession ? (
              <UserView isPending={!!settingActiveSession} />
            ) : (
              <>
                <UserAvatar />

                <div className="grid flex-1 text-left text-sm leading-tight">
                  {localization.auth.account}
                </div>
              </>
            )}

            <ChevronsUpDown className="ml-auto size-4" />
          </Button>
        )}
      </DropdownMenuTrigger>

      <DropdownMenuContent
        className="w-[--radix-dropdown-menu-trigger-width] min-w-40 md:min-w-56 max-w-[48svw]"
        sideOffset={sideOffset}
        align={align}
        onCloseAutoFocus={(e) => e.preventDefault()}
      >
        {session && (
          <>
            <DropdownMenuLabel className="text-sm font-normal">
              <UserView />
            </DropdownMenuLabel>

            <DropdownMenuSeparator />
          </>
        )}

        {session ? (
          <>
            {userLinks}

            {!hideSettings && (
              <DropdownMenuItem asChild>
                <Link
                  href={`${basePaths.settings}/${viewPaths.settings.account}`}
                >
                  <Settings className="text-muted-foreground" />

                  {localization.settings.settings}
                </Link>
              </DropdownMenuItem>
            )}

            {plugins.flatMap((plugin) =>
              plugin.userMenuItems?.map((Item, index) => (
                <Item key={`${plugin.id}-${index.toString()}`} />
              ))
            )}

            <DropdownMenuSeparator />

            <DropdownMenuItem asChild>
              <Link href={`${basePaths.auth}/${viewPaths.auth.signOut}`}>
                <LogOut className="text-muted-foreground" />

                {localization.auth.signOut}
              </Link>
            </DropdownMenuItem>
          </>
        ) : (
          <>
            {userLinks}

            <DropdownMenuItem asChild>
              <Link href={`${basePaths.auth}/${viewPaths.auth.signIn}`}>
                <LogIn className="text-muted-foreground" />

                {localization.auth.signIn}
              </Link>
            </DropdownMenuItem>

            <DropdownMenuItem asChild>
              <Link href={`${basePaths.auth}/${viewPaths.auth.signUp}`}>
                <UserPlus2 className="text-muted-foreground" />

                {localization.auth.signUp}
              </Link>
            </DropdownMenuItem>

            {plugins.flatMap((plugin) =>
              plugin.userMenuItems?.map((Item, index) => (
                <Item key={`${plugin.id}-${index.toString()}`} />
              ))
            )}
          </>
        )}
      </DropdownMenuContent>
    </DropdownMenu>
  )
}
