// examples/start-solid-zaidan-example/src/components/auth/settings/account/user-profile.tsx
import {
  fieldsWithModelValues,
  getAdditionalFieldDefaultValues,
  getAdditionalFieldSubmitValues,
  getFormFieldErrors,
  validateStringLength
} from "@better-auth-ui/core"
import { useAuth, useSession, useUpdateUser } from "@better-auth-ui/solid"
import { createEffect, For, Show } from "solid-js"
import { toast } from "solid-sonner"
import {
  createAuthForm,
  getAuthAdditionalFieldValidators,
  isAuthFormFieldInvalid
} from "@/components/auth/auth-form"
import { ChangeAvatar } from "@/components/auth/settings/account/change-avatar"
import { Card, CardContent, CardFooter } from "@/components/ui/card"
import { Field, FieldError, FieldLabel } from "@/components/ui/field"
import { Input } from "@/components/ui/input"
import { cn } from "@/lib/utils"

export type UserProfileProps = {
  class?: string
}

export function UserProfile(props: UserProfileProps = {}) {
  const auth = useAuth()
  const session = useSession(auth.authClient)
  const { mutateAsync: updateUser, isPending: updateUserPending } =
    useUpdateUser(auth.authClient, () => ({
      onSuccess: () =>
        toast.success(auth.localization.settings.profileUpdatedSuccess)
    }))

  const profileFields = () =>
    auth.additionalFields?.filter((field) => field.profile !== false) ?? []
  const hasProfileFields = () =>
    auth.profile.name ||
    profileFields().some((field) => field.inputType !== "hidden")
  const form = createAuthForm(() => ({
    defaultValues: {
      additionalFields: getAdditionalFieldDefaultValues(profileFields()),
      name: ""
    },
    onSubmit: async ({ value }) => {
      await updateUser({
        ...(auth.profile.name && { name: value.name }),
        ...getAdditionalFieldSubmitValues(
          profileFields(),
          value.additionalFields
        )
      })
    }
  }))

  createEffect(() => {
    const currentSession = session.data
    if (!currentSession) return

    form.reset({
      additionalFields: getAdditionalFieldDefaultValues(
        fieldsWithModelValues(
          profileFields(),
          currentSession.user as Record<string, unknown>
        )
      ),
      name: currentSession.user.name
    })
  })

  return (
    <Show when={auth.avatar.enabled || hasProfileFields()}>
      <div class={cn(props.class)}>
        <h2 class="mb-3 text-sm font-semibold">
          {auth.localization.settings.userProfile}
        </h2>
        <form.AppForm>
          <form.AuthFormRoot aria-label="Profile">
            <Card>
              <CardContent class="flex flex-col gap-6">
                <ChangeAvatar />

                <Show when={auth.profile.name}>
                  <form.AppField
                    name="name"
                    validators={{
                      onChange: ({ value }) =>
                        validateStringLength(value, {
                          requiredMessage: auth.localization.auth.fieldRequired,
                          trim: true
                        })
                    }}
                  >
                    {(field) => {
                      const isInvalid = () =>
                        isAuthFormFieldInvalid(field().state.meta)

                      return (
                        <Field data-invalid={isInvalid()}>
                          <FieldLabel for="settings-name">
                            {auth.localization.auth.name}
                          </FieldLabel>
                          <Input
                            aria-invalid={isInvalid()}
                            autocomplete="name"
                            disabled={updateUserPending}
                            id="settings-name"
                            name={field().name}
                            onBlur={field().handleBlur}
                            onInput={(event) =>
                              field().handleChange(event.currentTarget.value)
                            }
                            placeholder={auth.localization.auth.name}
                            value={field().state.value}
                          />
                          <FieldError
                            errors={getFormFieldErrors(
                              field().state.meta.errors
                            )}
                          />
                        </Field>
                      )
                    }}
                  </form.AppField>
                </Show>

                <For each={profileFields()}>
                  {(configuredField) => (
                    <form.AppField
                      name={`additionalFields.${configuredField.name}`}
                      validators={getAuthAdditionalFieldValidators(
                        configuredField,
                        auth.localization.auth.fieldRequired
                      )}
                    >
                      {(field) => (
                        <field.AuthFormAdditionalField
                          field={configuredField}
                          isPending={updateUserPending || !session.data}
                        />
                      )}
                    </form.AppField>
                  )}
                </For>
              </CardContent>
              <Show when={hasProfileFields()}>
                <CardFooter>
                  <form.AuthFormSubmitButton
                    aria-label="Save changes"
                    disabled={updateUserPending || !session.data}
                    size="sm"
                  >
                    {auth.localization.settings.saveChanges}
                  </form.AuthFormSubmitButton>
                </CardFooter>
              </Show>
            </Card>
          </form.AuthFormRoot>
        </form.AppForm>
      </div>
    </Show>
  )
}

// packages/heroui/src/components/auth/settings/account/user-profile.tsx
import {
  fieldsWithModelValues,
  getAdditionalFieldDefaultValues,
  getAdditionalFieldSubmitValues,
  validateStringLength
} from "@better-auth-ui/core"
import { useAuth, useSession, useUpdateUser } from "@better-auth-ui/react"
import {
  Card,
  type CardProps,
  cn,
  Input,
  Label,
  Skeleton,
  TextField,
  toast
} from "@heroui/react"
import { useEffect, useMemo } from "react"

import {
  getAuthAdditionalFieldValidators,
  isAuthFormFieldInvalid,
  useAuthForm
} from "../../auth-form"
import { ChangeAvatar } from "./change-avatar"

export type UserProfileProps = {
  className?: string
  variant?: CardProps["variant"]
}

/**
 * Render a profile card that lets the authenticated user view and update their
 * display name, avatar, and any plugin- or user-supplied additional fields.
 */
export function UserProfile({
  className,
  variant,
  ...props
}: UserProfileProps & Omit<CardProps, "children">) {
  const { additionalFields, authClient, avatar, localization, profile } =
    useAuth()
  const { data: session } = useSession(authClient)

  const { mutateAsync: updateUser, isPending } = useUpdateUser(authClient, {
    onSuccess: () => toast.success(localization.settings.profileUpdatedSuccess)
  })

  const profileFields = useMemo(
    () => additionalFields?.filter((field) => field.profile !== false) ?? [],
    [additionalFields]
  )
  const hasProfileFields =
    profile.name || profileFields.some((field) => field.inputType !== "hidden")
  const form = useAuthForm({
    defaultValues: {
      additionalFields: getAdditionalFieldDefaultValues(profileFields),
      name: ""
    },
    onSubmit: async ({ value }) => {
      await updateUser({
        ...(profile.name && { name: value.name }),
        ...getAdditionalFieldSubmitValues(profileFields, value.additionalFields)
      })
    }
  })

  useEffect(() => {
    if (!session) return
    form.reset({
      additionalFields: getAdditionalFieldDefaultValues(
        fieldsWithModelValues(
          profileFields,
          session.user as Record<string, unknown>
        )
      ),
      name: session.user.name
    })
  }, [form, profileFields, session])

  if (!avatar.enabled && !hasProfileFields) return null

  return (
    <div>
      <h2 className={cn("text-sm font-semibold mb-3")}>
        {localization.settings.userProfile}
      </h2>

      <Card className={cn("p-4 gap-4", className)} variant={variant} {...props}>
        <Card.Content>
          <form.AppForm>
            <form.AuthFormRoot className="flex flex-col gap-4">
              <ChangeAvatar />

              {profile.name && (
                <form.AppField
                  name="name"
                  validators={{
                    onChange: ({ value }) =>
                      validateStringLength(value, {
                        requiredMessage: localization.auth.fieldRequired,
                        trim: true
                      })
                  }}
                >
                  {(field) => {
                    const isInvalid = isAuthFormFieldInvalid(field.state.meta)

                    return (
                      <TextField
                        name={field.name}
                        isDisabled={isPending || !session}
                        value={field.state.value}
                        onBlur={field.handleBlur}
                        onChange={field.handleChange}
                        isInvalid={isInvalid || undefined}
                        validationBehavior="aria"
                      >
                        <Label>{localization.auth.name}</Label>

                        <Input
                          className={cn(!session && "hidden")}
                          autoComplete="name"
                          placeholder={localization.auth.name}
                          variant={
                            variant === "transparent" ? "primary" : "secondary"
                          }
                        />

                        {!session && (
                          <Skeleton className="h-10 md:h-9 w-full rounded-xl" />
                        )}

                        <field.AuthFormFieldError />
                      </TextField>
                    )
                  }}
                </form.AppField>
              )}

              {profileFields.map((configuredField) => {
                if (!session) {
                  if (configuredField.inputType === "hidden") {
                    return null
                  }

                  return (
                    <Skeleton
                      key={configuredField.name}
                      className="h-10 md:h-9 w-full rounded-xl"
                    />
                  )
                }

                return (
                  <form.AppField
                    key={configuredField.name}
                    name={`additionalFields.${configuredField.name}`}
                    validators={getAuthAdditionalFieldValidators(
                      configuredField,
                      localization.auth.fieldRequired
                    )}
                  >
                    {(field) => (
                      <field.AuthFormAdditionalField
                        field={configuredField}
                        isPending={isPending}
                        variant={variant}
                      />
                    )}
                  </form.AppField>
                )
              })}

              {hasProfileFields && (
                <form.AuthFormSubmitButton
                  isDisabled={!session}
                  size="sm"
                  className="self-start mt-1"
                >
                  {localization.settings.saveChanges}
                </form.AuthFormSubmitButton>
              )}
            </form.AuthFormRoot>
          </form.AppForm>
        </Card.Content>
      </Card>
    </div>
  )
}
