// examples/start-solid-zaidan-example/src/components/auth/organization/organization-profile.tsx
import type { OrganizationLocalization } from "@better-auth-ui/core/plugins"
import type { OrganizationAuthClient } from "@better-auth-ui/solid"
import {
  useActiveOrganization,
  useAuth,
  useUpdateOrganization
} from "@better-auth-ui/solid"
import { createEffect, createSignal, Show } from "solid-js"
import { toast } from "solid-sonner"
import { Button } from "@/components/ui/button"
import { Card, CardContent } from "@/components/ui/card"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { Skeleton } from "@/components/ui/skeleton"
import { organizationPlugin } from "@/lib/auth/organization-plugin"
import { ChangeOrganizationLogo } from "./change-organization-logo"
import { SlugField } from "./slug-field"

export type OrganizationProfileProps = {
  class?: string
}

const fallbackLocalization = {
  organizationProfile: "Organization profile",
  name: "Name",
  namePlaceholder: "Enter the organization name",
  organizationUpdatedSuccess: "Organization updated successfully"
} satisfies Pick<
  OrganizationLocalization,
  | "organizationProfile"
  | "name"
  | "namePlaceholder"
  | "organizationUpdatedSuccess"
>

export function OrganizationProfile(props: OrganizationProfileProps) {
  const auth = useAuth()
  const activeOrganization = useActiveOrganization(
    auth.authClient as OrganizationAuthClient
  )
  const updateOrganization = useUpdateOrganization(
    auth.authClient as OrganizationAuthClient,
    {
      onSuccess: () => toast.success(localization().organizationUpdatedSuccess)
    }
  )
  const [name, setName] = createSignal("")
  const [slug, setSlug] = createSignal("")
  const organizationPluginConfig = () =>
    auth.plugins.find((plugin) => plugin.id === organizationPlugin.id) as
      | { localization?: OrganizationLocalization }
      | undefined
  const localization = () =>
    organizationPluginConfig()?.localization ?? fallbackLocalization

  createEffect(() => {
    const organization = activeOrganization.data

    if (!organization) return

    setName(organization.name)
    setSlug(organization.slug)
  })

  const handleSubmit = (event: SubmitEvent) => {
    event.preventDefault()

    updateOrganization.mutate({ data: { name: name(), slug: slug() } })
  }

  return (
    <div class={props.class}>
      <h2 class="mb-3 font-semibold text-sm">
        {localization().organizationProfile}
      </h2>
      <Card>
        <CardContent>
          <form class="flex flex-col gap-4" onSubmit={handleSubmit}>
            <ChangeOrganizationLogo class="-ml-1 grid gap-2" />

            <Show
              when={activeOrganization.data}
              fallback={
                <div class="grid gap-4">
                  <Skeleton class="h-10 rounded-md" />
                  <Skeleton class="h-10 rounded-md" />
                </div>
              }
            >
              {(organization) => (
                <>
                  <div class="grid gap-2">
                    <Label for="organization-profile-name">
                      {localization().name}
                    </Label>
                    <Input
                      disabled={updateOrganization.isPending}
                      id="organization-profile-name"
                      name="name"
                      onInput={(event) => setName(event.currentTarget.value)}
                      placeholder={localization().namePlaceholder}
                      required
                      value={name()}
                    />
                  </div>

                  <SlugField
                    currentSlug={organization().slug}
                    disabled={updateOrganization.isPending}
                    id="organization-profile-slug"
                    onChange={setSlug}
                    value={slug()}
                  />
                </>
              )}
            </Show>

            <Button
              class="mt-1 w-fit"
              disabled={
                !activeOrganization.data || updateOrganization.isPending
              }
              size="sm"
              type="submit"
            >
              {auth.localization.settings.saveChanges}
            </Button>
          </form>
        </CardContent>
      </Card>
    </div>
  )
}

// examples/next-shadcn-example/src/components/auth/organization/organization-profile.tsx
"use client"

import {
  type OrganizationAuthClient,
  useActiveOrganization,
  useAuth,
  useAuthPlugin,
  useUpdateOrganization
} from "@better-auth-ui/react"
import { type SyntheticEvent, useEffect, useState } from "react"
import { toast } from "sonner"

import { Button } from "@/components/ui/button"
import { Card, CardContent } from "@/components/ui/card"
import { Field, FieldError } from "@/components/ui/field"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { Skeleton } from "@/components/ui/skeleton"
import { Spinner } from "@/components/ui/spinner"
import { organizationPlugin } from "@/lib/auth/organization-plugin"
import { cn } from "@/lib/utils"
import { ChangeOrganizationLogo } from "./change-organization-logo"
import { SlugField } from "./slug-field"

export type OrganizationProfileProps = {
  className?: string
}

/**
 * Profile card for the active organization: logo (when enabled), display name, and slug.
 */
export function OrganizationProfile({ className }: OrganizationProfileProps) {
  const { authClient, localization } = useAuth()
  const { localization: organizationLocalization } =
    useAuthPlugin(organizationPlugin)

  const { data: activeOrganization } = useActiveOrganization(
    authClient as OrganizationAuthClient
  )

  const [slug, setSlug] = useState(activeOrganization?.slug ?? "")

  useEffect(() => {
    setSlug(activeOrganization?.slug ?? "")
  }, [activeOrganization?.slug])

  const { mutate: commitOrganizationUpdate, isPending } = useUpdateOrganization(
    authClient as OrganizationAuthClient,
    {
      onSuccess: () =>
        toast.success(organizationLocalization.organizationUpdatedSuccess)
    }
  )

  function handleSubmit(e: SyntheticEvent<HTMLFormElement>) {
    e.preventDefault()
    if (!activeOrganization) return

    const formData = new FormData(e.currentTarget)
    const name = formData.get("name") as string

    commitOrganizationUpdate({
      data: { name, slug }
    })
  }

  const nameInputId = `${activeOrganization?.id ?? "org"}-name`
  const slugInputId = `${activeOrganization?.id ?? "org"}-slug`

  return (
    <div>
      <h2 className={cn("mb-3 text-sm font-semibold")}>
        {organizationLocalization.organizationProfile}
      </h2>

      <Card className={className}>
        <CardContent>
          <form onSubmit={handleSubmit} className="flex flex-col gap-4">
            <ChangeOrganizationLogo />

            <Field>
              <Label htmlFor={nameInputId}>
                {organizationLocalization.name}
              </Label>

              {activeOrganization ? (
                <Input
                  id={nameInputId}
                  name="name"
                  defaultValue={activeOrganization.name}
                  autoComplete="organization"
                  placeholder={organizationLocalization.namePlaceholder}
                  disabled={isPending}
                />
              ) : (
                <Skeleton className="h-8 w-full rounded-md" />
              )}

              <FieldError />
            </Field>

            {activeOrganization ? (
              <SlugField
                id={slugInputId}
                value={slug}
                onChange={setSlug}
                currentSlug={activeOrganization.slug}
                disabled={isPending}
              />
            ) : (
              <Field>
                <Label>{organizationLocalization.slug}</Label>
                <Skeleton className="h-8 w-full rounded-md" />
              </Field>
            )}

            <Button
              type="submit"
              disabled={isPending || !activeOrganization}
              size="sm"
              className="mt-1 w-fit"
            >
              {isPending && <Spinner />}

              {localization.settings.saveChanges}
            </Button>
          </form>
        </CardContent>
      </Card>
    </div>
  )
}
