// examples/start-solid-zaidan-example/src/components/auth/email-otp/reset-password-otp.tsx
import {
  type EmailOtpAuthClient,
  resetPasswordOtpOptions,
  useAuth,
  useAuthPlugin
} from "@better-auth-ui/solid"
import { createMutation } from "@tanstack/solid-query"
import { Link } from "@tanstack/solid-router"
import { createSignal, Show } from "solid-js"
import { toast } from "solid-sonner"

import { OpenEmailButton } from "@/components/auth/open-email-button"
import { OtpField } from "@/components/auth/otp-field"
import { Button } from "@/components/ui/button"
import {
  Card,
  CardContent,
  CardDescription,
  CardFooter,
  CardHeader,
  CardTitle
} from "@/components/ui/card"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { Spinner } from "@/components/ui/spinner"
import { emailOtpPlugin } from "@/lib/auth/email-otp-plugin"
import { cn } from "@/lib/utils"
import { RESET_PASSWORD_OTP_STORAGE_KEY } from "./forgot-password-otp"

export type ResetPasswordOtpProps = {
  class?: string
}

/**
 * Reset a password with an emailed code.
 *
 * Replaces the built-in `<ResetPassword />` view when the email-OTP plugin
 * runs with `passwordReset: true`. There is no token in the URL — the code
 * and the new password are submitted together. The address comes from the
 * forgot-password step, and is asked for again when it isn't there (e.g. the
 * user finishes on another tab).
 */
export function ResetPasswordOtp(props: ResetPasswordOtpProps) {
  const auth = useAuth()
  const { localization: emailOtpLocalization, otpLength } =
    useAuthPlugin(emailOtpPlugin)

  const storedEmail =
    typeof sessionStorage === "undefined"
      ? ""
      : (sessionStorage.getItem(RESET_PASSWORD_OTP_STORAGE_KEY) ?? "")

  const hasStoredEmail = Boolean(storedEmail)
  const [email, setEmail] = createSignal(storedEmail)
  const [code, setCode] = createSignal("")
  const [passwordError, setPasswordError] = createSignal<string>()
  let formRef: HTMLFormElement | undefined
  let submissionLocked = false

  const resetPassword = createMutation(() => ({
    ...resetPasswordOtpOptions(auth.authClient as EmailOtpAuthClient),
    onError: () => {
      submissionLocked = false
      setCode("")
    },
    onSuccess: () => {
      sessionStorage.removeItem(RESET_PASSWORD_OTP_STORAGE_KEY)
      toast.success(auth.localization.auth.passwordResetSuccess)
      auth.navigate({
        to: `${auth.basePaths.auth}/${auth.viewPaths.auth.signIn}`
      })
    }
  }))

  const submitReset = (
    form: HTMLFormElement,
    submittedCode: string,
    reportErrors: boolean
  ) => {
    if (resetPassword.isPending || submissionLocked) return

    const formData = new FormData(form)
    const password = formData.get("password") as string
    const confirmPassword = formData.get("confirmPassword") as string

    if (
      auth.emailAndPassword?.confirmPassword &&
      password !== confirmPassword
    ) {
      if (reportErrors) {
        toast.error(auth.localization.auth.passwordsDoNotMatch)
      }
      return
    }

    if (submittedCode.length !== otpLength) {
      if (reportErrors) {
        toast.error(
          emailOtpLocalization.codeLengthMismatch.replace(
            "{{length}}",
            String(otpLength)
          )
        )
      }
      return
    }

    submissionLocked = true
    resetPassword.mutate({
      email: hasStoredEmail ? email() : (formData.get("email") as string),
      otp: submittedCode,
      password
    } as Parameters<typeof resetPassword.mutate>[0])
  }

  const tryAutoSubmit = (completedCode?: string) => {
    if (!formRef?.matches(":valid")) return

    const formData = new FormData(formRef)
    const submittedCode = completedCode ?? String(formData.get("otp") ?? "")

    submitReset(formRef, submittedCode, false)
  }

  const submit = (event: SubmitEvent & { currentTarget: HTMLFormElement }) => {
    event.preventDefault()
    submitReset(event.currentTarget, code(), true)
  }

  return (
    <Card class={cn("w-full max-w-sm", props.class)}>
      <CardHeader>
        <CardTitle class="text-xl font-semibold">
          {auth.localization.auth.resetPassword}
        </CardTitle>

        <Show when={hasStoredEmail && email()}>
          <CardDescription>
            {emailOtpLocalization.codeSentTo.replace("{{email}}", email())}
          </CardDescription>
        </Show>
      </CardHeader>

      <CardContent>
        <form
          ref={formRef}
          aria-label={auth.localization.auth.resetPassword}
          onSubmit={submit}
        >
          <div class="grid gap-3">
            <Show when={!hasStoredEmail}>
              <Label for="reset-password-email">
                {auth.localization.auth.email}
              </Label>

              <Input
                autocomplete="email"
                disabled={resetPassword.isPending}
                id="reset-password-email"
                name="email"
                onInput={(event) => setEmail(event.currentTarget.value)}
                placeholder={auth.localization.auth.emailPlaceholder}
                required
                type="email"
                value={email()}
              />
            </Show>

            <OtpField
              autofocus={hasStoredEmail}
              disabled={resetPassword.isPending}
              id="reset-password-code"
              label={emailOtpLocalization.code}
              length={otpLength}
              name="otp"
              onInput={setCode}
              onComplete={tryAutoSubmit}
              value={code()}
            />

            <Label for="reset-password-password">
              {auth.localization.auth.newPassword}
            </Label>

            <Input
              aria-invalid={Boolean(passwordError())}
              autocomplete="new-password"
              disabled={resetPassword.isPending}
              id="reset-password-password"
              maxLength={auth.emailAndPassword?.maxPasswordLength}
              minLength={auth.emailAndPassword?.minPasswordLength}
              name="password"
              onInput={() => setPasswordError(undefined)}
              onInvalid={(event) => {
                event.preventDefault()
                setPasswordError(event.currentTarget.validationMessage)
              }}
              placeholder={auth.localization.auth.newPasswordPlaceholder}
              required
              type="password"
            />

            <Show when={passwordError()}>
              {(message) => (
                <p class="text-sm text-destructive" role="alert">
                  {message()}
                </p>
              )}
            </Show>

            <Show when={auth.emailAndPassword?.confirmPassword}>
              <Label for="reset-password-confirm">
                {auth.localization.auth.confirmPassword}
              </Label>

              <Input
                autocomplete="new-password"
                disabled={resetPassword.isPending}
                id="reset-password-confirm"
                maxLength={auth.emailAndPassword?.maxPasswordLength}
                minLength={auth.emailAndPassword?.minPasswordLength}
                name="confirmPassword"
                placeholder={auth.localization.auth.confirmPasswordPlaceholder}
                required
                type="password"
              />
            </Show>

            <Button
              class="w-full"
              disabled={resetPassword.isPending}
              type="submit"
            >
              <Show when={resetPassword.isPending}>
                <Spinner />
              </Show>

              {auth.localization.auth.resetPassword}
            </Button>

            <Show when={email()}>
              <OpenEmailButton email={email()} variant="secondary" />
            </Show>
          </div>
        </form>
      </CardContent>

      <CardFooter class="justify-center">
        <p class="text-sm text-muted-foreground">
          {auth.localization.auth.rememberYourPassword}{" "}
          <Link
            class="underline underline-offset-4"
            params={{ path: auth.viewPaths.auth.signIn }}
            to="/auth/$path"
          >
            {auth.localization.auth.signIn}
          </Link>
        </p>
      </CardFooter>
    </Card>
  )
}

// packages/heroui/src/components/auth/email-otp/reset-password-otp.tsx
import {
  type EmailOtpAuthClient,
  useAuth,
  useAuthPlugin,
  useResetPasswordOtp
} from "@better-auth-ui/react"
import { Eye, EyeSlash } from "@gravity-ui/icons"
import {
  Button,
  Card,
  type CardProps,
  cn,
  Description,
  FieldError,
  Form,
  Input,
  InputGroup,
  Label,
  Link,
  Spinner,
  TextField,
  toast,
  useIsHydrated
} from "@heroui/react"
import { type SyntheticEvent, useEffect, useRef, useState } from "react"

import { emailOtpPlugin } from "../../../lib/auth/email-otp-plugin"
import { OpenEmailButton } from "../open-email-button"
import { OtpField } from "../otp-field"
import { RESET_PASSWORD_OTP_STORAGE_KEY } from "./forgot-password-otp"

export type ResetPasswordOtpProps = {
  className?: string
  variant?: CardProps["variant"]
}

/**
 * Reset a password with an emailed code.
 *
 * Replaces the built-in `<ResetPassword />` view when the email-OTP plugin
 * runs with `passwordReset: true`. There is no token in the URL — the code
 * and the new password are submitted together. The address comes from the
 * forgot-password step, and is asked for again when it isn't there (e.g. the
 * user finishes on another tab).
 *
 * @param className - Additional CSS classes applied to the card.
 * @param variant - Card variant.
 */
export function ResetPasswordOtp({
  className,
  variant
}: ResetPasswordOtpProps) {
  const {
    authClient,
    basePaths,
    emailAndPassword,
    localization,
    navigate,
    viewPaths
  } = useAuth()
  const { localization: emailOtpLocalization, otpLength } =
    useAuthPlugin(emailOtpPlugin)

  const isHydrated = useIsHydrated()
  const initialEmail =
    (isHydrated && sessionStorage.getItem(RESET_PASSWORD_OTP_STORAGE_KEY)) || ""
  const [email, setEmail] = useState(initialEmail)
  const [hasStoredEmail, setHasStoredEmail] = useState(Boolean(initialEmail))
  const [code, setCode] = useState("")
  const [isPasswordVisible, setIsPasswordVisible] = useState(false)
  const [isConfirmPasswordVisible, setIsConfirmPasswordVisible] =
    useState(false)
  const formRef = useRef<HTMLFormElement>(null)
  const submissionLockedRef = useRef(false)

  useEffect(() => {
    const storedEmail =
      sessionStorage.getItem(RESET_PASSWORD_OTP_STORAGE_KEY) ?? ""
    setEmail(storedEmail)
    setHasStoredEmail(Boolean(storedEmail))
  }, [])

  const { mutate: resetPasswordOtp, isPending } = useResetPasswordOtp(
    authClient as EmailOtpAuthClient,
    {
      onError: () => {
        submissionLockedRef.current = false
        setCode("")
      },
      onSuccess: () => {
        sessionStorage.removeItem(RESET_PASSWORD_OTP_STORAGE_KEY)
        toast.success(localization.auth.passwordResetSuccess)
        navigate({ to: `${basePaths.auth}/${viewPaths.auth.signIn}` })
      }
    }
  )

  const validatePassword = (value: string) => {
    if (!value) return localization.auth.fieldRequired
    const min = emailAndPassword?.minPasswordLength
    const max = emailAndPassword?.maxPasswordLength
    if (min && value.length < min)
      return localization.auth.tooShort.replace("{{min}}", String(min))
    if (max && value.length > max)
      return localization.auth.tooLong.replace("{{max}}", String(max))
  }

  const submitReset = (
    form: HTMLFormElement,
    submittedCode: string,
    reportErrors: boolean
  ) => {
    if (isPending || submissionLockedRef.current) return

    const formData = new FormData(form)
    const password = formData.get("password") as string
    const confirmPassword = formData.get("confirmPassword") as string
    const submittedEmail = hasStoredEmail
      ? email
      : (formData.get("email") as string)

    if (emailAndPassword?.confirmPassword && password !== confirmPassword) {
      if (reportErrors) {
        toast.danger(localization.auth.passwordsDoNotMatch)
      }
      return
    }

    if (submittedCode.length !== otpLength) {
      if (reportErrors) {
        toast.danger(
          emailOtpLocalization.codeLengthMismatch.replace(
            "{{length}}",
            String(otpLength)
          )
        )
      }
      return
    }

    submissionLockedRef.current = true
    resetPasswordOtp({ email: submittedEmail, otp: submittedCode, password })
  }

  const tryAutoSubmit = (completedCode?: string) => {
    const form = formRef.current

    if (!form?.matches(":valid")) return

    const formData = new FormData(form)
    const submittedCode = completedCode ?? String(formData.get("otp") ?? "")

    submitReset(form, submittedCode, false)
  }

  const handleSubmit = (e: SyntheticEvent<HTMLFormElement>) => {
    e.preventDefault()
    submitReset(e.currentTarget, code, true)
  }

  return (
    <Card
      className={cn("w-full max-w-sm gap-4 md:p-6", className)}
      variant={variant}
    >
      <Card.Header>
        <Card.Title className="text-xl font-semibold mb-1">
          {localization.auth.resetPassword}
        </Card.Title>

        {hasStoredEmail && email && (
          <Card.Description>
            {emailOtpLocalization.codeSentTo.replace("{{email}}", email)}
          </Card.Description>
        )}
      </Card.Header>

      <Card.Content className="gap-4">
        <Form
          ref={formRef}
          className="flex flex-col gap-4"
          onSubmit={handleSubmit}
        >
          {!hasStoredEmail && (
            <TextField
              name="email"
              type="email"
              autoComplete="email"
              isDisabled={isPending}
              value={email}
              onChange={setEmail}
              validate={(value) => {
                if (!value) return localization.auth.fieldRequired
                if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(value))
                  return localization.auth.invalidEmail
              }}
            >
              <Label>{localization.auth.email}</Label>

              <Input
                placeholder={localization.auth.emailPlaceholder}
                required
                variant={variant === "transparent" ? "primary" : "secondary"}
              />

              <FieldError />
            </TextField>
          )}

          <OtpField
            autoFocus={hasStoredEmail}
            isDisabled={isPending}
            label={emailOtpLocalization.code}
            length={otpLength}
            name="otp"
            value={code}
            variant={variant}
            onChange={setCode}
            onComplete={tryAutoSubmit}
          />

          <TextField
            minLength={emailAndPassword?.minPasswordLength}
            maxLength={emailAndPassword?.maxPasswordLength}
            name="password"
            autoComplete="new-password"
            isDisabled={isPending}
            validate={validatePassword}
          >
            <Label>{localization.auth.newPassword}</Label>

            <InputGroup
              variant={variant === "transparent" ? "primary" : "secondary"}
            >
              <InputGroup.Input
                name="password"
                placeholder={localization.auth.newPasswordPlaceholder}
                type={isPasswordVisible ? "text" : "password"}
                required
              />

              <InputGroup.Suffix className="px-0">
                <Button
                  isIconOnly
                  aria-label={
                    isPasswordVisible
                      ? localization.auth.hidePassword
                      : localization.auth.showPassword
                  }
                  size="sm"
                  variant="ghost"
                  onPress={() => setIsPasswordVisible(!isPasswordVisible)}
                  isDisabled={isPending}
                >
                  {isPasswordVisible ? <EyeSlash /> : <Eye />}
                </Button>
              </InputGroup.Suffix>
            </InputGroup>

            <FieldError />
          </TextField>

          {emailAndPassword?.confirmPassword && (
            <TextField
              minLength={emailAndPassword?.minPasswordLength}
              maxLength={emailAndPassword?.maxPasswordLength}
              name="confirmPassword"
              autoComplete="new-password"
              isDisabled={isPending}
              validate={validatePassword}
            >
              <Label>{localization.auth.confirmPassword}</Label>

              <InputGroup
                variant={variant === "transparent" ? "primary" : "secondary"}
              >
                <InputGroup.Input
                  name="confirmPassword"
                  placeholder={localization.auth.confirmPasswordPlaceholder}
                  type={isConfirmPasswordVisible ? "text" : "password"}
                  required
                />

                <InputGroup.Suffix className="px-0">
                  <Button
                    isIconOnly
                    aria-label={
                      isConfirmPasswordVisible
                        ? localization.auth.hidePassword
                        : localization.auth.showPassword
                    }
                    size="sm"
                    variant="ghost"
                    onPress={() =>
                      setIsConfirmPasswordVisible(!isConfirmPasswordVisible)
                    }
                    isDisabled={isPending}
                  >
                    {isConfirmPasswordVisible ? <EyeSlash /> : <Eye />}
                  </Button>
                </InputGroup.Suffix>
              </InputGroup>

              <FieldError />
            </TextField>
          )}

          <div className="flex flex-col gap-3">
            <Button type="submit" className="w-full" isPending={isPending}>
              {isPending && <Spinner color="current" size="sm" />}

              {localization.auth.resetPassword}
            </Button>

            {email && <OpenEmailButton email={email} variant="secondary" />}
          </div>
        </Form>
      </Card.Content>

      <Card.Footer className="flex-col gap-3">
        <Description className="text-sm">
          {localization.auth.rememberYourPassword}{" "}
          <Link
            href={`${basePaths.auth}/${viewPaths.auth.signIn}`}
            className="text-accent no-underline hover:underline decoration-accent-hover"
          >
            {localization.auth.signIn}
          </Link>
        </Description>
      </Card.Footer>
    </Card>
  )
}
