// apps/docs/src/components/user/user-view.tsx
"use client"

import { useAuth, useSession } from "@better-auth-ui/react"
import type { User } from "better-auth"

import { Skeleton } from "@/components/ui/skeleton"
import { cn } from "@/lib/utils"
import { UserAvatar } from "./user-avatar"

export type UserViewProps = {
  className?: string
  isPending?: boolean
  /** @remarks `User` */
  user?: User & { username?: string | null; displayUsername?: string | null }
}

/**
 * Render a compact user item with an avatar, a primary label (display username, name, or email), and an optional secondary email line.
 *
 * @param isPending - If true and no `user` prop is provided, renders a loading skeleton instead of user details
 * @param className - Additional CSS classes applied to the outer container
 * @param user - Optional user object to display; when omitted the current session user is used
 * @returns A React element showing the user's avatar with their identifying information
 */
export function UserView({ className, isPending, user }: UserViewProps) {
  const { authClient } = useAuth()
  const { data: session, isPending: sessionPending } = useSession(authClient, {
    enabled: !user && !isPending
  })

  const resolvedUser = user ?? session?.user

  if ((isPending || sessionPending) && !user) {
    return (
      <div className={cn("flex items-center gap-2", className)}>
        <UserAvatar isPending />

        <div className="grid flex-1 gap-1 text-left text-sm">
          <Skeleton className="h-4 w-24" />
          <Skeleton className="h-3 w-32" />
        </div>
      </div>
    )
  }

  return (
    <div className={cn("flex items-center gap-2", className)}>
      <UserAvatar user={resolvedUser} />

      <div className="grid flex-1 text-left text-sm leading-tight">
        <span className="truncate font-medium text-foreground">
          {resolvedUser?.displayUsername ||
            resolvedUser?.name ||
            resolvedUser?.email}
        </span>

        {(resolvedUser?.displayUsername || resolvedUser?.name) && (
          <span className="text-muted-foreground truncate text-xs">
            {resolvedUser?.email}
          </span>
        )}
      </div>
    </div>
  )
}

// examples/start-solid-zaidan-example/src/components/auth/user/user-view.tsx
import { useAuth, useSession } from "@better-auth-ui/solid"
import type { User as AuthUserBase } from "better-auth"
import { Show } from "solid-js"
import { Skeleton } from "@/components/ui/skeleton"
import { cn } from "@/lib/utils"
import { UserAvatar } from "./user-avatar"

type AuthUser = AuthUserBase & {
  displayUsername?: string | null
  username?: string | null
}

export type UserViewProps = {
  class?: string
  image?: string | null
  initials?: string
  isPending?: boolean
  label?: string
  secondaryLabel?: string | null
  user?: AuthUser
}

const resolvePrimaryLabel = (user?: AuthUser, label?: string) =>
  label ??
  user?.displayUsername ??
  user?.username ??
  user?.name ??
  user?.email ??
  "Account"

const resolveSecondaryLabel = (
  user?: AuthUser,
  secondaryLabel?: string | null
) =>
  secondaryLabel ??
  (user?.displayUsername || user?.username || user?.name
    ? user?.email
    : undefined)

export function UserView(props: UserViewProps) {
  const auth = useAuth()
  const session = useSession(auth.authClient, {
    enabled: !props.user && !props.isPending && !props.label
  })
  const sessionPending = () => session.isPending
  const resolvedUser = () =>
    props.user ?? (session.data?.user as AuthUser | undefined)
  const label = () => resolvePrimaryLabel(resolvedUser(), props.label)
  const secondaryLabel = () =>
    resolveSecondaryLabel(resolvedUser(), props.secondaryLabel)

  if ((props.isPending || sessionPending()) && !props.user && !props.label) {
    return (
      <div class={cn("flex items-center gap-2", props.class)}>
        <UserAvatar isPending />
        <div class="grid flex-1 gap-1 text-left text-sm">
          <Skeleton class="h-4 w-24" />
          <Skeleton class="h-3 w-32" />
        </div>
      </div>
    )
  }

  return (
    <div class={cn("contents", props.class)}>
      <UserAvatar
        user={resolvedUser()}
        image={props.image}
        initials={props.initials}
        label={label()}
      />

      <div class="grid min-w-0 flex-1 gap-0.5 text-sm">
        <span class="truncate font-medium leading-4 text-foreground">
          {label()}
        </span>

        <Show when={secondaryLabel()}>
          <span class="truncate text-xs leading-4 text-muted-foreground">
            {secondaryLabel()}
          </span>
        </Show>
      </div>
    </div>
  )
}
