// packages/heroui/src/components/auth/magic-link/magic-link.tsx
import { authMutationKeys } from "@better-auth-ui/core"
import {
  type MagicLinkAuthClient,
  useAuth,
  useAuthPlugin,
  useSignInMagicLink
} from "@better-auth-ui/react"
import {
  Button,
  Card,
  type CardProps,
  cn,
  Description,
  FieldError,
  Form,
  Input,
  Label,
  Link,
  Spinner,
  TextField,
  toast
} from "@heroui/react"
import { useIsMutating } from "@tanstack/react-query"
import { type SyntheticEvent, useState } from "react"

import { magicLinkPlugin } from "../../../lib/auth/magic-link-plugin"
import { FieldSeparator } from "../field-separator"
import { ProviderButtons, type SocialLayout } from "../provider-buttons"

export type MagicLinkProps = {
  className?: string
  socialLayout?: SocialLayout
  socialPosition?: "top" | "bottom"
  variant?: CardProps["variant"]
}

/**
 * Magic-link sign-in form.
 *
 * @param socialLayout - Provider button layout.
 * @param socialPosition - `"top"` or `"bottom"`. Defaults to `"bottom"`.
 * @param variant - Card variant.
 */
export function MagicLink({
  className,
  socialLayout,
  socialPosition = "bottom",
  variant
}: MagicLinkProps) {
  const {
    authClient,
    basePaths,
    baseURL,
    emailAndPassword,
    localization,
    plugins,
    redirectTo,
    socialProviders,
    viewPaths
  } = useAuth()
  const { localization: magicLinkLocalization } = useAuthPlugin(magicLinkPlugin)

  const [email, setEmail] = useState("")

  const { mutate: signInMagicLink, isPending: signInMagicLinkPending } =
    useSignInMagicLink(authClient as MagicLinkAuthClient, {
      onSuccess: () => {
        setEmail("")
        toast.success(magicLinkLocalization.magicLinkSent)
      }
    })

  const signInMutating = useIsMutating({
    mutationKey: authMutationKeys.signIn.all
  })
  const signUpMutating = useIsMutating({
    mutationKey: authMutationKeys.signUp.all
  })
  const isPending = signInMutating + signUpMutating > 0

  const handleSubmit = (e: SyntheticEvent<HTMLFormElement>) => {
    e.preventDefault()
    signInMagicLink({ email, callbackURL: `${baseURL}${redirectTo}` })
  }

  const showSeparator = !!socialProviders?.length

  return (
    <Card
      className={cn("w-full max-w-sm gap-4 md:p-6", className)}
      variant={variant}
    >
      <Card.Header>
        <Card.Title className="text-xl font-semibold mb-1">
          {localization.auth.signIn}
        </Card.Title>
      </Card.Header>

      <Card.Content className="gap-4">
        {socialPosition === "top" && (
          <>
            {!!socialProviders?.length && (
              <ProviderButtons socialLayout={socialLayout} />
            )}

            {showSeparator && (
              <FieldSeparator>{localization.auth.or}</FieldSeparator>
            )}
          </>
        )}

        <Form onSubmit={handleSubmit} className="flex flex-col gap-4">
          <TextField
            name="email"
            type="email"
            autoComplete="email"
            isDisabled={isPending}
            value={email}
            onChange={setEmail}
          >
            <Label>{localization.auth.email}</Label>

            <Input
              placeholder={localization.auth.emailPlaceholder}
              required
              variant={variant === "transparent" ? "primary" : "secondary"}
            />

            <FieldError />
          </TextField>

          <div className="flex flex-col gap-3">
            <Button type="submit" className="w-full" isPending={isPending}>
              {signInMagicLinkPending && <Spinner color="current" size="sm" />}

              {magicLinkLocalization.sendMagicLink}
            </Button>

            {plugins.flatMap((plugin) =>
              (plugin.authButtons ?? []).map((AuthButton, index) => (
                <AuthButton
                  key={`${plugin.id}-${index.toString()}`}
                  view="magicLink"
                />
              ))
            )}
          </div>
        </Form>

        {socialPosition === "bottom" && (
          <>
            {showSeparator && (
              <FieldSeparator>{localization.auth.or}</FieldSeparator>
            )}

            {!!socialProviders?.length && (
              <ProviderButtons socialLayout={socialLayout} />
            )}
          </>
        )}
      </Card.Content>

      {emailAndPassword?.enabled && (
        <Card.Footer className="flex-col gap-3">
          <Description className="text-sm">
            {localization.auth.needToCreateAnAccount}{" "}
            <Link
              href={`${basePaths.auth}/${viewPaths.auth.signUp}`}
              className="text-accent no-underline hover:underline decoration-accent-hover"
            >
              {localization.auth.signUp}
            </Link>
          </Description>
        </Card.Footer>
      )}
    </Card>
  )
}

// examples/start-solid-zaidan-example/src/components/auth/magic-link.tsx
import {
  magicLinkPlugin as coreMagicLinkPlugin,
  type MagicLinkLocalization,
  magicLinkLocalization
} from "@better-auth-ui/core/plugins"
import {
  type MagicLinkAuthClient,
  signInMagicLinkOptions,
  useAuth
} from "@better-auth-ui/solid"
import type { AuthPlugin } from "@better-auth-ui/solid/plugins"
import { createMutation } from "@tanstack/solid-query"
import { Link } from "@tanstack/solid-router"
import { type Component, createSignal, For, Show } from "solid-js"
import { toast } from "solid-sonner"
import {
  ProviderButtons,
  type SocialLayout
} from "@/components/auth/provider-buttons"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { cn } from "@/lib/utils"

export type MagicLinkProps = {
  class?: string
  socialLayout?: SocialLayout
  socialPosition?: "bottom" | "top"
}

type AuthButtonComponent = Component<{ view?: string }>

type AuthPluginWithButtons = AuthPlugin & {
  authButtons?: AuthButtonComponent[]
}

export function MagicLink(props: MagicLinkProps) {
  const auth = useAuth()
  const [email, setEmail] = createSignal("")
  const [emailError, setEmailError] = createSignal<string>()
  const magicLinkPluginConfig = () =>
    auth.plugins.find((plugin) => plugin.id === coreMagicLinkPlugin.id)
  const magicLinkLabels = (): MagicLinkLocalization => ({
    ...magicLinkLocalization,
    ...(magicLinkPluginConfig()?.localization as
      | Partial<MagicLinkLocalization>
      | undefined)
  })
  const signInMagicLink = createMutation(() => ({
    ...signInMagicLinkOptions(auth.authClient as MagicLinkAuthClient),
    onSuccess: () => {
      setEmail("")
      toast.success(magicLinkLabels().magicLinkSent)
    }
  }))
  const showSeparator = () => Boolean(auth.socialProviders?.length)
  const socialPosition = () => props.socialPosition ?? "bottom"

  const submitMagicLink = (
    event: SubmitEvent & { currentTarget: HTMLFormElement }
  ) => {
    event.preventDefault()
    signInMagicLink.mutate({
      callbackURL: `${auth.baseURL}${auth.redirectTo}`,
      email: email()
    } as Parameters<typeof signInMagicLink.mutate>[0])
  }

  return (
    <Card class={cn("w-full max-w-sm", props.class)}>
      <CardHeader>
        <CardTitle class="text-xl font-semibold">
          {auth.localization.auth.signIn}
        </CardTitle>
      </CardHeader>
      <CardContent>
        <div class="flex flex-col gap-6">
          <Show
            when={socialPosition() === "top" && auth.socialProviders?.length}
          >
            <ProviderButtons socialLayout={props.socialLayout} />
            <Show when={showSeparator()}>
              <div class="text-center text-muted-foreground text-xs">
                {auth.localization.auth.or}
              </div>
            </Show>
          </Show>
          <form aria-label="Magic link" onSubmit={submitMagicLink}>
            <div class="grid gap-3">
              <Label for="magic-link-email">
                {auth.localization.auth.email}
              </Label>
              <Input
                aria-invalid={Boolean(emailError())}
                autocomplete="email"
                disabled={signInMagicLink.isPending}
                id="magic-link-email"
                name="email"
                onInput={(event) => {
                  setEmail(event.currentTarget.value)
                  setEmailError(undefined)
                }}
                onInvalid={(event) => {
                  event.preventDefault()
                  setEmailError(event.currentTarget.validationMessage)
                }}
                placeholder={auth.localization.auth.emailPlaceholder}
                required
                type="email"
                value={email()}
              />
              <Show when={emailError()}>
                {(message) => <p role="alert">{message()}</p>}
              </Show>
              <div class="flex flex-col gap-3">
                <Button disabled={signInMagicLink.isPending} type="submit">
                  {magicLinkLabels().sendMagicLink}
                </Button>

                <For
                  each={(auth.plugins as AuthPluginWithButtons[]).flatMap(
                    (plugin) =>
                      (plugin.authButtons ?? []).map((AuthButton) => ({
                        AuthButton
                      }))
                  )}
                >
                  {({ AuthButton }) => <AuthButton view="magicLink" />}
                </For>
              </div>
            </div>
          </form>
          <Show
            when={socialPosition() === "bottom" && auth.socialProviders?.length}
          >
            <Show when={showSeparator()}>
              <div class="text-center text-muted-foreground text-xs">
                {auth.localization.auth.or}
              </div>
            </Show>
            <ProviderButtons socialLayout={props.socialLayout} />
          </Show>
        </div>
        <Show when={auth.emailAndPassword?.enabled}>
          <p class="mt-4 text-center text-muted-foreground text-sm">
            {auth.localization.auth.needToCreateAnAccount}{" "}
            <Link
              params={{ path: auth.viewPaths.auth.signUp }}
              to="/auth/$path"
            >
              {auth.localization.auth.signUp}
            </Link>
          </p>
        </Show>
      </CardContent>
    </Card>
  )
}
