// examples/start-shadcn-example/src/components/auth/sign-out.tsx
"use client"

import { useAuth, useSignOut } from "@better-auth-ui/react"
import { useEffect, useRef } from "react"
import { toast } from "sonner"

import { Spinner } from "@/components/ui/spinner"
import { cn } from "@/lib/utils"

export type SignOutProps = {
  className?: string
}

/**
 * Signs the current user out on mount and renders a centered spinner while the operation completes.
 *
 * @param className - Optional additional class names appended to the root element
 * @returns The spinner shown during sign-out
 */
export function SignOut({ className }: SignOutProps) {
  const { basePaths, navigate, viewPaths } = useAuth()

  const { mutate: signOut } = useSignOut({
    onError: (error) => {
      toast.error(error.error?.message || error.message)
      navigate({
        to: `${basePaths.auth}/${viewPaths.auth.signIn}`,
        replace: true
      })
    },
    onSuccess: () =>
      navigate({
        to: `${basePaths.auth}/${viewPaths.auth.signIn}`,
        replace: true
      })
  })

  const hasSignedOut = useRef(false)

  useEffect(() => {
    if (hasSignedOut.current) return
    hasSignedOut.current = true

    signOut()
  }, [signOut])

  return <Spinner className={cn("mx-auto my-auto", className)} />
}

// examples/start-solid-zaidan-example/src/components/auth/sign-out.tsx
import { useAuth } from "@better-auth-ui/solid"
import { onMount } from "solid-js"
import { Spinner } from "@/components/ui/spinner"
import { cn } from "@/lib/utils"

export type SignOutProps = {
  class?: string
}

const signInHref = (basePath: string, signInPath: string) =>
  `${basePath}/${signInPath}`

export function SignOut(props: SignOutProps) {
  const auth = useAuth()
  let hasRequestedSignOut = false

  onMount(async () => {
    if (hasRequestedSignOut) return
    hasRequestedSignOut = true

    try {
      await auth.authClient.signOut({ fetchOptions: { throw: true } })
    } finally {
      auth.navigate({
        to: signInHref(auth.basePaths.auth, auth.viewPaths.auth.signIn),
        replace: true
      })
    }
  })

  return <Spinner class={cn("mx-auto my-auto", props.class)} />
}
