// apps/docs/src/components/auth/sign-up.tsx
"use client"

import {
  authMutationKeys,
  parseAdditionalFieldValue
} from "@better-auth-ui/core"
import { useAuth, useFetchOptions, useSignUpEmail } from "@better-auth-ui/react"
import { useIsMutating } from "@tanstack/react-query"
import { Eye, EyeOff } from "lucide-react"
import { type SyntheticEvent, useState } from "react"
import { toast } from "sonner"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import {
  Field,
  FieldDescription,
  FieldError,
  FieldGroup,
  FieldSeparator
} from "@/components/ui/field"
import { Input } from "@/components/ui/input"
import {
  InputGroup,
  InputGroupAddon,
  InputGroupButton,
  InputGroupInput
} from "@/components/ui/input-group"
import { Spinner } from "@/components/ui/spinner"
import { cn } from "@/lib/utils"
import { Label } from "../ui/label"
import { AdditionalField } from "./additional-field"
import { ProviderButtons, type SocialLayout } from "./provider-buttons"

export type SignUpProps = {
  className?: string
  socialLayout?: SocialLayout
  socialPosition?: "top" | "bottom"
}

/**
 * Renders a sign-up form with name, email, and password fields, optional social provider buttons, and submission handling.
 *
 * Submits credentials to the configured auth client and handles the response:
 * - If email verification is required, shows a notification and navigates to sign-in
 * - On success, refreshes the session and navigates to the configured redirect path
 * - On failure, displays error toasts
 * - Manages a pending state while the request is in-flight
 *
 * @param className - Additional CSS classes applied to the outer container
 * @param socialLayout - Social layout to apply to the component
 * @param socialPosition - Social position to apply to the component
 * @returns The sign-up form React element.
 */
export function SignUp({
  className,
  socialLayout,
  socialPosition = "bottom"
}: SignUpProps) {
  const {
    additionalFields,
    authClient,
    basePaths,
    emailAndPassword,
    localization,
    plugins,
    redirectTo,
    socialProviders,
    viewPaths,
    navigate,
    Link
  } = useAuth()

  const { fetchOptions, resetFetchOptions } = useFetchOptions()

  const [password, setPassword] = useState("")
  const [confirmPassword, setConfirmPassword] = useState("")

  const { mutate: signUpEmail, isPending: signUpEmailPending } = useSignUpEmail(
    authClient,
    {
      onError: () => {
        setPassword("")
        setConfirmPassword("")
        resetFetchOptions()
      },
      onSuccess: () => {
        if (emailAndPassword?.requireEmailVerification) {
          toast.success(localization.auth.verifyYourEmail)
          navigate({ to: `${basePaths.auth}/${viewPaths.auth.signIn}` })
        } else {
          navigate({ to: redirectTo })
        }
      }
    }
  )

  const signInMutating = useIsMutating({
    mutationKey: authMutationKeys.signIn.all
  })
  const signUpMutating = useIsMutating({
    mutationKey: authMutationKeys.signUp.all
  })
  const isPending = signInMutating + signUpMutating > 0

  const Captcha = plugins.find(
    (plugin) => plugin.captchaComponent
  )?.captchaComponent

  const [isPasswordVisible, setIsPasswordVisible] = useState(false)
  const [isConfirmPasswordVisible, setIsConfirmPasswordVisible] =
    useState(false)

  const [fieldErrors, setFieldErrors] = useState<{
    name?: string
    email?: string
    password?: string
    confirmPassword?: string
  }>({})

  const handleSubmit = async (e: SyntheticEvent<HTMLFormElement>) => {
    e.preventDefault()

    const formData = new FormData(e.currentTarget)
    // `emailAndPassword.name === false` hides the name field and submits "".
    const name = (formData.get("name") as string | null) ?? ""
    const email = formData.get("email") as string

    if (emailAndPassword?.confirmPassword && password !== confirmPassword) {
      toast.error(localization.auth.passwordsDoNotMatch)
      setPassword("")
      setConfirmPassword("")
      return
    }

    const additionalFieldValues: Record<string, unknown> = {}

    for (const field of additionalFields ?? []) {
      if (!field.signUp || field.readOnly) continue
      const value = parseAdditionalFieldValue(
        field,
        formData.get(field.name) as string | null
      )

      if (field.validate) {
        try {
          await field.validate(value)
        } catch (error) {
          toast.error(error instanceof Error ? error.message : String(error))
          return
        }
      }

      if (value !== undefined) {
        additionalFieldValues[field.name] = value
      }
    }

    signUpEmail({
      name,
      email,
      password,
      ...additionalFieldValues,
      fetchOptions
    })
  }

  const showSeparator =
    emailAndPassword?.enabled && socialProviders && socialProviders.length > 0

  return (
    <Card className={cn("w-full max-w-sm", className)}>
      <CardHeader>
        <CardTitle className="text-xl font-semibold">
          {localization.auth.signUp}
        </CardTitle>
      </CardHeader>

      <CardContent>
        <div className="flex flex-col gap-6">
          {socialPosition === "top" && (
            <>
              {socialProviders && socialProviders.length > 0 && (
                <ProviderButtons socialLayout={socialLayout} />
              )}

              {showSeparator && (
                <FieldSeparator className="*:data-[slot=field-separator-content]:bg-card text-xs flex items-center">
                  {localization.auth.or}
                </FieldSeparator>
              )}
            </>
          )}

          {emailAndPassword?.enabled && (
            <form onSubmit={handleSubmit}>
              <FieldGroup>
                {emailAndPassword.name !== false && (
                  <Field data-invalid={!!fieldErrors.name}>
                    <Label htmlFor="name">{localization.auth.name}</Label>

                    <Input
                      id="name"
                      name="name"
                      type="text"
                      autoComplete="name"
                      placeholder={localization.auth.namePlaceholder}
                      required
                      disabled={isPending}
                      onChange={() => {
                        setFieldErrors((prev) => ({
                          ...prev,
                          name: undefined
                        }))
                      }}
                      onInvalid={(e) => {
                        e.preventDefault()

                        setFieldErrors((prev) => ({
                          ...prev,
                          name: localization.auth.fieldRequired
                        }))
                      }}
                      aria-invalid={!!fieldErrors.name}
                    />

                    <FieldError>{fieldErrors.name}</FieldError>
                  </Field>
                )}

                <Field data-invalid={!!fieldErrors.email}>
                  <Label htmlFor="email">{localization.auth.email}</Label>

                  <Input
                    id="email"
                    name="email"
                    type="email"
                    autoComplete="email"
                    placeholder={localization.auth.emailPlaceholder}
                    required
                    disabled={isPending}
                    onChange={() => {
                      setFieldErrors((prev) => ({
                        ...prev,
                        email: undefined
                      }))
                    }}
                    onInvalid={(e) => {
                      e.preventDefault()
                      const el = e.target as HTMLInputElement
                      const msg = el.validity.valueMissing
                        ? localization.auth.fieldRequired
                        : localization.auth.invalidEmail

                      setFieldErrors((prev) => ({
                        ...prev,
                        email: msg
                      }))
                    }}
                    aria-invalid={!!fieldErrors.email}
                  />

                  <FieldError>{fieldErrors.email}</FieldError>
                </Field>

                {additionalFields?.map(
                  (field) =>
                    field.signUp === "above" && (
                      <AdditionalField
                        key={field.name}
                        name={field.name}
                        field={field}
                        isPending={isPending}
                      />
                    )
                )}

                <Field data-invalid={!!fieldErrors.password}>
                  <Label htmlFor="password">{localization.auth.password}</Label>

                  <InputGroup>
                    <InputGroupInput
                      id="password"
                      name="password"
                      type={isPasswordVisible ? "text" : "password"}
                      autoComplete="new-password"
                      value={password}
                      onChange={(e) => {
                        setPassword(e.target.value)
                        setFieldErrors((prev) => ({
                          ...prev,
                          password: undefined
                        }))
                      }}
                      placeholder={localization.auth.passwordPlaceholder}
                      required
                      minLength={emailAndPassword?.minPasswordLength}
                      maxLength={emailAndPassword?.maxPasswordLength}
                      disabled={isPending}
                      onInvalid={(e) => {
                        e.preventDefault()
                        const el = e.target as HTMLInputElement
                        const min = emailAndPassword?.minPasswordLength
                        const max = emailAndPassword?.maxPasswordLength
                        const msg = el.validity.valueMissing
                          ? localization.auth.fieldRequired
                          : el.validity.tooShort
                            ? localization.auth.tooShort.replace(
                                "{{min}}",
                                String(min)
                              )
                            : localization.auth.tooLong.replace(
                                "{{max}}",
                                String(max)
                              )

                        setFieldErrors((prev) => ({
                          ...prev,
                          password: msg
                        }))
                      }}
                      aria-invalid={!!fieldErrors.password}
                    />

                    <InputGroupAddon align="inline-end">
                      <InputGroupButton
                        aria-label={
                          isPasswordVisible
                            ? localization.auth.hidePassword
                            : localization.auth.showPassword
                        }
                        title={
                          isPasswordVisible
                            ? localization.auth.hidePassword
                            : localization.auth.showPassword
                        }
                        onClick={() => {
                          setIsPasswordVisible(!isPasswordVisible)
                        }}
                      >
                        {isPasswordVisible ? <EyeOff /> : <Eye />}
                      </InputGroupButton>
                    </InputGroupAddon>
                  </InputGroup>

                  <FieldError>{fieldErrors.password}</FieldError>
                </Field>

                {emailAndPassword?.confirmPassword && (
                  <Field data-invalid={!!fieldErrors.confirmPassword}>
                    <Label htmlFor="confirmPassword">
                      {localization.auth.confirmPassword}
                    </Label>

                    <InputGroup>
                      <InputGroupInput
                        id="confirmPassword"
                        name="confirmPassword"
                        type={isConfirmPasswordVisible ? "text" : "password"}
                        autoComplete="new-password"
                        value={confirmPassword}
                        onChange={(e) => {
                          setConfirmPassword(e.target.value)

                          setFieldErrors((prev) => ({
                            ...prev,
                            confirmPassword: undefined
                          }))
                        }}
                        placeholder={
                          localization.auth.confirmPasswordPlaceholder
                        }
                        required
                        minLength={emailAndPassword?.minPasswordLength}
                        maxLength={emailAndPassword?.maxPasswordLength}
                        disabled={isPending}
                        onInvalid={(e) => {
                          e.preventDefault()
                          const el = e.target as HTMLInputElement
                          const min = emailAndPassword?.minPasswordLength
                          const max = emailAndPassword?.maxPasswordLength
                          const msg = el.validity.valueMissing
                            ? localization.auth.fieldRequired
                            : el.validity.tooShort
                              ? localization.auth.tooShort.replace(
                                  "{{min}}",
                                  String(min)
                                )
                              : localization.auth.tooLong.replace(
                                  "{{max}}",
                                  String(max)
                                )

                          setFieldErrors((prev) => ({
                            ...prev,
                            confirmPassword: msg
                          }))
                        }}
                        aria-invalid={!!fieldErrors.confirmPassword}
                      />

                      <InputGroupAddon align="inline-end">
                        <InputGroupButton
                          aria-label={
                            isConfirmPasswordVisible
                              ? localization.auth.hidePassword
                              : localization.auth.showPassword
                          }
                          title={
                            isConfirmPasswordVisible
                              ? localization.auth.hidePassword
                              : localization.auth.showPassword
                          }
                          onClick={() =>
                            setIsConfirmPasswordVisible(
                              !isConfirmPasswordVisible
                            )
                          }
                        >
                          {isConfirmPasswordVisible ? <EyeOff /> : <Eye />}
                        </InputGroupButton>
                      </InputGroupAddon>
                    </InputGroup>

                    <FieldError>{fieldErrors.confirmPassword}</FieldError>
                  </Field>
                )}

                {additionalFields?.map(
                  (field) =>
                    field.signUp &&
                    field.signUp !== "above" && (
                      <AdditionalField
                        key={field.name}
                        name={field.name}
                        field={field}
                        isPending={isPending}
                      />
                    )
                )}

                {Captcha && (
                  <div className="flex justify-center">{Captcha}</div>
                )}

                <div className="flex flex-col gap-3">
                  <Button type="submit" disabled={isPending}>
                    {signUpEmailPending && <Spinner />}

                    {localization.auth.signUp}
                  </Button>

                  {plugins.flatMap((plugin) =>
                    (plugin.authButtons ?? []).map((AuthButton, index) => (
                      <AuthButton
                        key={`${plugin.id}-${index.toString()}`}
                        view="signUp"
                      />
                    ))
                  )}
                </div>
              </FieldGroup>
            </form>
          )}

          {socialPosition === "bottom" && (
            <>
              {showSeparator && (
                <FieldSeparator className="*:data-[slot=field-separator-content]:bg-card text-xs flex items-center">
                  {localization.auth.or}
                </FieldSeparator>
              )}

              {socialProviders && socialProviders.length > 0 && (
                <ProviderButtons socialLayout={socialLayout} />
              )}
            </>
          )}
        </div>

        {emailAndPassword?.enabled && (
          <div className="flex flex-col gap-3 items-center w-full mt-4">
            <FieldDescription className="text-center">
              {localization.auth.alreadyHaveAnAccount}{" "}
              <Link
                href={`${basePaths.auth}/${viewPaths.auth.signIn}`}
                className="underline underline-offset-4"
              >
                {localization.auth.signIn}
              </Link>
            </FieldDescription>
          </div>
        )}
      </CardContent>
    </Card>
  )
}

// examples/start-solid-zaidan-example/src/components/auth/sign-up.tsx
import { authQueryKeys, parseAdditionalFieldValue } from "@better-auth-ui/core"
import {
  signUpEmailOptions,
  useAuth,
  useFetchOptions
} from "@better-auth-ui/solid"
import type { AuthPlugin } from "@better-auth-ui/solid/plugins"
import { createMutation, useQueryClient } from "@tanstack/solid-query"
import { Link } from "@tanstack/solid-router"
import { Eye, EyeOff } from "lucide-solid"
import { createSignal, For, Show } from "solid-js"
import { toast } from "solid-sonner"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { cn } from "@/lib/utils"
import { AdditionalField } from "./additional-field"
import { ProviderButtons, type SocialLayout } from "./provider-buttons"

export type SignUpProps = {
  class?: string
  socialLayout?: SocialLayout
  socialPosition?: "top" | "bottom"
}

export function SignUp(props: SignUpProps) {
  const auth = useAuth()
  const { fetchOptions, resetFetchOptions } = useFetchOptions()
  const queryClient = useQueryClient()
  const [email, setEmail] = createSignal("")
  const [emailError, setEmailError] = createSignal<string>()
  const [name, setName] = createSignal("")
  const [nameError, setNameError] = createSignal<string>()
  const [password, setPassword] = createSignal("")
  const [passwordError, setPasswordError] = createSignal<string>()
  const [confirmPassword, setConfirmPassword] = createSignal("")
  const [confirmPasswordError, setConfirmPasswordError] = createSignal<string>()
  const [isPasswordVisible, setIsPasswordVisible] = createSignal(false)
  const [isConfirmPasswordVisible, setIsConfirmPasswordVisible] =
    createSignal(false)
  const signUp = createMutation(() => ({
    ...signUpEmailOptions(auth.authClient),
    onError: () => {
      resetFetchOptions()
    },
    onSuccess: () => {
      if (auth.emailAndPassword.requireEmailVerification) {
        auth.navigate({
          to: `${auth.basePaths.auth}/${auth.viewPaths.auth.signIn}`
        })
        return
      }

      queryClient.invalidateQueries({ queryKey: authQueryKeys.session })
      auth.navigate({ to: auth.redirectTo })
    }
  }))
  const captchaComponent = () =>
    (auth.plugins as AuthPlugin[]).find((plugin) => plugin.captchaComponent)
      ?.captchaComponent
  const socialPosition = () => props.socialPosition ?? "bottom"
  const showSeparator = () =>
    Boolean(auth.emailAndPassword?.enabled && auth.socialProviders?.length)

  const signUpFieldsAbove = () =>
    auth.additionalFields?.filter((field) => field.signUp === "above") ?? []
  const signUpFieldsBelow = () =>
    auth.additionalFields?.filter(
      (field) => field.signUp && field.signUp !== "above"
    ) ?? []

  const submitSignUp = async (event: SubmitEvent) => {
    event.preventDefault()

    setConfirmPasswordError(undefined)

    if (
      auth.emailAndPassword.confirmPassword &&
      password() !== confirmPassword()
    ) {
      setConfirmPasswordError(auth.localization.auth.passwordsDoNotMatch)
      return
    }

    const formData = new FormData(event.currentTarget as HTMLFormElement)
    const additionalFieldValues: Record<string, unknown> = {}

    for (const field of auth.additionalFields ?? []) {
      if (!field.signUp || field.readOnly) continue

      const value = parseAdditionalFieldValue(
        field,
        formData.get(field.name) as string | null
      )

      if (field.validate) {
        try {
          await field.validate(value)
        } catch (error) {
          toast.error(error instanceof Error ? error.message : String(error))
          return
        }
      }

      if (value !== undefined) {
        additionalFieldValues[field.name] = value
      }
    }

    signUp.mutate({
      email: email(),
      fetchOptions: fetchOptions(),
      name: name(),
      password: password(),
      ...additionalFieldValues
    } as Parameters<typeof signUp.mutate>[0])
  }

  return (
    <Card class={cn("w-full max-w-sm", props.class)}>
      <CardHeader>
        <CardTitle class="text-xl font-semibold">
          {auth.localization.auth.signUp}
        </CardTitle>
      </CardHeader>

      <CardContent>
        <Show when={socialPosition() === "top"}>
          <Show when={auth.socialProviders?.length}>
            <ProviderButtons socialLayout={props.socialLayout} view="signUp" />
          </Show>
          <Show when={showSeparator()}>
            <div class="my-4 text-center text-muted-foreground text-xs">
              {auth.localization.auth.or}
            </div>
          </Show>
        </Show>

        <form aria-label="Sign up" onSubmit={submitSignUp}>
          <div class="flex flex-col gap-6">
            <Show when={auth.emailAndPassword.name}>
              <div class="grid gap-3">
                <Label for="sign-up-name">{auth.localization.auth.name}</Label>
                <Input
                  aria-invalid={Boolean(nameError())}
                  autocomplete="name"
                  id="sign-up-name"
                  name="name"
                  onInput={(event) => {
                    setName(event.currentTarget.value)
                    setNameError(undefined)
                  }}
                  onInvalid={(event) => {
                    event.preventDefault()
                    setNameError(event.currentTarget.validationMessage)
                  }}
                  placeholder={auth.localization.auth.namePlaceholder}
                  required={auth.emailAndPassword.name}
                  type="text"
                  value={name()}
                />

                <Show when={nameError()}>
                  {(message) => (
                    <p class="text-sm text-destructive" role="alert">
                      {message()}
                    </p>
                  )}
                </Show>
              </div>
            </Show>
            <div class="grid gap-3">
              <Label for="sign-up-email">{auth.localization.auth.email}</Label>
              <Input
                aria-invalid={Boolean(emailError())}
                autocomplete="email"
                id="sign-up-email"
                name="email"
                onInput={(event) => {
                  setEmail(event.currentTarget.value)
                  setEmailError(undefined)
                }}
                onInvalid={(event) => {
                  event.preventDefault()
                  setEmailError(event.currentTarget.validationMessage)
                }}
                placeholder={auth.localization.auth.emailPlaceholder}
                required
                type="email"
                value={email()}
              />

              <Show when={emailError()}>
                {(message) => (
                  <p class="text-sm text-destructive" role="alert">
                    {message()}
                  </p>
                )}
              </Show>
            </div>
            <For each={signUpFieldsAbove()}>
              {(field) => (
                <AdditionalField
                  field={field}
                  isPending={signUp.isPending}
                  name={field.name}
                />
              )}
            </For>
            <div class="grid gap-3">
              <Label for="sign-up-password">
                {auth.localization.auth.password}
              </Label>
              <div class="relative">
                <Input
                  aria-invalid={Boolean(passwordError())}
                  autocomplete="new-password"
                  class="pr-12"
                  id="sign-up-password"
                  maxLength={auth.emailAndPassword.maxPasswordLength}
                  minLength={auth.emailAndPassword.minPasswordLength}
                  name="password"
                  onInput={(event) => {
                    setPassword(event.currentTarget.value)
                    setPasswordError(undefined)
                    setConfirmPasswordError(undefined)
                  }}
                  onInvalid={(event) => {
                    event.preventDefault()
                    setPasswordError(event.currentTarget.validationMessage)
                  }}
                  placeholder={auth.localization.auth.passwordPlaceholder}
                  required
                  type={isPasswordVisible() ? "text" : "password"}
                  value={password()}
                />

                <Button
                  aria-label={
                    isPasswordVisible()
                      ? auth.localization.auth.hidePassword
                      : auth.localization.auth.showPassword
                  }
                  class="absolute right-1 top-1/2 -translate-y-1/2"
                  onClick={() => setIsPasswordVisible((visible) => !visible)}
                  size="icon-sm"
                  title={
                    isPasswordVisible()
                      ? auth.localization.auth.hidePassword
                      : auth.localization.auth.showPassword
                  }
                  type="button"
                  variant="ghost"
                >
                  {isPasswordVisible() ? (
                    <EyeOff aria-hidden class="size-4" />
                  ) : (
                    <Eye aria-hidden class="size-4" />
                  )}
                </Button>
              </div>

              <Show when={passwordError()}>
                {(message) => (
                  <p class="text-sm text-destructive" role="alert">
                    {message()}
                  </p>
                )}
              </Show>
            </div>
            <Show when={auth.emailAndPassword.confirmPassword}>
              <div class="grid gap-3">
                <Label for="sign-up-confirm-password">
                  {auth.localization.auth.confirmPassword}
                </Label>
                <div class="relative">
                  <Input
                    aria-invalid={Boolean(confirmPasswordError())}
                    autocomplete="new-password"
                    class="pr-12"
                    id="sign-up-confirm-password"
                    maxLength={auth.emailAndPassword.maxPasswordLength}
                    minLength={auth.emailAndPassword.minPasswordLength}
                    name="confirmPassword"
                    onInput={(event) => {
                      setConfirmPassword(event.currentTarget.value)
                      setConfirmPasswordError(undefined)
                    }}
                    onInvalid={(event) => {
                      event.preventDefault()
                      setConfirmPasswordError(
                        event.currentTarget.validationMessage
                      )
                    }}
                    placeholder={
                      auth.localization.auth.confirmPasswordPlaceholder
                    }
                    required
                    type={isConfirmPasswordVisible() ? "text" : "password"}
                    value={confirmPassword()}
                  />

                  <Button
                    aria-label={
                      isConfirmPasswordVisible()
                        ? auth.localization.auth.hidePassword
                        : auth.localization.auth.showPassword
                    }
                    class="absolute right-1 top-1/2 -translate-y-1/2"
                    onClick={() =>
                      setIsConfirmPasswordVisible((visible) => !visible)
                    }
                    size="icon-sm"
                    title={
                      isConfirmPasswordVisible()
                        ? auth.localization.auth.hidePassword
                        : auth.localization.auth.showPassword
                    }
                    type="button"
                    variant="ghost"
                  >
                    {isConfirmPasswordVisible() ? (
                      <EyeOff aria-hidden class="size-4" />
                    ) : (
                      <Eye aria-hidden class="size-4" />
                    )}
                  </Button>
                </div>

                <Show when={confirmPasswordError()}>
                  {(message) => (
                    <p class="text-sm text-destructive" role="alert">
                      {message()}
                    </p>
                  )}
                </Show>
              </div>
            </Show>
            <For each={signUpFieldsBelow()}>
              {(field) => (
                <AdditionalField
                  field={field}
                  isPending={signUp.isPending}
                  name={field.name}
                />
              )}
            </For>
            <Show when={captchaComponent()} keyed>
              {(Captcha) => <Captcha />}
            </Show>
            <Button disabled={signUp.isPending} type="submit">
              {signUp.isPending
                ? `${auth.localization.auth.signUp}…`
                : auth.localization.auth.signUp}
            </Button>
            <Show when={signUp.isSuccess}>
              <p role="status">
                Account created. Check your email if verification is required.
              </p>
            </Show>
            <Show when={signUp.isError}>
              <p role="alert">Unable to create an account. Try again.</p>
            </Show>
          </div>
        </form>

        <Show
          when={socialPosition() === "bottom" && auth.socialProviders?.length}
        >
          <div class="my-4 text-center text-muted-foreground text-xs">
            {auth.localization.auth.or}
          </div>
          <ProviderButtons socialLayout={props.socialLayout} view="signUp" />
        </Show>

        <div class="mt-4 flex w-full flex-col items-center gap-3">
          <p class="text-center text-sm text-muted-foreground">
            {auth.localization.auth.alreadyHaveAnAccount}{" "}
            <Link
              class="underline underline-offset-4"
              params={{ path: auth.viewPaths.auth.signIn }}
              to="/auth/$path"
            >
              {auth.localization.auth.signIn}
            </Link>
          </p>
        </div>
      </CardContent>
    </Card>
  )
}
