// apps/heroui-dev/src/components/providers.tsx
import { AuthProvider } from "@better-auth-ui/heroui"
import {
  apiKeyPlugin,
  deleteUserPlugin,
  magicLinkPlugin,
  multiSessionPlugin,
  organizationPlugin,
  passkeyPlugin,
  themePlugin,
  usernamePlugin
} from "@better-auth-ui/heroui/plugins"
import { Toast } from "@heroui/react"
import { useNavigate } from "@tanstack/react-router"
import { ThemeProvider, useTheme } from "next-themes"
import type { ReactNode } from "react"
import { authClient } from "@/lib/auth-client"

export function Providers({ children }: { children: ReactNode }) {
  const navigate = useNavigate()

  return (
    <ThemeProvider defaultTheme="system" enableSystem disableTransitionOnChange>
      <AuthProvider
        authClient={authClient}
        redirectTo="/settings/account"
        socialProviders={["github"]}
        navigate={navigate}
        plugins={[
          usernamePlugin(),
          magicLinkPlugin(),
          passkeyPlugin(),
          apiKeyPlugin(),
          themePlugin({ useTheme }),
          multiSessionPlugin(),
          deleteUserPlugin(),
          organizationPlugin()
        ]}
      >
        {children}

        <Toast.Provider />
      </AuthProvider>
    </ThemeProvider>
  )
}

// examples/start-solid-zaidan-example/src/components/providers.tsx
import {
  apiKeyPlugin,
  deleteUserPlugin,
  multiSessionPlugin,
  usernamePlugin
} from "@better-auth-ui/core/plugins"
import type { QueryClient } from "@tanstack/solid-query"
import { useNavigate } from "@tanstack/solid-router"
import type { JSX } from "solid-js"
import { onCleanup, onMount } from "solid-js"
import { organizationPlugin } from "@/lib/auth/organization-plugin"
import { passkeyPlugin } from "@/lib/auth/passkey-plugin"
import { authClient } from "@/lib/auth-client"
import { syncDocumentThemePreference } from "@/lib/theme"

import { AuthProvider } from "./auth/auth-provider"
import { Toaster } from "./ui/sonner"

export type ProvidersProps = {
  children?: JSX.Element | (() => JSX.Element)
  queryClient?: QueryClient
}

const resolveProviderChildren = (children: ProvidersProps["children"]) =>
  typeof children === "function" ? children() : children

export function Providers(props: ProvidersProps) {
  const navigate = useNavigate()

  onMount(() => {
    const cleanup = syncDocumentThemePreference()

    onCleanup(cleanup)
  })

  return (
    <AuthProvider
      authClient={authClient}
      redirectTo="/settings/account"
      navigate={navigate}
      queryClient={props.queryClient}
      socialProviders={["github"]}
      plugins={[
        multiSessionPlugin(),
        apiKeyPlugin(),
        passkeyPlugin(),
        deleteUserPlugin(),
        usernamePlugin(),
        organizationPlugin()
      ]}
    >
      {() => (
        <>
          {resolveProviderChildren(props.children)}
          <Toaster />
        </>
      )}
    </AuthProvider>
  )
}
