// packages/heroui/src/components/auth/organization/organization-invitation-row.tsx
import {
  type OrganizationAuthClient,
  useAuth,
  useAuthPlugin,
  useCancelInvitation,
  useHasPermission
} from "@better-auth-ui/react"
import { Xmark } from "@gravity-ui/icons"
import { Button, Chip, Spinner, Table } from "@heroui/react"

import type { Invitation } from "better-auth/client"

import { organizationPlugin } from "../../../lib/auth/organization-plugin"
import { OrganizationInvitationRowSkeleton } from "./organization-invitation-row-skeleton"

export type OrganizationInvitationTableRowProps = {
  invitation: Invitation
}

export function OrganizationInvitationTableRow({
  invitation
}: OrganizationInvitationTableRowProps) {
  const { authClient } = useAuth()
  const { localization: organizationLocalization, roles } =
    useAuthPlugin(organizationPlugin)

  const {
    data: cancelInvitationPermission,
    isPending: cancelPermissionPending
  } = useHasPermission(authClient as OrganizationAuthClient, {
    permissions: { invitation: ["cancel"] }
  })

  const { mutate: cancelInvitation, isPending: cancelPending } =
    useCancelInvitation(authClient as OrganizationAuthClient)

  const roleLabel = roles?.[invitation.role] ?? invitation.role

  const statusLabel =
    organizationLocalization[invitation.status] ?? invitation.status

  const statusColor =
    invitation.status === "pending"
      ? "warning"
      : invitation.status === "accepted"
        ? "success"
        : invitation.status === "rejected"
          ? "danger"
          : "default"

  if (cancelPermissionPending) {
    return <OrganizationInvitationRowSkeleton />
  }

  return (
    <Table.Row>
      <Table.Cell className="font-medium text-sm">
        {invitation.email}
      </Table.Cell>

      <Table.Cell className="text-muted text-xs tabular-nums whitespace-nowrap">
        {new Date(invitation.createdAt).toLocaleString(undefined, {
          dateStyle: "short",
          timeStyle: "short"
        })}
      </Table.Cell>

      <Table.Cell className="text-sm">{roleLabel}</Table.Cell>

      <Table.Cell className="text-sm">
        <Chip color={statusColor} size="sm" variant="soft">
          {statusLabel}
        </Chip>
      </Table.Cell>

      <Table.Cell className="text-end">
        {cancelInvitationPermission?.success &&
          invitation.status === "pending" && (
            <Button
              isIconOnly
              size="sm"
              variant="danger-soft"
              isPending={cancelPending}
              onPress={() => cancelInvitation({ invitationId: invitation.id })}
              aria-label={organizationLocalization.cancelInvitation}
            >
              {cancelPending ? (
                <Spinner color="current" size="sm" />
              ) : (
                <Xmark />
              )}
            </Button>
          )}
      </Table.Cell>
    </Table.Row>
  )
}

// examples/start-solid-zaidan-example/src/components/auth/organization/organization-invitation-row.tsx
import type { OrganizationAuthClient } from "@better-auth-ui/solid"
import {
  useAuth,
  useCancelInvitation,
  useHasPermission
} from "@better-auth-ui/solid"
import { X } from "lucide-solid"
import { Show } from "solid-js"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { Spinner } from "@/components/ui/spinner"
import { TableCell, TableRow } from "@/components/ui/table"

type OrganizationInvitation = {
  createdAt?: Date | string | null
  email?: string | null
  id: string
  role?: string | null
  status?: string | null
}

type RoleMap = Record<string, string>

const statusBadgeClasses: Record<string, string> = {
  accepted: "z-badge-status-accepted",
  canceled: "z-badge-status-canceled",
  pending: "z-badge-status-pending",
  rejected: "z-badge-status-rejected"
}

export type OrganizationInvitationRowProps = {
  invitation: OrganizationInvitation
  roles: RoleMap
}

function formatRole(role?: string | null) {
  if (!role) return "Member"

  return role.charAt(0).toUpperCase() + role.slice(1)
}

function formatStatus(status?: string | null) {
  if (!status) return "Pending"

  return status.charAt(0).toUpperCase() + status.slice(1)
}

function formatInvitationDate(createdAt?: Date | string | null) {
  if (!createdAt) return "—"

  const date = createdAt instanceof Date ? createdAt : new Date(createdAt)

  if (Number.isNaN(date.getTime())) return "—"

  return date.toLocaleString(undefined, {
    dateStyle: "short",
    timeStyle: "short"
  })
}

export function OrganizationInvitationRow(
  props: OrganizationInvitationRowProps
) {
  const auth = useAuth()
  const permission = useHasPermission(
    auth.authClient as OrganizationAuthClient,
    {
      permissions: { invitation: ["cancel"] }
    }
  )
  const cancelInvitation = useCancelInvitation(
    auth.authClient as OrganizationAuthClient
  )
  const roleLabel = () =>
    props.roles[props.invitation.role ?? ""] ??
    formatRole(props.invitation.role)
  const statusBadgeClass = () =>
    statusBadgeClasses[props.invitation.status ?? "pending"] ??
    statusBadgeClasses.pending

  return (
    <TableRow>
      <TableCell class="font-medium">
        {props.invitation.email ?? "Invitation"}
      </TableCell>
      <TableCell class="whitespace-nowrap text-muted-foreground text-xs tabular-nums">
        {formatInvitationDate(props.invitation.createdAt)}
      </TableCell>
      <TableCell class="text-sm">{roleLabel()}</TableCell>
      <TableCell>
        <Badge class={statusBadgeClass()} variant="secondary">
          {formatStatus(props.invitation.status)}
        </Badge>
      </TableCell>
      <TableCell class="text-end">
        <Show
          when={
            permission.data?.success && props.invitation.status === "pending"
          }
        >
          <Button
            aria-label="Cancel invitation"
            disabled={cancelInvitation.isPending}
            onClick={() =>
              cancelInvitation.mutate({
                invitationId: props.invitation.id
              })
            }
            size="icon-sm"
            type="button"
            variant="outline"
          >
            <Show
              when={cancelInvitation.isPending}
              fallback={<X class="size-4 text-destructive" />}
            >
              <Spinner class="text-destructive" />
            </Show>
          </Button>
        </Show>
      </TableCell>
    </TableRow>
  )
}
