// examples/next-shadcn-example/src/components/auth/organization/organization-invitations.tsx
"use client"

import type { OrganizationLocalization } from "@better-auth-ui/core/plugins"
import {
  type OrganizationAuthClient,
  useAuth,
  useAuthPlugin,
  useHasPermission,
  useListOrganizationInvitations
} from "@better-auth-ui/react"
import { ChevronUp, Filter, Search, X } from "lucide-react"
import { type ComponentProps, type ReactNode, useMemo, useState } from "react"

import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { Card } from "@/components/ui/card"
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuRadioGroup,
  DropdownMenuRadioItem,
  DropdownMenuTrigger
} from "@/components/ui/dropdown-menu"
import {
  InputGroup,
  InputGroupAddon,
  InputGroupInput
} from "@/components/ui/input-group"
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow
} from "@/components/ui/table"
import { organizationPlugin } from "@/lib/auth/organization-plugin"
import { cn } from "@/lib/utils"
import { InviteMemberDialog } from "./invite-member-dialog"
import { OrganizationInvitationRow } from "./organization-invitation-row"
import { OrganizationInvitationRowSkeleton } from "./organization-invitation-row-skeleton"
import { OrganizationInvitationsEmpty } from "./organization-invitations-empty"

type SortDirection = "ascending" | "descending"

type SortDescriptor = {
  column: string
  direction: SortDirection
}

/** Props for the `OrganizationInvitations` component. */
export type OrganizationInvitationsProps = {
  className?: string
}

/**
 * Organization invitations table with invite control and per-row actions.
 */
export function OrganizationInvitations({
  className,
  ...props
}: OrganizationInvitationsProps & ComponentProps<"div">) {
  const { authClient, localization } = useAuth()
  const { localization: organizationLocalization, roles } =
    useAuthPlugin(organizationPlugin)

  const { data: invitations, isPending: invitationsPending } =
    useListOrganizationInvitations(authClient as OrganizationAuthClient)

  const { isPending: invitationPermissionPending } = useHasPermission(
    authClient as OrganizationAuthClient,
    {
      permissions: { invitation: ["cancel"] }
    }
  )

  const isPending = invitationsPending || invitationPermissionPending

  const [sortDescriptor, setSortDescriptor] = useState<SortDescriptor>()
  const [roleFilter, setRoleFilter] = useState("all")
  const [statusFilter, setStatusFilter] = useState("all")
  const [search, setSearch] = useState("")

  const filteredInvitations = useMemo(() => {
    return invitations?.filter(
      (invitation) =>
        (roleFilter === "all" || invitation.role === roleFilter) &&
        (statusFilter === "all" || invitation.status === statusFilter) &&
        invitation.email.toLowerCase().includes(search.toLowerCase())
    )
  }, [search, invitations, roleFilter, statusFilter])

  const sortedInvitations = useMemo(() => {
    if (!sortDescriptor) return filteredInvitations
    if (!filteredInvitations) return filteredInvitations

    return [...filteredInvitations].sort((a, b) => {
      const col = sortDescriptor.column as keyof typeof a
      let cmp = 0

      if (col === "createdAt") {
        cmp = new Date(a.createdAt).getTime() - new Date(b.createdAt).getTime()
      } else {
        cmp = String(a[col]).localeCompare(String(b[col]))
      }

      if (sortDescriptor.direction === "descending") {
        cmp *= -1
      }

      return cmp
    })
  }, [sortDescriptor, filteredInvitations])

  const [inviteOpen, setInviteOpen] = useState(false)

  function toggleSort(column: string) {
    setSortDescriptor((current) => {
      if (current?.column !== column) {
        return { column, direction: "ascending" }
      }
      if (current.direction === "ascending") {
        return { column, direction: "descending" }
      }
      return undefined
    })
  }

  return (
    <div className={cn("flex flex-col gap-3", className)} {...props}>
      <h3 className="truncate text-sm font-semibold">
        {organizationLocalization.invitations}
      </h3>

      <div className="flex flex-col gap-4">
        <div className="flex items-center gap-3">
          <InputGroup className="min-w-0 sm:w-[220px]">
            <InputGroupInput
              type="search"
              value={search}
              onChange={(e) => setSearch(e.target.value)}
              aria-label={organizationLocalization.search}
              placeholder={organizationLocalization.search}
              disabled={isPending}
            />

            <InputGroupAddon>
              <Search className="text-muted-foreground" />
            </InputGroupAddon>
          </InputGroup>

          <DropdownMenu>
            <DropdownMenuTrigger asChild>
              <Button size="sm" variant="outline" disabled={isPending}>
                <Filter />

                {organizationLocalization.role}
              </Button>
            </DropdownMenuTrigger>

            <DropdownMenuContent align="start">
              <DropdownMenuRadioGroup
                value={roleFilter}
                onValueChange={setRoleFilter}
              >
                <DropdownMenuRadioItem value="all">
                  {organizationLocalization.all}
                </DropdownMenuRadioItem>

                {Object.entries(roles).map(([key, label]) => (
                  <DropdownMenuRadioItem key={key} value={key}>
                    {label}
                  </DropdownMenuRadioItem>
                ))}
              </DropdownMenuRadioGroup>
            </DropdownMenuContent>
          </DropdownMenu>

          <DropdownMenu>
            <DropdownMenuTrigger asChild>
              <Button size="sm" variant="outline" disabled={isPending}>
                <Filter />

                {organizationLocalization.status}
              </Button>
            </DropdownMenuTrigger>

            <DropdownMenuContent align="start">
              <DropdownMenuRadioGroup
                value={statusFilter}
                onValueChange={setStatusFilter}
              >
                <DropdownMenuRadioItem value="all">
                  {organizationLocalization.all}
                </DropdownMenuRadioItem>

                {(["pending", "accepted", "rejected", "canceled"] as const).map(
                  (status) => (
                    <DropdownMenuRadioItem key={status} value={status}>
                      {organizationLocalization[
                        status as keyof OrganizationLocalization
                      ] ?? status}
                    </DropdownMenuRadioItem>
                  )
                )}
              </DropdownMenuRadioGroup>
            </DropdownMenuContent>
          </DropdownMenu>
        </div>

        {(roleFilter !== "all" || statusFilter !== "all") && (
          <div className="flex flex-wrap gap-2">
            {roleFilter !== "all" && (
              <Badge variant="secondary" className="gap-1">
                {organizationLocalization.role}:{" "}
                <span className="capitalize">
                  {roles?.[roleFilter] ?? roleFilter}
                </span>
                <button
                  type="button"
                  aria-label={organizationLocalization.clear}
                  className="inline-flex cursor-pointer items-center text-muted-foreground hover:text-foreground"
                  onClick={() => setRoleFilter("all")}
                >
                  <X className="size-3" />
                </button>
              </Badge>
            )}

            {statusFilter !== "all" && (
              <Badge variant="secondary" className="gap-1">
                {organizationLocalization.status}:{" "}
                {organizationLocalization[
                  statusFilter as keyof OrganizationLocalization
                ] ?? statusFilter}
                <button
                  type="button"
                  aria-label={organizationLocalization.clear}
                  className="inline-flex cursor-pointer items-center text-muted-foreground hover:text-foreground"
                  onClick={() => setStatusFilter("all")}
                >
                  <X className="size-3" />
                </button>
              </Badge>
            )}
          </div>
        )}

        <Card className="p-0">
          <Table aria-label={organizationLocalization.invitations}>
            <TableHeader>
              <TableRow>
                <SortableTableHead
                  sortDirection={
                    sortDescriptor?.column === "email"
                      ? sortDescriptor.direction
                      : undefined
                  }
                  onClick={() => toggleSort("email")}
                >
                  {localization.auth.email}
                </SortableTableHead>

                <SortableTableHead
                  sortDirection={
                    sortDescriptor?.column === "createdAt"
                      ? sortDescriptor.direction
                      : undefined
                  }
                  onClick={() => toggleSort("createdAt")}
                >
                  {organizationLocalization.invitedAt}
                </SortableTableHead>

                <SortableTableHead
                  sortDirection={
                    sortDescriptor?.column === "role"
                      ? sortDescriptor.direction
                      : undefined
                  }
                  onClick={() => toggleSort("role")}
                >
                  {organizationLocalization.role}
                </SortableTableHead>

                <SortableTableHead
                  sortDirection={
                    sortDescriptor?.column === "status"
                      ? sortDescriptor.direction
                      : undefined
                  }
                  onClick={() => toggleSort("status")}
                >
                  {organizationLocalization.status}
                </SortableTableHead>

                <TableHead className="text-end">
                  {organizationLocalization.actions}
                </TableHead>
              </TableRow>
            </TableHeader>

            <TableBody>
              {isPending ? (
                <OrganizationInvitationRowSkeleton />
              ) : !sortedInvitations?.length ? (
                <TableRow>
                  <TableCell colSpan={5}>
                    <OrganizationInvitationsEmpty
                      onInvitePress={() => setInviteOpen(true)}
                    />
                  </TableCell>
                </TableRow>
              ) : (
                sortedInvitations.map((invitation) => (
                  <OrganizationInvitationRow
                    key={invitation.id}
                    invitation={invitation}
                  />
                ))
              )}
            </TableBody>
          </Table>
        </Card>
      </div>

      <InviteMemberDialog open={inviteOpen} onOpenChange={setInviteOpen} />
    </div>
  )
}

function SortableTableHead({
  children,
  sortDirection,
  onClick
}: {
  children: ReactNode
  sortDirection?: SortDirection
  onClick: () => void
}) {
  return (
    <TableHead>
      <button
        type="button"
        onClick={onClick}
        className="flex w-full items-center gap-2 text-left font-medium"
      >
        {children}

        {!!sortDirection && (
          <ChevronUp
            className={cn(
              "size-3 transition-transform duration-100 ease-out",
              sortDirection === "descending" ? "rotate-180" : ""
            )}
          />
        )}
      </button>
    </TableHead>
  )
}

// examples/start-solid-zaidan-example/src/components/auth/organization/organization-invitations.tsx
import type { OrganizationLocalization } from "@better-auth-ui/core/plugins"
import type { OrganizationAuthClient } from "@better-auth-ui/solid"
import { useAuth, useListOrganizationInvitations } from "@better-auth-ui/solid"
import { ChevronUp, Filter, Search, X } from "lucide-solid"
import { createMemo, createSignal, For, type JSX, Show } from "solid-js"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { Card } from "@/components/ui/card"
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuRadioGroup,
  DropdownMenuRadioItem,
  DropdownMenuTrigger
} from "@/components/ui/dropdown-menu"
import {
  InputGroup,
  InputGroupAddon,
  InputGroupInput
} from "@/components/ui/input-group"
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow
} from "@/components/ui/table"
import { organizationPlugin } from "@/lib/auth/organization-plugin"
import { cn } from "@/lib/utils"
import { OrganizationInvitationRow } from "./organization-invitation-row"
import { OrganizationInvitationRowSkeleton } from "./organization-invitation-row-skeleton"
import { OrganizationInvitationsEmpty } from "./organization-invitations-empty"

export type OrganizationInvitationsProps = {
  class?: string
}

type RoleMap = Record<string, string>
type InvitationSort = "none" | "email" | "createdAt" | "role" | "status"
type InvitationSortColumn = Exclude<InvitationSort, "none">
type SortDirection = "ascending" | "descending"

type SortDescriptor = {
  column: InvitationSortColumn
  direction: SortDirection
}

const fallbackLocalization = {
  search: "Search...",
  clear: "Clear",
  all: "All",
  role: "Role",
  status: "Status",
  pending: "Pending",
  accepted: "Accepted",
  rejected: "Rejected",
  canceled: "Canceled",
  member: "Member",
  admin: "Admin",
  owner: "Owner"
} satisfies Pick<
  OrganizationLocalization,
  | "search"
  | "clear"
  | "all"
  | "role"
  | "status"
  | "pending"
  | "accepted"
  | "rejected"
  | "canceled"
  | "member"
  | "admin"
  | "owner"
>

const invitationStatuses = [
  "pending",
  "accepted",
  "rejected",
  "canceled"
] as const

const fallbackRoles: RoleMap = {
  owner: fallbackLocalization.owner,
  admin: fallbackLocalization.admin,
  member: fallbackLocalization.member
}

type OrganizationInvitation = {
  createdAt?: Date | string | null
  email?: string | null
  id: string
  role?: string | null
  status?: string | null
}

function formatStatus(status?: string | null) {
  if (!status) return "Pending"

  return status.charAt(0).toUpperCase() + status.slice(1)
}

function SortableTableHead(props: {
  children: JSX.Element
  onClick: () => void
  sortDirection?: SortDirection
}) {
  return (
    <TableHead aria-sort={props.sortDirection ?? "none"}>
      <button
        class="flex w-full items-center gap-2 text-left font-medium"
        onClick={props.onClick}
        type="button"
      >
        {props.children}
        <Show when={props.sortDirection}>
          <ChevronUp
            class={cn(
              "size-3 transition-transform duration-100 ease-out",
              props.sortDirection === "descending" && "rotate-180"
            )}
          />
        </Show>
      </button>
    </TableHead>
  )
}

export function OrganizationInvitations(props: OrganizationInvitationsProps) {
  const auth = useAuth()
  const [invitationSearch, setInvitationSearch] = createSignal("")
  const [invitationRoleFilter, setInvitationRoleFilter] = createSignal("all")
  const [invitationStatusFilter, setInvitationStatusFilter] =
    createSignal("all")
  const [invitationSort, setInvitationSort] =
    createSignal<InvitationSort>("none")
  const [sortDescriptor, setSortDescriptor] = createSignal<
    SortDescriptor | undefined
  >()
  const invitations = useListOrganizationInvitations(
    auth.authClient as OrganizationAuthClient
  )
  const invitationRows = () =>
    (invitations.data ?? []) as OrganizationInvitation[]
  const organizationPluginConfig = () =>
    auth.plugins.find((plugin) => plugin.id === organizationPlugin.id) as
      | {
          localization?: Pick<
            OrganizationLocalization,
            | "search"
            | "clear"
            | "all"
            | "role"
            | "status"
            | "pending"
            | "accepted"
            | "rejected"
            | "canceled"
          >
          roles?: RoleMap
        }
      | undefined
  const localization = () =>
    organizationPluginConfig()?.localization ?? fallbackLocalization
  const roles = createMemo(
    () => organizationPluginConfig()?.roles ?? fallbackRoles
  )
  const selectedRoleLabel = () =>
    roles()[invitationRoleFilter()] ?? invitationRoleFilter()
  const selectedStatusLabel = () =>
    invitationStatusFilter() === "all"
      ? localization().all
      : invitationStatusLabel(
          invitationStatusFilter() as (typeof invitationStatuses)[number]
        )
  const normalizedInvitationSearch = () =>
    invitationSearch().trim().toLowerCase()
  const filteredInvitationRows = () =>
    invitationRows().filter((invitation) => {
      const roleMatches =
        invitationRoleFilter() === "all" ||
        invitation.role === invitationRoleFilter()
      const statusMatches =
        invitationStatusFilter() === "all" ||
        invitation.status === invitationStatusFilter()
      const search = normalizedInvitationSearch()

      if (!search) return roleMatches && statusMatches

      return (
        roleMatches &&
        statusMatches &&
        (invitation.email?.toLowerCase().includes(search) ?? false)
      )
    })
  const invitationStatusLabel = (status: (typeof invitationStatuses)[number]) =>
    localization()[status] ?? formatStatus(status)
  const invitationDateTime = (invitation: OrganizationInvitation) => {
    if (!invitation.createdAt) return Number.POSITIVE_INFINITY

    const date =
      invitation.createdAt instanceof Date
        ? invitation.createdAt
        : new Date(invitation.createdAt)
    const time = date.getTime()

    return Number.isNaN(time) ? Number.POSITIVE_INFINITY : time
  }
  const sortInvitations = (
    first: OrganizationInvitation,
    second: OrganizationInvitation
  ) => {
    let comparison = 0

    if (invitationSort() === "email") {
      comparison = (first.email ?? "").localeCompare(second.email ?? "")
    }

    if (invitationSort() === "createdAt") {
      comparison = invitationDateTime(first) - invitationDateTime(second)
    }

    if (invitationSort() === "role") {
      const firstRole = roles()[first.role ?? ""] ?? first.role ?? ""
      const secondRole = roles()[second.role ?? ""] ?? second.role ?? ""

      comparison = firstRole.localeCompare(secondRole)
    }

    if (invitationSort() === "status") {
      comparison = formatStatus(first.status).localeCompare(
        formatStatus(second.status)
      )
    }

    return sortDescriptor()?.direction === "descending"
      ? comparison * -1
      : comparison
  }
  const sortedInvitationRows = () =>
    [...filteredInvitationRows()].sort(sortInvitations)
  const toggleSort = (column: InvitationSortColumn) => {
    setInvitationSort(column)
    setSortDescriptor((current) => {
      if (current?.column !== column) {
        return { column, direction: "ascending" }
      }

      return {
        column,
        direction:
          current.direction === "ascending" ? "descending" : "ascending"
      }
    })
  }

  return (
    <div class={cn("flex flex-col gap-3", props.class)}>
      <h3 class="truncate text-sm font-semibold">Invitations</h3>
      <Show
        when={!invitations.isPending}
        fallback={
          <Card class="!p-0">
            <Table>
              <TableBody>
                <OrganizationInvitationRowSkeleton />
                <OrganizationInvitationRowSkeleton />
              </TableBody>
            </Table>
          </Card>
        }
      >
        <Show
          when={invitationRows().length > 0}
          fallback={
            <Card class="!p-0">
              <Table>
                <TableBody>
                  <TableRow>
                    <TableCell colSpan={5}>
                      <OrganizationInvitationsEmpty />
                    </TableCell>
                  </TableRow>
                </TableBody>
              </Table>
            </Card>
          }
        >
          <div class="flex flex-col gap-2 sm:flex-row sm:items-center">
            <InputGroup class="min-w-0 sm:w-[220px]">
              <InputGroupAddon>
                <Search class="size-4 text-muted-foreground" />
              </InputGroupAddon>
              <InputGroupInput
                aria-label={localization().search}
                onInput={(event) =>
                  setInvitationSearch(event.currentTarget.value)
                }
                placeholder={localization().search}
                type="search"
                value={invitationSearch()}
              />
            </InputGroup>
            <DropdownMenu>
              <DropdownMenuTrigger
                as={Button}
                class="shrink-0"
                variant="outline"
              >
                <Filter class="size-4" />
                {localization().role}
              </DropdownMenuTrigger>
              <DropdownMenuContent>
                <DropdownMenuRadioGroup
                  onChange={setInvitationRoleFilter}
                  value={invitationRoleFilter()}
                >
                  <DropdownMenuRadioItem value="all">
                    {localization().all}
                  </DropdownMenuRadioItem>
                  <For each={Object.entries(roles())}>
                    {([role, label]) => (
                      <DropdownMenuRadioItem value={role}>
                        {label}
                      </DropdownMenuRadioItem>
                    )}
                  </For>
                </DropdownMenuRadioGroup>
              </DropdownMenuContent>
            </DropdownMenu>
            <DropdownMenu>
              <DropdownMenuTrigger
                as={Button}
                class="shrink-0"
                variant="outline"
              >
                <Filter class="size-4" />
                {localization().status}
              </DropdownMenuTrigger>
              <DropdownMenuContent>
                <DropdownMenuRadioGroup
                  onChange={setInvitationStatusFilter}
                  value={invitationStatusFilter()}
                >
                  <DropdownMenuRadioItem value="all">
                    {localization().all}
                  </DropdownMenuRadioItem>
                  <For each={invitationStatuses}>
                    {(status) => (
                      <DropdownMenuRadioItem value={status}>
                        {invitationStatusLabel(status)}
                      </DropdownMenuRadioItem>
                    )}
                  </For>
                </DropdownMenuRadioGroup>
              </DropdownMenuContent>
            </DropdownMenu>
          </div>
          <Show
            when={
              invitationRoleFilter() !== "all" ||
              invitationStatusFilter() !== "all"
            }
          >
            <div class="flex flex-wrap gap-2">
              <Show when={invitationRoleFilter() !== "all"}>
                <Badge class="gap-1 pr-1" variant="secondary">
                  {localization().role}: {selectedRoleLabel()}
                  <button
                    aria-label={`${localization().clear} invitation role filter`}
                    class="rounded-sm p-0.5 hover:bg-muted"
                    onClick={() => setInvitationRoleFilter("all")}
                    type="button"
                  >
                    <X class="size-3" />
                  </button>
                </Badge>
              </Show>
              <Show when={invitationStatusFilter() !== "all"}>
                <Badge class="gap-1 pr-1" variant="secondary">
                  {localization().status}: {selectedStatusLabel()}
                  <button
                    aria-label={`${localization().clear} invitation status filter`}
                    class="rounded-sm p-0.5 hover:bg-muted"
                    onClick={() => setInvitationStatusFilter("all")}
                    type="button"
                  >
                    <X class="size-3" />
                  </button>
                </Badge>
              </Show>
            </div>
          </Show>
          <Card class="!p-0">
            <Table aria-label="Invitations">
              <TableHeader>
                <TableRow>
                  <SortableTableHead
                    onClick={() => toggleSort("email")}
                    sortDirection={
                      sortDescriptor()?.column === "email"
                        ? sortDescriptor()?.direction
                        : undefined
                    }
                  >
                    Email
                  </SortableTableHead>
                  <SortableTableHead
                    onClick={() => toggleSort("createdAt")}
                    sortDirection={
                      sortDescriptor()?.column === "createdAt"
                        ? sortDescriptor()?.direction
                        : undefined
                    }
                  >
                    Invited
                  </SortableTableHead>
                  <SortableTableHead
                    onClick={() => toggleSort("role")}
                    sortDirection={
                      sortDescriptor()?.column === "role"
                        ? sortDescriptor()?.direction
                        : undefined
                    }
                  >
                    {localization().role}
                  </SortableTableHead>
                  <SortableTableHead
                    onClick={() => toggleSort("status")}
                    sortDirection={
                      sortDescriptor()?.column === "status"
                        ? sortDescriptor()?.direction
                        : undefined
                    }
                  >
                    {localization().status}
                  </SortableTableHead>
                  <TableHead class="!text-end">Actions</TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                <Show
                  when={filteredInvitationRows().length > 0}
                  fallback={
                    <TableRow>
                      <TableCell
                        class="text-muted-foreground text-sm"
                        colSpan={5}
                      >
                        No invitations match the current filters.
                      </TableCell>
                    </TableRow>
                  }
                >
                  <For each={sortedInvitationRows()}>
                    {(invitation) => (
                      <OrganizationInvitationRow
                        invitation={invitation}
                        roles={roles()}
                      />
                    )}
                  </For>
                </Show>
              </TableBody>
            </Table>
          </Card>
        </Show>
      </Show>
    </div>
  )
}
