// packages/heroui/src/components/auth/organization/organization-invitations.tsx
import type { OrganizationLocalization } from "@better-auth-ui/core/plugins"
import {
  type OrganizationAuthClient,
  useAuth,
  useAuthPlugin,
  useHasPermission,
  useListOrganizationInvitations
} from "@better-auth-ui/react"
import { ChevronUp, Funnel, Xmark } from "@gravity-ui/icons"
import {
  Button,
  Chip,
  cn,
  Dropdown,
  Label,
  SearchField,
  type SortDescriptor,
  Table
} from "@heroui/react"
import { type ComponentProps, type ReactNode, useMemo, useState } from "react"

import { organizationPlugin } from "../../../lib/auth/organization-plugin"
import { InviteMemberDialog } from "./invite-member-dialog"
import { OrganizationInvitationTableRow } from "./organization-invitation-row"
import { OrganizationInvitationRowSkeleton } from "./organization-invitation-row-skeleton"
import { OrganizationInvitationsEmpty } from "./organization-invitations-empty"

/** Props for the {@link OrganizationInvitations} component. */
export type OrganizationInvitationsProps = {
  className?: string
}

/**
 * Organization invitations table with invite control and per-row actions.
 */
export function OrganizationInvitations({
  className,
  ...props
}: OrganizationInvitationsProps & ComponentProps<"div">) {
  const { authClient, localization } = useAuth()
  const { localization: organizationLocalization, roles } =
    useAuthPlugin(organizationPlugin)

  const { data: invitations, isPending: invitationsPending } =
    useListOrganizationInvitations(authClient as OrganizationAuthClient)

  const { isPending: invitationPermissionPending } = useHasPermission(
    authClient as OrganizationAuthClient,
    {
      permissions: { invitation: ["cancel"] }
    }
  )

  const isPending = invitationsPending || invitationPermissionPending

  const [sortDescriptor, setSortDescriptor] = useState<SortDescriptor>()
  const [roleFilter, setRoleFilter] = useState("all")
  const [statusFilter, setStatusFilter] = useState("all")
  const [search, setSearch] = useState("")

  const filteredInvitations = useMemo(() => {
    return invitations?.filter(
      (invitation) =>
        (roleFilter === "all" || invitation.role === roleFilter) &&
        (statusFilter === "all" || invitation.status === statusFilter) &&
        invitation.email.toLowerCase().includes(search.toLowerCase())
    )
  }, [search, invitations, roleFilter, statusFilter])

  const sortedInvitations = useMemo(() => {
    if (!sortDescriptor) return filteredInvitations
    if (!filteredInvitations) return filteredInvitations

    return [...filteredInvitations].sort((a, b) => {
      const col = sortDescriptor.column as keyof typeof a
      let cmp = 0

      const first = String(a[col])
      const second = String(b[col])
      cmp = first.localeCompare(second)

      if (sortDescriptor.direction === "descending") {
        cmp *= -1
      }

      return cmp
    })
  }, [sortDescriptor, filteredInvitations])

  const [inviteOpen, setInviteOpen] = useState(false)

  return (
    <div className={cn("flex flex-col gap-3", className)} {...props}>
      <h3 className="truncate text-sm font-semibold">
        {organizationLocalization.invitations}
      </h3>

      <div className="flex flex-col gap-4">
        <div className="flex items-center gap-3">
          <SearchField
            className="min-w-0"
            aria-label={organizationLocalization.search}
            value={search}
            onChange={setSearch}
            isDisabled={isPending}
          >
            <SearchField.Group>
              <SearchField.SearchIcon />

              <SearchField.Input
                placeholder={organizationLocalization.search}
                className="sm:w-[200px]"
              />

              <SearchField.ClearButton />
            </SearchField.Group>
          </SearchField>

          <Dropdown>
            <Button size="sm" variant="secondary" isDisabled={isPending}>
              <Funnel />

              {organizationLocalization.role}
            </Button>

            <Dropdown.Popover>
              <Dropdown.Menu
                selectionMode="single"
                selectedKeys={new Set([roleFilter])}
                onSelectionChange={(keys) => {
                  const key = [...keys][0] as string | undefined
                  setRoleFilter(key ?? "all")
                }}
              >
                <Dropdown.Item
                  id="all"
                  textValue={organizationLocalization.all}
                >
                  <Label>{organizationLocalization.all}</Label>

                  <Dropdown.ItemIndicator />
                </Dropdown.Item>

                {Object.entries(roles).map(([key, label]) => (
                  <Dropdown.Item key={key} id={key} textValue={label}>
                    <Label>{label}</Label>

                    <Dropdown.ItemIndicator />
                  </Dropdown.Item>
                ))}
              </Dropdown.Menu>
            </Dropdown.Popover>
          </Dropdown>

          <Dropdown>
            <Button size="sm" variant="secondary" isDisabled={isPending}>
              <Funnel />

              {organizationLocalization.status}
            </Button>

            <Dropdown.Popover>
              <Dropdown.Menu
                selectionMode="single"
                selectedKeys={new Set([statusFilter])}
                onSelectionChange={(keys) => {
                  const key = [...keys][0] as string | undefined
                  setStatusFilter(key ?? "all")
                }}
              >
                <Dropdown.Item
                  id="all"
                  textValue={organizationLocalization.all}
                >
                  <Label>{organizationLocalization.all}</Label>

                  <Dropdown.ItemIndicator />
                </Dropdown.Item>

                {["pending", "accepted", "rejected", "canceled"].map(
                  (status) => (
                    <Dropdown.Item
                      key={status}
                      id={status}
                      textValue={
                        organizationLocalization[
                          status as keyof OrganizationLocalization
                        ] ?? status
                      }
                    >
                      <Label>
                        {organizationLocalization[
                          status as keyof OrganizationLocalization
                        ] ?? status}
                      </Label>

                      <Dropdown.ItemIndicator />
                    </Dropdown.Item>
                  )
                )}
              </Dropdown.Menu>
            </Dropdown.Popover>
          </Dropdown>
        </div>

        {(roleFilter !== "all" || statusFilter !== "all") && (
          <div className="flex flex-wrap gap-2">
            {roleFilter !== "all" && (
              <Chip size="sm" variant="secondary" className="w-fit">
                <Chip.Label>
                  {organizationLocalization.role}:{" "}
                  <span className="capitalize">
                    {roles?.[roleFilter] ?? roleFilter}
                  </span>
                </Chip.Label>

                <button
                  type="button"
                  aria-label={organizationLocalization.clear}
                  className="text-muted hover:text-foreground inline-flex cursor-pointer items-center"
                  onClick={() => setRoleFilter("all")}
                >
                  <Xmark className="size-3" />
                </button>
              </Chip>
            )}

            {statusFilter !== "all" && (
              <Chip size="sm" variant="secondary" className="w-fit">
                <Chip.Label>
                  {organizationLocalization.status}:{" "}
                  {organizationLocalization[
                    statusFilter as keyof OrganizationLocalization
                  ] ?? statusFilter}
                </Chip.Label>

                <button
                  type="button"
                  aria-label={organizationLocalization.clear}
                  className="text-muted hover:text-foreground inline-flex cursor-pointer items-center"
                  onClick={() => setStatusFilter("all")}
                >
                  <Xmark className="size-3" />
                </button>
              </Chip>
            )}
          </div>
        )}

        <Table>
          <Table.ScrollContainer>
            <Table.Content
              aria-label={organizationLocalization.invitations}
              sortDescriptor={sortDescriptor}
              onSortChange={(descriptor) => {
                const shouldReset =
                  sortDescriptor?.column === descriptor.column &&
                  descriptor.direction === "ascending"
                setSortDescriptor(shouldReset ? undefined : descriptor)
              }}
            >
              <Table.Header>
                <Table.Column allowsSorting isRowHeader id="email">
                  {({ sortDirection }) => (
                    <SortableColumnHeader sortDirection={sortDirection}>
                      {localization.auth.email}
                    </SortableColumnHeader>
                  )}
                </Table.Column>

                <Table.Column allowsSorting id="createdAt">
                  {({ sortDirection }) => (
                    <SortableColumnHeader sortDirection={sortDirection}>
                      {organizationLocalization.invitedAt}
                    </SortableColumnHeader>
                  )}
                </Table.Column>

                <Table.Column allowsSorting id="role">
                  {({ sortDirection }) => (
                    <SortableColumnHeader sortDirection={sortDirection}>
                      {organizationLocalization.role}
                    </SortableColumnHeader>
                  )}
                </Table.Column>

                <Table.Column allowsSorting id="status">
                  {({ sortDirection }) => (
                    <SortableColumnHeader sortDirection={sortDirection}>
                      {organizationLocalization.status}
                    </SortableColumnHeader>
                  )}
                </Table.Column>

                <Table.Column className="text-end">
                  {organizationLocalization.actions}
                </Table.Column>
              </Table.Header>

              <Table.Body
                renderEmptyState={() => (
                  <OrganizationInvitationsEmpty
                    onInvitePress={() => setInviteOpen(true)}
                  />
                )}
              >
                {isPending ? (
                  <OrganizationInvitationRowSkeleton />
                ) : (
                  sortedInvitations?.map((invitation) => (
                    <OrganizationInvitationTableRow
                      key={invitation.id}
                      invitation={invitation}
                    />
                  ))
                )}
              </Table.Body>
            </Table.Content>
          </Table.ScrollContainer>
        </Table>
      </div>

      <InviteMemberDialog isOpen={inviteOpen} onOpenChange={setInviteOpen} />
    </div>
  )
}

function SortableColumnHeader({
  children,
  sortDirection
}: {
  children: ReactNode
  sortDirection?: "ascending" | "descending"
}) {
  return (
    <span className="flex items-center justify-between">
      {children}

      {!!sortDirection && (
        <ChevronUp
          className={cn(
            "size-3 transform transition-transform duration-100 ease-out",
            sortDirection === "descending" ? "rotate-180" : ""
          )}
        />
      )}
    </span>
  )
}

// examples/start-solid-zaidan-example/src/components/auth/organization/organization-invitations.tsx
import type { OrganizationLocalization } from "@better-auth-ui/core/plugins"
import type { OrganizationAuthClient } from "@better-auth-ui/solid"
import { useAuth, useListOrganizationInvitations } from "@better-auth-ui/solid"
import { ChevronUp, Filter, Search, X } from "lucide-solid"
import { createMemo, createSignal, For, type JSX, Show } from "solid-js"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { Card } from "@/components/ui/card"
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuRadioGroup,
  DropdownMenuRadioItem,
  DropdownMenuTrigger
} from "@/components/ui/dropdown-menu"
import {
  InputGroup,
  InputGroupAddon,
  InputGroupInput
} from "@/components/ui/input-group"
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow
} from "@/components/ui/table"
import { organizationPlugin } from "@/lib/auth/organization-plugin"
import { cn } from "@/lib/utils"
import { OrganizationInvitationRow } from "./organization-invitation-row"
import { OrganizationInvitationRowSkeleton } from "./organization-invitation-row-skeleton"
import { OrganizationInvitationsEmpty } from "./organization-invitations-empty"

export type OrganizationInvitationsProps = {
  class?: string
}

type RoleMap = Record<string, string>
type InvitationSort = "none" | "email" | "createdAt" | "role" | "status"
type InvitationSortColumn = Exclude<InvitationSort, "none">
type SortDirection = "ascending" | "descending"

type SortDescriptor = {
  column: InvitationSortColumn
  direction: SortDirection
}

const fallbackLocalization = {
  search: "Search...",
  clear: "Clear",
  all: "All",
  role: "Role",
  status: "Status",
  pending: "Pending",
  accepted: "Accepted",
  rejected: "Rejected",
  canceled: "Canceled",
  member: "Member",
  admin: "Admin",
  owner: "Owner"
} satisfies Pick<
  OrganizationLocalization,
  | "search"
  | "clear"
  | "all"
  | "role"
  | "status"
  | "pending"
  | "accepted"
  | "rejected"
  | "canceled"
  | "member"
  | "admin"
  | "owner"
>

const invitationStatuses = [
  "pending",
  "accepted",
  "rejected",
  "canceled"
] as const

const fallbackRoles: RoleMap = {
  owner: fallbackLocalization.owner,
  admin: fallbackLocalization.admin,
  member: fallbackLocalization.member
}

type OrganizationInvitation = {
  createdAt?: Date | string | null
  email?: string | null
  id: string
  role?: string | null
  status?: string | null
}

function formatStatus(status?: string | null) {
  if (!status) return "Pending"

  return status.charAt(0).toUpperCase() + status.slice(1)
}

function SortableTableHead(props: {
  children: JSX.Element
  onClick: () => void
  sortDirection?: SortDirection
}) {
  return (
    <TableHead aria-sort={props.sortDirection ?? "none"}>
      <button
        class="flex w-full items-center gap-2 text-left font-medium"
        onClick={props.onClick}
        type="button"
      >
        {props.children}
        <Show when={props.sortDirection}>
          <ChevronUp
            class={cn(
              "size-3 transition-transform duration-100 ease-out",
              props.sortDirection === "descending" && "rotate-180"
            )}
          />
        </Show>
      </button>
    </TableHead>
  )
}

export function OrganizationInvitations(props: OrganizationInvitationsProps) {
  const auth = useAuth()
  const [invitationSearch, setInvitationSearch] = createSignal("")
  const [invitationRoleFilter, setInvitationRoleFilter] = createSignal("all")
  const [invitationStatusFilter, setInvitationStatusFilter] =
    createSignal("all")
  const [invitationSort, setInvitationSort] =
    createSignal<InvitationSort>("none")
  const [sortDescriptor, setSortDescriptor] = createSignal<
    SortDescriptor | undefined
  >()
  const invitations = useListOrganizationInvitations(
    auth.authClient as OrganizationAuthClient
  )
  const invitationRows = () =>
    (invitations.data ?? []) as OrganizationInvitation[]
  const organizationPluginConfig = () =>
    auth.plugins.find((plugin) => plugin.id === organizationPlugin.id) as
      | {
          localization?: Pick<
            OrganizationLocalization,
            | "search"
            | "clear"
            | "all"
            | "role"
            | "status"
            | "pending"
            | "accepted"
            | "rejected"
            | "canceled"
          >
          roles?: RoleMap
        }
      | undefined
  const localization = () =>
    organizationPluginConfig()?.localization ?? fallbackLocalization
  const roles = createMemo(
    () => organizationPluginConfig()?.roles ?? fallbackRoles
  )
  const selectedRoleLabel = () =>
    roles()[invitationRoleFilter()] ?? invitationRoleFilter()
  const selectedStatusLabel = () =>
    invitationStatusFilter() === "all"
      ? localization().all
      : invitationStatusLabel(
          invitationStatusFilter() as (typeof invitationStatuses)[number]
        )
  const normalizedInvitationSearch = () =>
    invitationSearch().trim().toLowerCase()
  const filteredInvitationRows = () =>
    invitationRows().filter((invitation) => {
      const roleMatches =
        invitationRoleFilter() === "all" ||
        invitation.role === invitationRoleFilter()
      const statusMatches =
        invitationStatusFilter() === "all" ||
        invitation.status === invitationStatusFilter()
      const search = normalizedInvitationSearch()

      if (!search) return roleMatches && statusMatches

      return (
        roleMatches &&
        statusMatches &&
        (invitation.email?.toLowerCase().includes(search) ?? false)
      )
    })
  const invitationStatusLabel = (status: (typeof invitationStatuses)[number]) =>
    localization()[status] ?? formatStatus(status)
  const invitationDateTime = (invitation: OrganizationInvitation) => {
    if (!invitation.createdAt) return Number.POSITIVE_INFINITY

    const date =
      invitation.createdAt instanceof Date
        ? invitation.createdAt
        : new Date(invitation.createdAt)
    const time = date.getTime()

    return Number.isNaN(time) ? Number.POSITIVE_INFINITY : time
  }
  const sortInvitations = (
    first: OrganizationInvitation,
    second: OrganizationInvitation
  ) => {
    let comparison = 0

    if (invitationSort() === "email") {
      comparison = (first.email ?? "").localeCompare(second.email ?? "")
    }

    if (invitationSort() === "createdAt") {
      comparison = invitationDateTime(first) - invitationDateTime(second)
    }

    if (invitationSort() === "role") {
      const firstRole = roles()[first.role ?? ""] ?? first.role ?? ""
      const secondRole = roles()[second.role ?? ""] ?? second.role ?? ""

      comparison = firstRole.localeCompare(secondRole)
    }

    if (invitationSort() === "status") {
      comparison = formatStatus(first.status).localeCompare(
        formatStatus(second.status)
      )
    }

    return sortDescriptor()?.direction === "descending"
      ? comparison * -1
      : comparison
  }
  const sortedInvitationRows = () =>
    [...filteredInvitationRows()].sort(sortInvitations)
  const toggleSort = (column: InvitationSortColumn) => {
    setInvitationSort(column)
    setSortDescriptor((current) => {
      if (current?.column !== column) {
        return { column, direction: "ascending" }
      }

      return {
        column,
        direction:
          current.direction === "ascending" ? "descending" : "ascending"
      }
    })
  }

  return (
    <div class={cn("flex flex-col gap-3", props.class)}>
      <h3 class="truncate text-sm font-semibold">Invitations</h3>
      <Show
        when={!invitations.isPending}
        fallback={
          <Card class="!p-0">
            <Table>
              <TableBody>
                <OrganizationInvitationRowSkeleton />
                <OrganizationInvitationRowSkeleton />
              </TableBody>
            </Table>
          </Card>
        }
      >
        <Show
          when={invitationRows().length > 0}
          fallback={
            <Card class="!p-0">
              <Table>
                <TableBody>
                  <TableRow>
                    <TableCell colSpan={5}>
                      <OrganizationInvitationsEmpty />
                    </TableCell>
                  </TableRow>
                </TableBody>
              </Table>
            </Card>
          }
        >
          <div class="flex flex-col gap-2 sm:flex-row sm:items-center">
            <InputGroup class="min-w-0 sm:w-[220px]">
              <InputGroupAddon>
                <Search class="size-4 text-muted-foreground" />
              </InputGroupAddon>
              <InputGroupInput
                aria-label={localization().search}
                onInput={(event) =>
                  setInvitationSearch(event.currentTarget.value)
                }
                placeholder={localization().search}
                type="search"
                value={invitationSearch()}
              />
            </InputGroup>
            <DropdownMenu>
              <DropdownMenuTrigger
                as={Button}
                class="shrink-0"
                variant="outline"
              >
                <Filter class="size-4" />
                {localization().role}
              </DropdownMenuTrigger>
              <DropdownMenuContent>
                <DropdownMenuRadioGroup
                  onChange={setInvitationRoleFilter}
                  value={invitationRoleFilter()}
                >
                  <DropdownMenuRadioItem value="all">
                    {localization().all}
                  </DropdownMenuRadioItem>
                  <For each={Object.entries(roles())}>
                    {([role, label]) => (
                      <DropdownMenuRadioItem value={role}>
                        {label}
                      </DropdownMenuRadioItem>
                    )}
                  </For>
                </DropdownMenuRadioGroup>
              </DropdownMenuContent>
            </DropdownMenu>
            <DropdownMenu>
              <DropdownMenuTrigger
                as={Button}
                class="shrink-0"
                variant="outline"
              >
                <Filter class="size-4" />
                {localization().status}
              </DropdownMenuTrigger>
              <DropdownMenuContent>
                <DropdownMenuRadioGroup
                  onChange={setInvitationStatusFilter}
                  value={invitationStatusFilter()}
                >
                  <DropdownMenuRadioItem value="all">
                    {localization().all}
                  </DropdownMenuRadioItem>
                  <For each={invitationStatuses}>
                    {(status) => (
                      <DropdownMenuRadioItem value={status}>
                        {invitationStatusLabel(status)}
                      </DropdownMenuRadioItem>
                    )}
                  </For>
                </DropdownMenuRadioGroup>
              </DropdownMenuContent>
            </DropdownMenu>
          </div>
          <Show
            when={
              invitationRoleFilter() !== "all" ||
              invitationStatusFilter() !== "all"
            }
          >
            <div class="flex flex-wrap gap-2">
              <Show when={invitationRoleFilter() !== "all"}>
                <Badge class="gap-1 pr-1" variant="secondary">
                  {localization().role}: {selectedRoleLabel()}
                  <button
                    aria-label={`${localization().clear} invitation role filter`}
                    class="rounded-sm p-0.5 hover:bg-muted"
                    onClick={() => setInvitationRoleFilter("all")}
                    type="button"
                  >
                    <X class="size-3" />
                  </button>
                </Badge>
              </Show>
              <Show when={invitationStatusFilter() !== "all"}>
                <Badge class="gap-1 pr-1" variant="secondary">
                  {localization().status}: {selectedStatusLabel()}
                  <button
                    aria-label={`${localization().clear} invitation status filter`}
                    class="rounded-sm p-0.5 hover:bg-muted"
                    onClick={() => setInvitationStatusFilter("all")}
                    type="button"
                  >
                    <X class="size-3" />
                  </button>
                </Badge>
              </Show>
            </div>
          </Show>
          <Card class="!p-0">
            <Table aria-label="Invitations">
              <TableHeader>
                <TableRow>
                  <SortableTableHead
                    onClick={() => toggleSort("email")}
                    sortDirection={
                      sortDescriptor()?.column === "email"
                        ? sortDescriptor()?.direction
                        : undefined
                    }
                  >
                    Email
                  </SortableTableHead>
                  <SortableTableHead
                    onClick={() => toggleSort("createdAt")}
                    sortDirection={
                      sortDescriptor()?.column === "createdAt"
                        ? sortDescriptor()?.direction
                        : undefined
                    }
                  >
                    Invited
                  </SortableTableHead>
                  <SortableTableHead
                    onClick={() => toggleSort("role")}
                    sortDirection={
                      sortDescriptor()?.column === "role"
                        ? sortDescriptor()?.direction
                        : undefined
                    }
                  >
                    {localization().role}
                  </SortableTableHead>
                  <SortableTableHead
                    onClick={() => toggleSort("status")}
                    sortDirection={
                      sortDescriptor()?.column === "status"
                        ? sortDescriptor()?.direction
                        : undefined
                    }
                  >
                    {localization().status}
                  </SortableTableHead>
                  <TableHead class="!text-end">Actions</TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                <Show
                  when={filteredInvitationRows().length > 0}
                  fallback={
                    <TableRow>
                      <TableCell
                        class="text-muted-foreground text-sm"
                        colSpan={5}
                      >
                        No invitations match the current filters.
                      </TableCell>
                    </TableRow>
                  }
                >
                  <For each={sortedInvitationRows()}>
                    {(invitation) => (
                      <OrganizationInvitationRow
                        invitation={invitation}
                        roles={roles()}
                      />
                    )}
                  </For>
                </Show>
              </TableBody>
            </Table>
          </Card>
        </Show>
      </Show>
    </div>
  )
}
