// packages/heroui/src/components/auth/organization/organization-view-skeleton.tsx
import { cn, Skeleton } from "@heroui/react"
import type { ComponentProps } from "react"

import { OrganizationLogo } from "./organization-logo"
import type { OrganizationViewProps } from "./organization-view"

/**
 * Placeholder matching {@link OrganizationView} while organization data loads.
 */
export function OrganizationViewSkeleton({
  className,
  hideSlug,
  size = "md",
  ...props
}: OrganizationViewProps & ComponentProps<"div">) {
  return (
    <div
      className={cn("flex min-w-0 items-center gap-2", className)}
      {...props}
    >
      <OrganizationLogo
        isPending
        className={size === "sm" ? "size-5" : undefined}
        size={size === "lg" ? "md" : "sm"}
      />

      <div className="flex flex-col min-w-0 gap-1">
        <Skeleton className="h-3.5 w-20 rounded-lg" />

        {!hideSlug && (
          <Skeleton className="h-3 w-28 rounded-lg mt-[0.5px] mb-0.5" />
        )}
      </div>
    </div>
  )
}

// examples/start-solid-zaidan-example/src/components/auth/organization/organization-view-skeleton.tsx
import type { ComponentProps } from "solid-js"
import { Show, splitProps } from "solid-js"
import { Skeleton } from "@/components/ui/skeleton"
import { cn } from "@/lib/utils"
import {
  OrganizationLogo,
  type OrganizationLogoSize
} from "./organization-logo"

export type OrganizationViewSkeletonProps = ComponentProps<"div"> & {
  hideSlug?: boolean
  size?: OrganizationLogoSize
}

export function OrganizationViewSkeleton(props: OrganizationViewSkeletonProps) {
  const [local, others] = splitProps(props, ["class", "hideSlug", "size"])
  const size = () => local.size ?? "md"

  return (
    <div class={cn("flex min-w-0 items-center gap-2", local.class)} {...others}>
      <OrganizationLogo
        isPending
        class={size() === "sm" ? "size-5" : undefined}
        size={size() === "lg" ? "md" : "sm"}
      />

      <div class="flex min-w-0 flex-col gap-1">
        <Skeleton class="h-3.5 w-20 rounded-md" />

        <Show when={!local.hideSlug}>
          <Skeleton class="h-3 w-28 rounded-md" />
        </Show>
      </div>
    </div>
  )
}
