// packages/heroui/src/components/auth/organization/organization-view.tsx
import {
  type OrganizationAuthClient,
  useActiveOrganization,
  useAuth,
  useAuthPlugin,
  useListOrganizationMembers,
  useSession
} from "@better-auth-ui/react"
import { type AvatarProps, Chip, cn } from "@heroui/react"
import type { Organization } from "better-auth/client"
import type { ComponentProps } from "react"

import { organizationPlugin } from "../../../lib/auth/organization-plugin"
import { OrganizationLogo } from "./organization-logo"
import { OrganizationViewSkeleton } from "./organization-view-skeleton"

export type OrganizationViewProps = {
  className?: string
  isPending?: boolean
  size?: AvatarProps["size"]
  hideRole?: boolean
  hideSlug?: boolean
  organization?: Partial<Organization>
}

/**
 * Compact organization row: logo, primary name, secondary slug — analogous to {@link UserView}.
 */
export function OrganizationView({
  className,
  isPending,
  size = "md",
  hideSlug,
  hideRole,
  organization,
  ...props
}: OrganizationViewProps & ComponentProps<"div">) {
  const { authClient } = useAuth()
  const { roles } = useAuthPlugin(organizationPlugin)

  const { data: session } = useSession(authClient)

  const { data: activeOrganization, isPending: activeOrganizationPending } =
    useActiveOrganization(authClient as OrganizationAuthClient, {
      enabled: !organization && !isPending
    })

  const resolvedOrganization = organization ?? activeOrganization

  const { data: membersList, isPending: membersPending } =
    useListOrganizationMembers(authClient as OrganizationAuthClient, {
      query: {
        organizationId: resolvedOrganization?.id
      },
      enabled: !!resolvedOrganization?.id && !hideRole
    })

  const membership = membersList?.members?.find(
    (member) => member.userId === session?.user.id
  )

  if (
    isPending ||
    (!organization && activeOrganizationPending) ||
    (!hideRole && !!resolvedOrganization?.id && membersPending)
  ) {
    return (
      <OrganizationViewSkeleton
        className={className}
        hideSlug={hideSlug}
        size={size}
        {...props}
      />
    )
  }

  return (
    <div
      className={cn("flex min-w-0 items-center gap-2", className)}
      {...props}
    >
      <OrganizationLogo
        organization={resolvedOrganization}
        className={size === "sm" ? "size-5 [&>span]:text-xs" : undefined}
        size={size === "lg" ? "md" : "sm"}
      />

      <div className="flex flex-col min-w-0">
        <div className="flex min-w-0 items-center gap-2">
          <p className="text-foreground text-sm font-medium truncate leading-tight">
            {resolvedOrganization?.name}
          </p>

          {!hideRole && !!membership && (
            <Chip className="shrink-0 -my-0.5" size="sm">
              {roles?.[membership.role] ?? membership.role}
            </Chip>
          )}
        </div>

        {!hideSlug && (
          <p className="text-muted text-xs truncate overflow-x-hidden font-mono leading-tight">
            {resolvedOrganization?.slug}
          </p>
        )}
      </div>
    </div>
  )
}

// examples/start-solid-zaidan-example/src/components/auth/organization/organization-view.tsx
import type { OrganizationLocalization } from "@better-auth-ui/core/plugins"
import { organizationLocalization } from "@better-auth-ui/core/plugins"
import type { OrganizationAuthClient } from "@better-auth-ui/solid"
import {
  useActiveOrganization,
  useAuth,
  useListOrganizationMembers,
  useSession
} from "@better-auth-ui/solid"
import type { Organization } from "better-auth/client"
import type { ComponentProps } from "solid-js"
import { Show, splitProps } from "solid-js"
import { Badge } from "@/components/ui/badge"
import { organizationPlugin } from "@/lib/auth/organization-plugin"
import { cn } from "@/lib/utils"
import {
  OrganizationLogo,
  type OrganizationLogoSize
} from "./organization-logo"
import { OrganizationViewSkeleton } from "./organization-view-skeleton"

type OrganizationPluginConfig = {
  roles?: Record<string, string>
  localization?: OrganizationLocalization
}

type OrganizationMember = {
  userId: string
  role: string
}

export type OrganizationViewProps = ComponentProps<"div"> & {
  isPending?: boolean
  size?: OrganizationLogoSize
  hideRole?: boolean
  hideSlug?: boolean
  organization?: Partial<Organization>
}

export function OrganizationView(props: OrganizationViewProps) {
  const [local, others] = splitProps(props, [
    "class",
    "isPending",
    "size",
    "hideRole",
    "hideSlug",
    "organization"
  ])
  const auth = useAuth()
  const client = auth.authClient as OrganizationAuthClient
  const pluginConfig = () =>
    auth.plugins.find((plugin) => plugin.id === organizationPlugin.id) as
      | OrganizationPluginConfig
      | undefined
  const roles = () =>
    pluginConfig()?.roles ?? {
      owner: organizationLocalization.owner,
      admin: organizationLocalization.admin,
      member: organizationLocalization.member
    }
  const session = useSession(client)
  const activeOrganization = useActiveOrganization(client, {
    enabled: !local.organization && !local.isPending
  } as never)
  const resolvedOrganization = () =>
    local.organization ?? activeOrganization.data
  const membersList = useListOrganizationMembers(client, {
    query: { organizationId: resolvedOrganization()?.id },
    enabled: !!resolvedOrganization()?.id && !local.hideRole
  } as never)
  const membership = () =>
    (membersList.data?.members as OrganizationMember[] | undefined)?.find(
      (member) => member.userId === session.data?.user.id
    )

  return (
    <Show
      when={
        !local.isPending &&
        (local.organization || !activeOrganization.isPending) &&
        (local.hideRole ||
          !resolvedOrganization()?.id ||
          !membersList.isPending)
      }
      fallback={
        <OrganizationViewSkeleton
          class={local.class}
          hideSlug={local.hideSlug}
          size={local.size}
        />
      }
    >
      <div
        class={cn("flex min-w-0 items-center gap-2", local.class)}
        {...others}
      >
        <OrganizationLogo
          organization={resolvedOrganization()}
          class={local.size === "sm" ? "size-5" : undefined}
          size={local.size === "lg" ? "md" : "sm"}
        />

        <div class="flex min-w-0 flex-col">
          <div class="flex min-w-0 items-center gap-2">
            <p class="truncate text-sm font-medium leading-tight text-foreground">
              {resolvedOrganization()?.name}
            </p>

            <Show when={!local.hideRole && membership()}>
              {(member) => (
                <Badge variant="secondary" class="-my-0.5 shrink-0">
                  {roles()[member().role] ?? member().role}
                </Badge>
              )}
            </Show>
          </div>

          <Show when={!local.hideSlug}>
            <p class="truncate overflow-x-hidden font-mono text-muted-foreground text-xs leading-tight">
              {resolvedOrganization()?.slug}
            </p>
          </Show>
        </div>
      </div>
    </Show>
  )
}
