// packages/heroui/src/components/auth/organization/user-invitations.tsx
import {
  type OrganizationAuthClient,
  useAuth,
  useAuthPlugin,
  useListUserInvitations
} from "@better-auth-ui/react"
import { Card, type CardProps } from "@heroui/react"

import { organizationPlugin } from "../../../lib/auth/organization-plugin"
import { UserInvitationRow } from "./user-invitation-row"
import { UserInvitationRowSkeleton } from "./user-invitation-row-skeleton"
import { UserInvitationsEmpty } from "./user-invitations-empty"

export type UserInvitationsProps = {
  variant?: CardProps["variant"]
}

/**
 * Organization invitations for the signed-in user (from
 * {@link useListUserInvitations}). Always renders the section card; uses
 * {@link UserInvitationsEmpty} when there are no pending invitations.
 */
export function UserInvitations({ variant }: UserInvitationsProps) {
  const { authClient } = useAuth()
  const { localization: organizationLocalization } =
    useAuthPlugin(organizationPlugin)

  const { data: invitations, isPending } = useListUserInvitations(
    authClient as OrganizationAuthClient
  )

  return (
    <div className="flex flex-col gap-3">
      <h2 className="truncate text-sm font-semibold">
        {organizationLocalization.invitations}
      </h2>

      <Card variant={variant}>
        <Card.Content>
          {isPending ? (
            <UserInvitationRowSkeleton />
          ) : !invitations?.length ? (
            <UserInvitationsEmpty />
          ) : (
            invitations?.map((invitation, index) => (
              <div key={invitation.id}>
                {index > 0 && (
                  <div className="border-b border-dashed -mx-4 my-4" />
                )}

                <UserInvitationRow invitation={invitation} />
              </div>
            ))
          )}
        </Card.Content>
      </Card>
    </div>
  )
}

// examples/start-solid-zaidan-example/src/components/auth/organization/user-invitations.tsx
import { organizationLocalization } from "@better-auth-ui/core/plugins"
import type { OrganizationAuthClient } from "@better-auth-ui/solid"
import { useAuth, useListUserInvitations } from "@better-auth-ui/solid"
import { For, Show } from "solid-js"
import { Card, CardContent } from "@/components/ui/card"
import { Separator } from "@/components/ui/separator"
import { UserInvitationRow } from "./user-invitation-row"
import { UserInvitationRowSkeleton } from "./user-invitation-row-skeleton"
import { UserInvitationsEmpty } from "./user-invitations-empty"

export type UserInvitationsProps = {
  class?: string
}

type UserInvitation = {
  createdAt?: Date | string | null
  id: string
  organizationName?: string | null
  role?: string | null
}

export function UserInvitations(props: UserInvitationsProps = {}) {
  const auth = useAuth()
  const invitations = useListUserInvitations(
    auth.authClient as OrganizationAuthClient
  )
  const invitationRows = () => (invitations.data ?? []) as UserInvitation[]

  return (
    <div class={props.class}>
      <div class="flex flex-col gap-3">
        <h2 class="truncate font-semibold text-sm">
          {organizationLocalization.invitations}
        </h2>
        <Card class="z-card-padding-none">
          <CardContent class="z-card-content-padding-none">
            <Show
              when={!invitations.isPending}
              fallback={
                <div class="p-4">
                  <UserInvitationRowSkeleton />
                </div>
              }
            >
              <Show
                when={invitationRows().length > 0}
                fallback={<UserInvitationsEmpty />}
              >
                <For each={invitationRows()}>
                  {(invitation, index) => (
                    <>
                      <Show when={index() > 0}>
                        <Separator />
                      </Show>

                      <div class="p-4">
                        <UserInvitationRow invitation={invitation} />
                      </div>
                    </>
                  )}
                </For>
              </Show>
            </Show>
          </CardContent>
        </Card>
      </div>
    </div>
  )
}
