// packages/solid/src/lib/auth-provider.tsx
import type { AuthConfig } from "@better-auth-ui/core"
import { QueryClient, QueryClientProvider } from "@tanstack/solid-query"
import { createContext, type JSX, useContext } from "solid-js"
import type { AuthClient } from "./auth-client"
import { resolveAuthConfig, type SolidAuthConfigInput } from "./auth-config"
import { FetchOptionsProvider } from "./fetch-options-provider"
import { MutationInvalidator } from "./mutation-invalidator"

const AuthContext = createContext<AuthConfig>()
/** Provider-instance scoped config fallback for SSR — replaces the former module-level global. */
const RenderingAuthConfigContext = createContext<AuthConfig>()

const fallbackQueryClient = new QueryClient({
  defaultOptions: {
    queries: {
      staleTime: 5000
    }
  }
})

export type AuthProviderProps<TAuthClient = AuthClient> =
  SolidAuthConfigInput<TAuthClient> & {
    children?: JSX.Element | (() => JSX.Element)
    /** TanStack QueryClient to use for your application's queries. */
    queryClient?: QueryClient
  }

const resolveProviderChildren = (children: AuthProviderProps["children"]) =>
  typeof children === "function" ? children() : children

export function AuthProvider(props: AuthProviderProps) {
  const { children, queryClient: qc, ...configInput } = props
  const config = resolveAuthConfig(configInput as AuthProviderProps<AuthClient>)
  const queryClient = qc || fallbackQueryClient

  return (
    <AuthContext.Provider value={config}>
      <RenderingAuthConfigContext.Provider value={config}>
        <QueryClientProvider client={queryClient}>
          <FetchOptionsProvider>
            <MutationInvalidator queryClient={queryClient} />
            {resolveProviderChildren(children)}
          </FetchOptionsProvider>
        </QueryClientProvider>
      </RenderingAuthConfigContext.Provider>
    </AuthContext.Provider>
  )
}

export function useAuth(): AuthConfig {
  const context = useContext(AuthContext)
  const renderingConfig = useContext(RenderingAuthConfigContext)
  const auth = context ?? renderingConfig

  if (!auth) {
    throw new Error("[Better Auth UI] AuthProvider is required")
  }

  return auth
}

// packages/react/src/components/auth/auth-provider.tsx
"use client"

import {
  type AuthConfig,
  type DeepPartial,
  deepmerge,
  defaultAuthConfig
} from "@better-auth-ui/core"
import {
  QueryClient,
  QueryClientContext,
  QueryClientProvider
} from "@tanstack/react-query"
import { createContext, type PropsWithChildren, useContext } from "react"

import type { AuthClient } from "../../lib/auth-clients/auth-client"

const AuthContext = createContext<AuthConfig<AuthClient> | undefined>(undefined)

const fallbackQueryClient = new QueryClient()

declare module "@better-auth-ui/core" {
  interface AuthConfig {
    authClient: AuthClient
  }
}

export type AuthProviderProps<TAuthClient = AuthClient> = PropsWithChildren<
  DeepPartial<AuthConfig>
> & {
  authClient: TAuthClient
  navigate: (options: { to: string; replace?: boolean }) => void
  /** TanStack QueryClient to use for your application's queries */
  queryClient?: QueryClient
}

/**
 * Provides merged authentication configuration and a resolved React Query client to descendant components.
 *
 * The component merges the provided auth config with the library defaults, updates `redirectTo` from the
 * current URL when the app is hydrated, wires a QueryClient (prop, context, or fallback) and installs an
 * error handler that surfaces query errors via the configured toast. It then supplies the merged config
 * via AuthContext and wraps children with QueryClientProvider.
 *
 * @returns The children wrapped with AuthContext.Provider and QueryClientProvider configured for auth.
 */
export function AuthProvider({
  children,
  queryClient,
  ...config
}: AuthProviderProps) {
  const mergedConfig = deepmerge(
    defaultAuthConfig,
    config as AuthConfig
  ) as AuthConfig<AuthClient>

  mergedConfig.redirectTo =
    (typeof window !== "undefined" &&
      new URLSearchParams(window.location.search).get("redirectTo")?.trim()) ||
    mergedConfig.redirectTo

  const contextQueryClient = useContext(QueryClientContext)

  if (contextQueryClient) {
    return (
      <AuthContext.Provider value={mergedConfig}>
        {children}
      </AuthContext.Provider>
    )
  }

  return (
    <QueryClientProvider client={queryClient || fallbackQueryClient}>
      <AuthContext.Provider value={mergedConfig}>
        {children}
      </AuthContext.Provider>
    </QueryClientProvider>
  )
}

/**
 * Accesses the current authentication configuration from AuthContext.
 *
 * @returns The merged authentication configuration provided by AuthProvider.
 * @throws If no AuthProvider is present in the component tree.
 */
export function useAuth<TAuthClient = AuthClient>() {
  const context = useContext(AuthContext) as AuthConfig<TAuthClient>

  if (!context) {
    throw new Error("[Better Auth UI] AuthProvider is required")
  }

  return context
}
