// examples/next-shadcn-registry-example/src/components/settings/security/change-password.tsx
"use client"

import { useAuth, useChangePassword, useSession } from "@better-auth-ui/react"
import { Eye, EyeOff } from "lucide-react"
import { type SyntheticEvent, useState } from "react"
import { toast } from "sonner"

import { Button } from "@/components/ui/button"
import { Card, CardContent, CardFooter } from "@/components/ui/card"
import { Field, FieldError, FieldLabel } from "@/components/ui/field"
import { Input } from "@/components/ui/input"
import {
  InputGroup,
  InputGroupAddon,
  InputGroupButton,
  InputGroupInput
} from "@/components/ui/input-group"
import { Skeleton } from "@/components/ui/skeleton"
import { Spinner } from "@/components/ui/spinner"
import { cn } from "@/lib/utils"

export type ChangePasswordProps = {
  className?: string
}

/**
 * Render a card form for changing the authenticated user's password.
 *
 * Displays a card with fields for current password, new password, and optionally
 * confirm password (based on `emailAndPassword.confirmPassword`). All other sessions
 * are revoked upon successful password change.
 *
 * @returns A JSX element containing the change-password card and form
 */
export function ChangePassword({ className }: ChangePasswordProps) {
  const { emailAndPassword, localization } = useAuth()
  const { data: sessionData } = useSession()

  const [currentPassword, setCurrentPassword] = useState("")
  const [newPassword, setNewPassword] = useState("")
  const [confirmPassword, setConfirmPassword] = useState("")

  const { mutate: changePassword, isPending } = useChangePassword({
    onError: (error) => {
      setCurrentPassword("")
      setNewPassword("")
      setConfirmPassword("")
      toast.error(error.error?.message || error.message)
    },
    onSuccess: () => {
      setCurrentPassword("")
      setNewPassword("")
      setConfirmPassword("")
      toast.success(localization.settings.changePasswordSuccess)
    }
  })

  const [isNewPasswordVisible, setIsNewPasswordVisible] = useState(false)
  const [isConfirmPasswordVisible, setIsConfirmPasswordVisible] =
    useState(false)

  const [fieldErrors, setFieldErrors] = useState<{
    currentPassword?: string
    newPassword?: string
    confirmPassword?: string
  }>({})

  const handleSubmit = (e: SyntheticEvent<HTMLFormElement>) => {
    e.preventDefault()

    if (emailAndPassword.confirmPassword && newPassword !== confirmPassword) {
      setCurrentPassword("")
      setNewPassword("")
      setConfirmPassword("")
      toast.error(localization.auth.passwordsDoNotMatch)
      return
    }

    changePassword({
      currentPassword,
      newPassword,
      revokeOtherSessions: true
    })
  }

  return (
    <div>
      <h2 className="text-sm font-semibold mb-3">
        {localization.settings.changePassword}
      </h2>

      <form onSubmit={handleSubmit}>
        <Card className={cn(className)}>
          <CardContent className="grid gap-4">
            <Field data-invalid={!!fieldErrors.currentPassword}>
              <FieldLabel htmlFor="currentPassword">
                {localization.settings.currentPassword}
              </FieldLabel>

              {sessionData ? (
                <Input
                  id="currentPassword"
                  name="currentPassword"
                  type="password"
                  autoComplete="current-password"
                  placeholder={localization.settings.currentPasswordPlaceholder}
                  value={currentPassword}
                  onChange={(e) => {
                    setCurrentPassword(e.target.value)
                    setFieldErrors((prev) => ({
                      ...prev,
                      currentPassword: undefined
                    }))
                  }}
                  disabled={isPending}
                  required
                  onInvalid={(e) => {
                    e.preventDefault()
                    setFieldErrors((prev) => ({
                      ...prev,
                      currentPassword: (e.target as HTMLInputElement)
                        .validationMessage
                    }))
                  }}
                  aria-invalid={!!fieldErrors.currentPassword}
                />
              ) : (
                <Skeleton className="h-8 w-full" />
              )}

              <FieldError>{fieldErrors.currentPassword}</FieldError>
            </Field>

            <Field data-invalid={!!fieldErrors.newPassword}>
              <FieldLabel htmlFor="newPassword">
                {localization.auth.newPassword}
              </FieldLabel>

              {sessionData ? (
                <InputGroup>
                  <InputGroupInput
                    id="newPassword"
                    name="newPassword"
                    type={isNewPasswordVisible ? "text" : "password"}
                    autoComplete="new-password"
                    placeholder={localization.auth.newPasswordPlaceholder}
                    value={newPassword}
                    onChange={(e) => {
                      setNewPassword(e.target.value)
                      setFieldErrors((prev) => ({
                        ...prev,
                        newPassword: undefined
                      }))
                    }}
                    minLength={emailAndPassword.minPasswordLength}
                    maxLength={emailAndPassword.maxPasswordLength}
                    disabled={isPending}
                    required
                    onInvalid={(e) => {
                      e.preventDefault()
                      setFieldErrors((prev) => ({
                        ...prev,
                        newPassword: (e.target as HTMLInputElement)
                          .validationMessage
                      }))
                    }}
                    aria-invalid={!!fieldErrors.newPassword}
                  />

                  <InputGroupAddon align="inline-end">
                    <InputGroupButton
                      size="icon-xs"
                      aria-label={
                        isNewPasswordVisible
                          ? localization.auth.hidePassword
                          : localization.auth.showPassword
                      }
                      onClick={() =>
                        setIsNewPasswordVisible(!isNewPasswordVisible)
                      }
                      disabled={isPending}
                    >
                      {isNewPasswordVisible ? <EyeOff /> : <Eye />}
                    </InputGroupButton>
                  </InputGroupAddon>
                </InputGroup>
              ) : (
                <Skeleton className="h-8 w-full" />
              )}

              <FieldError>{fieldErrors.newPassword}</FieldError>
            </Field>

            {emailAndPassword.confirmPassword && (
              <Field data-invalid={!!fieldErrors.confirmPassword}>
                <FieldLabel htmlFor="confirmPassword">
                  {localization.auth.confirmPassword}
                </FieldLabel>

                {sessionData ? (
                  <InputGroup>
                    <InputGroupInput
                      id="confirmPassword"
                      name="confirmPassword"
                      type={isConfirmPasswordVisible ? "text" : "password"}
                      autoComplete="new-password"
                      placeholder={localization.auth.confirmPasswordPlaceholder}
                      value={confirmPassword}
                      onChange={(e) => {
                        setConfirmPassword(e.target.value)
                        setFieldErrors((prev) => ({
                          ...prev,
                          confirmPassword: undefined
                        }))
                      }}
                      minLength={emailAndPassword.minPasswordLength}
                      maxLength={emailAndPassword.maxPasswordLength}
                      disabled={isPending}
                      required
                      onInvalid={(e) => {
                        e.preventDefault()
                        setFieldErrors((prev) => ({
                          ...prev,
                          confirmPassword: (e.target as HTMLInputElement)
                            .validationMessage
                        }))
                      }}
                      aria-invalid={!!fieldErrors.confirmPassword}
                    />

                    <InputGroupAddon align="inline-end">
                      <InputGroupButton
                        size="icon-xs"
                        aria-label={
                          isConfirmPasswordVisible
                            ? localization.auth.hidePassword
                            : localization.auth.showPassword
                        }
                        onClick={() =>
                          setIsConfirmPasswordVisible(!isConfirmPasswordVisible)
                        }
                        disabled={isPending}
                      >
                        {isConfirmPasswordVisible ? <EyeOff /> : <Eye />}
                      </InputGroupButton>
                    </InputGroupAddon>
                  </InputGroup>
                ) : (
                  <Skeleton className="h-8 w-full" />
                )}

                <FieldError>{fieldErrors.confirmPassword}</FieldError>
              </Field>
            )}
          </CardContent>

          <CardFooter>
            <Button
              type="submit"
              size="sm"
              disabled={isPending || !sessionData}
            >
              {isPending && <Spinner />}

              {localization.settings.updatePassword}
            </Button>
          </CardFooter>
        </Card>
      </form>
    </div>
  )
}

// examples/start-solid-zaidan-example/src/components/auth/settings/security/change-password.tsx
import {
  changePasswordOptions,
  listAccountsOptions,
  requestPasswordResetOptions,
  useAuth,
  useSession
} from "@better-auth-ui/solid"
import { createMutation, createQuery } from "@tanstack/solid-query"
import type { BetterFetchError } from "better-auth/client"
import { Eye, EyeOff } from "lucide-solid"
import { createSignal, Show } from "solid-js"
import { toast } from "solid-sonner"
import { OpenEmailButton } from "@/components/auth/open-email-button"
import { shouldLoadAccounts } from "@/components/auth/settings/shared/helpers"
import type { ChangePasswordFieldErrors } from "@/components/auth/settings/shared/types"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardFooter } from "@/components/ui/card"
import { Input } from "@/components/ui/input"
import {
  InputGroup,
  InputGroupAddon,
  InputGroupButton,
  InputGroupInput
} from "@/components/ui/input-group"
import { Label } from "@/components/ui/label"
import { Skeleton } from "@/components/ui/skeleton"
import { cn } from "@/lib/utils"

function ChangePasswordSkeletonInput() {
  return (
    <Skeleton>
      <Input class="invisible" />
    </Skeleton>
  )
}

export type ChangePasswordSettingsProps = {
  class?: string
  confirmPassword?: boolean
}

export function ChangePasswordSettings(
  props: ChangePasswordSettingsProps = {}
) {
  const auth = useAuth()
  const session = useSession(auth.authClient)
  const userId = () => session.data?.user.id
  const linkedAccounts = createQuery(() => ({
    ...listAccountsOptions(auth.authClient, userId()),
    enabled: shouldLoadAccounts({
      isSsr: import.meta.env.SSR,
      userId: userId()
    })
  }))
  const hasCredentialAccount = () =>
    linkedAccounts.data?.some(
      (account: { providerId?: string }) => account.providerId === "credential"
    )
  const requestPasswordReset = createMutation(() =>
    requestPasswordResetOptions(auth.authClient)
  )
  const changePassword = createMutation(() => ({
    ...changePasswordOptions(auth.authClient),
    onError: (error: BetterFetchError) => {
      setCurrentPassword("")
      setNewPassword("")
      setConfirmPassword("")
      toast.error(error.error?.message || error.message)
    },
    onSuccess: () => {
      setCurrentPassword("")
      setNewPassword("")
      setConfirmPassword("")
      toast.success(auth.localization.settings.changePasswordSuccess)
    }
  }))
  const [currentPassword, setCurrentPassword] = createSignal("")
  const [newPassword, setNewPassword] = createSignal("")
  const [confirmPassword, setConfirmPassword] = createSignal("")
  const [isCurrentPasswordVisible, setIsCurrentPasswordVisible] =
    createSignal(false)
  const [isNewPasswordVisible, setIsNewPasswordVisible] = createSignal(false)
  const [isConfirmPasswordVisible, setIsConfirmPasswordVisible] =
    createSignal(false)
  const [fieldErrors, setFieldErrors] = createSignal<ChangePasswordFieldErrors>(
    {}
  )

  const setPasswordFieldError = (
    field: keyof ChangePasswordFieldErrors,
    message?: string
  ) => {
    setFieldErrors((previous) => ({ ...previous, [field]: message }))
  }

  const resetPasswordFields = () => {
    setCurrentPassword("")
    setNewPassword("")
    setConfirmPassword("")
  }

  const sendResetLink = () => {
    if (!session.data) return

    requestPasswordReset.mutate({
      email: session.data.user.email
    } as Parameters<typeof requestPasswordReset.mutate>[0])
  }

  const submitChangePassword = (event: SubmitEvent) => {
    event.preventDefault()

    if (props.confirmPassword && newPassword() !== confirmPassword()) {
      resetPasswordFields()
      toast.error(auth.localization.auth.passwordsDoNotMatch)
      return
    }

    changePassword.mutate({
      currentPassword: currentPassword(),
      newPassword: newPassword(),
      revokeOtherSessions: true
    } as Parameters<typeof changePassword.mutate>[0])
  }

  const isPasswordPending = () =>
    changePassword.isPending || requestPasswordReset.isPending

  if (!linkedAccounts.isPending && !hasCredentialAccount()) {
    return (
      <div class={cn(props.class)}>
        <h2 class="mb-3 text-sm font-semibold">
          {auth.localization.settings.changePassword}
        </h2>

        <Card>
          <CardContent class="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between">
            <div>
              <p class="font-medium text-sm leading-tight">
                {auth.localization.settings.setPassword}
              </p>
              <p class="mt-0.5 text-muted-foreground text-xs">
                {auth.localization.settings.setPasswordDescription}
              </p>
            </div>

            <Show
              fallback={
                <Button
                  disabled={requestPasswordReset.isPending || !session.data}
                  onClick={sendResetLink}
                  size="sm"
                  type="button"
                >
                  {requestPasswordReset.isPending
                    ? `${auth.localization.auth.sendResetLink}…`
                    : auth.localization.auth.sendResetLink}
                </Button>
              }
              when={requestPasswordReset.isSuccess && session.data?.user.email}
              keyed
            >
              {(sentEmail) => (
                <div class="flex flex-col items-start gap-3 sm:items-end">
                  <p class="text-sm" role="status">
                    {auth.localization.auth.resetLinkSentTo.replace(
                      "{{email}}",
                      sentEmail
                    )}
                  </p>

                  <OpenEmailButton class="w-auto" email={sentEmail} />
                </div>
              )}
            </Show>
          </CardContent>
        </Card>
      </div>
    )
  }

  return (
    <div class={cn(props.class)}>
      <h2 class="mb-3 text-sm font-semibold">
        {auth.localization.settings.changePassword}
      </h2>

      <form onSubmit={submitChangePassword}>
        <Card>
          <CardContent class="flex flex-col gap-6">
            <div class="grid gap-2">
              <Label for="currentPassword">
                {auth.localization.settings.currentPassword}
              </Label>
              <Show
                fallback={<ChangePasswordSkeletonInput />}
                when={session.data && !linkedAccounts.isPending}
              >
                <InputGroup>
                  <InputGroupInput
                    aria-invalid={!!fieldErrors().currentPassword}
                    autocomplete="current-password"
                    disabled={isPasswordPending()}
                    id="currentPassword"
                    name="currentPassword"
                    onInput={(event) => {
                      setCurrentPassword(event.currentTarget.value)
                      setPasswordFieldError("currentPassword")
                    }}
                    onInvalid={(event) => {
                      event.preventDefault()
                      setPasswordFieldError(
                        "currentPassword",
                        event.currentTarget.validationMessage
                      )
                    }}
                    placeholder={
                      auth.localization.settings.currentPasswordPlaceholder
                    }
                    required
                    type={isCurrentPasswordVisible() ? "text" : "password"}
                    value={currentPassword()}
                  />
                  <InputGroupAddon align="inline-end">
                    <InputGroupButton
                      aria-label={
                        isCurrentPasswordVisible()
                          ? auth.localization.auth.hidePassword
                          : auth.localization.auth.showPassword
                      }
                      disabled={isPasswordPending()}
                      onClick={() =>
                        setIsCurrentPasswordVisible((visible) => !visible)
                      }
                      size="icon-sm"
                      title={
                        isCurrentPasswordVisible()
                          ? auth.localization.auth.hidePassword
                          : auth.localization.auth.showPassword
                      }
                    >
                      <Show
                        when={isCurrentPasswordVisible()}
                        fallback={<Eye aria-hidden class="size-4" />}
                      >
                        <EyeOff aria-hidden class="size-4" />
                      </Show>
                    </InputGroupButton>
                  </InputGroupAddon>
                </InputGroup>
              </Show>
              <Show when={fieldErrors().currentPassword}>
                {(message) => (
                  <p class="text-destructive text-sm" role="alert">
                    {message()}
                  </p>
                )}
              </Show>
            </div>

            <div class="grid gap-2">
              <Label for="newPassword">
                {auth.localization.auth.newPassword}
              </Label>
              <Show
                fallback={<ChangePasswordSkeletonInput />}
                when={session.data && !linkedAccounts.isPending}
              >
                <InputGroup>
                  <InputGroupInput
                    aria-invalid={!!fieldErrors().newPassword}
                    autocomplete="new-password"
                    disabled={isPasswordPending()}
                    id="newPassword"
                    maxLength={auth.emailAndPassword.maxPasswordLength}
                    minLength={auth.emailAndPassword.minPasswordLength}
                    name="newPassword"
                    onInput={(event) => {
                      setNewPassword(event.currentTarget.value)
                      setPasswordFieldError("newPassword")
                    }}
                    onInvalid={(event) => {
                      event.preventDefault()
                      setPasswordFieldError(
                        "newPassword",
                        event.currentTarget.validationMessage
                      )
                    }}
                    placeholder={auth.localization.auth.newPasswordPlaceholder}
                    required
                    type={isNewPasswordVisible() ? "text" : "password"}
                    value={newPassword()}
                  />
                  <InputGroupAddon align="inline-end">
                    <InputGroupButton
                      aria-label={
                        isNewPasswordVisible()
                          ? auth.localization.auth.hidePassword
                          : auth.localization.auth.showPassword
                      }
                      disabled={isPasswordPending()}
                      onClick={() =>
                        setIsNewPasswordVisible((visible) => !visible)
                      }
                      size="icon-sm"
                      title={
                        isNewPasswordVisible()
                          ? auth.localization.auth.hidePassword
                          : auth.localization.auth.showPassword
                      }
                      type="button"
                    >
                      {isNewPasswordVisible() ? (
                        <EyeOff aria-hidden class="size-4" />
                      ) : (
                        <Eye aria-hidden class="size-4" />
                      )}
                    </InputGroupButton>
                  </InputGroupAddon>
                </InputGroup>
              </Show>
              <Show when={fieldErrors().newPassword}>
                {(message) => (
                  <p class="text-destructive text-sm" role="alert">
                    {message()}
                  </p>
                )}
              </Show>
            </div>

            <Show when={props.confirmPassword}>
              <div class="grid gap-2">
                <Label for="confirmPassword">
                  {auth.localization.auth.confirmPassword}
                </Label>
                <Show
                  fallback={<ChangePasswordSkeletonInput />}
                  when={session.data && !linkedAccounts.isPending}
                >
                  <InputGroup>
                    <InputGroupInput
                      aria-invalid={!!fieldErrors().confirmPassword}
                      autocomplete="new-password"
                      disabled={isPasswordPending()}
                      id="confirmPassword"
                      maxLength={auth.emailAndPassword.maxPasswordLength}
                      minLength={auth.emailAndPassword.minPasswordLength}
                      name="confirmPassword"
                      onInput={(event) => {
                        setConfirmPassword(event.currentTarget.value)
                        setPasswordFieldError("confirmPassword")
                      }}
                      onInvalid={(event) => {
                        event.preventDefault()
                        setPasswordFieldError(
                          "confirmPassword",
                          event.currentTarget.validationMessage
                        )
                      }}
                      placeholder={
                        auth.localization.auth.confirmPasswordPlaceholder
                      }
                      required
                      type={isConfirmPasswordVisible() ? "text" : "password"}
                      value={confirmPassword()}
                    />
                    <InputGroupAddon align="inline-end">
                      <InputGroupButton
                        aria-label={
                          isConfirmPasswordVisible()
                            ? auth.localization.auth.hidePassword
                            : auth.localization.auth.showPassword
                        }
                        disabled={isPasswordPending()}
                        onClick={() =>
                          setIsConfirmPasswordVisible((visible) => !visible)
                        }
                        size="icon-sm"
                        title={
                          isConfirmPasswordVisible()
                            ? auth.localization.auth.hidePassword
                            : auth.localization.auth.showPassword
                        }
                        type="button"
                      >
                        {isConfirmPasswordVisible() ? (
                          <EyeOff aria-hidden class="size-4" />
                        ) : (
                          <Eye aria-hidden class="size-4" />
                        )}
                      </InputGroupButton>
                    </InputGroupAddon>
                  </InputGroup>
                </Show>
                <Show when={fieldErrors().confirmPassword}>
                  {(message) => (
                    <p class="text-destructive text-sm" role="alert">
                      {message()}
                    </p>
                  )}
                </Show>
              </div>
            </Show>
          </CardContent>

          <CardFooter>
            <Button
              disabled={isPasswordPending() || !session.data}
              size="sm"
              type="submit"
            >
              {changePassword.isPending
                ? `${auth.localization.settings.updatePassword}…`
                : auth.localization.settings.updatePassword}
            </Button>
          </CardFooter>
        </Card>
      </form>
    </div>
  )
}
