// packages/heroui/src/components/auth/settings/security/linked-accounts.tsx
import { useAuth, useListAccounts } from "@better-auth-ui/react"
import { Card, type CardProps, cn, Skeleton } from "@heroui/react"
import { LinkedAccount } from "./linked-account"

export type LinkedAccountsProps = {
  className?: string
  variant?: CardProps["variant"]
}

/**
 * Render a card showing linked social accounts and available social providers to link.
 *
 * Linked accounts (excluding the "credential" provider) are shown with an unlink control;
 * available providers are shown with a link control. Button states and labels reflect
 * ongoing link/unlink activity and use localization for provider-specific text.
 *
 * @returns A JSX element containing the linked accounts card
 */
export function LinkedAccounts({
  className,
  variant,
  ...props
}: LinkedAccountsProps & Omit<CardProps, "children">) {
  const {
    authClient,
    localization,
    multipleAccountsPerProvider,
    socialProviders
  } = useAuth()

  const { data: accounts, isPending } = useListAccounts(authClient)

  const linkedAccounts = accounts?.filter(
    (account) => account.providerId !== "credential"
  )

  const linkedProviderIds = new Set(linkedAccounts?.map((a) => a.providerId))

  const availableProviders =
    multipleAccountsPerProvider === false
      ? socialProviders?.filter((p) => !linkedProviderIds.has(p))
      : socialProviders

  const allRows = [
    ...(linkedAccounts?.map((account) => ({
      key: account.id,
      account,
      provider: account.providerId
    })) ?? []),
    ...(availableProviders?.map((provider) => ({
      key: provider,
      account: undefined,
      provider
    })) ?? [])
  ]

  return (
    <div>
      <h2 className={cn("text-sm font-semibold mb-3")}>
        {localization.settings.linkedAccounts}
      </h2>

      <Card className={cn(className)} variant={variant} {...props}>
        <Card.Content className="gap-0">
          {isPending
            ? socialProviders?.map((provider, index) => (
                <div key={provider}>
                  {index > 0 && (
                    <div className="border-b border-dashed -mx-4 my-4" />
                  )}
                  <AccountRowSkeleton />
                </div>
              ))
            : allRows.map((row, index) => (
                <div key={row.key}>
                  {index > 0 && (
                    <div className="border-b border-dashed -mx-4 my-4" />
                  )}

                  <LinkedAccount
                    account={row.account}
                    provider={row.provider}
                  />
                </div>
              ))}
        </Card.Content>
      </Card>
    </div>
  )
}

function AccountRowSkeleton() {
  return (
    <div className="flex items-center justify-between">
      <div className="flex items-center gap-3">
        <Skeleton className="size-10 rounded-xl" />

        <div className="flex flex-col gap-1">
          <Skeleton className="h-4 w-20 rounded-lg" />
          <Skeleton className="h-3 w-32 rounded-lg" />
        </div>
      </div>
    </div>
  )
}

// examples/start-solid-zaidan-example/src/components/auth/settings/security/linked-accounts.tsx
import { listAccountsOptions, useAuth, useSession } from "@better-auth-ui/solid"
import { createQuery } from "@tanstack/solid-query"
import { For, Show } from "solid-js"
import { shouldLoadLinkedAccounts } from "@/components/auth/settings/shared/helpers"
import type {
  LinkedAccount,
  LinkedProvider
} from "@/components/auth/settings/shared/types"
import { Card, CardContent } from "@/components/ui/card"
import { Separator } from "@/components/ui/separator"
import { cn } from "@/lib/utils"
import { LinkedAccountRow, LinkedAccountRowSkeleton } from "./linked-account"

export type LinkedAccountsSettingsProps = {
  class?: string
}

export function LinkedAccountsSettings(
  props: LinkedAccountsSettingsProps = {}
) {
  const auth = useAuth()
  const session = useSession(auth.authClient)
  const userId = () => session.data?.user.id
  const linkedAccounts = createQuery(() => ({
    ...listAccountsOptions(auth.authClient, userId()),
    enabled: shouldLoadLinkedAccounts({
      isSsr: import.meta.env.SSR,
      userId: userId()
    })
  }))
  const socialProviders = () => auth.socialProviders ?? []
  const linkedSocialAccounts = () =>
    ((linkedAccounts.data ?? []) as LinkedAccount[]).filter(
      (account) => account.providerId !== "credential"
    )
  const availableProviders = () => {
    if (auth.multipleAccountsPerProvider !== false) return socialProviders()

    const linkedProviderIds = new Set(
      linkedSocialAccounts().map((account) => account.providerId)
    )

    return socialProviders().filter(
      (provider) => !linkedProviderIds.has(provider)
    )
  }
  const accountRows = () => {
    const linked = linkedSocialAccounts().map((account: LinkedAccount) => ({
      account,
      key: account.id,
      provider: account.providerId as LinkedProvider
    }))

    return [
      ...linked,
      ...availableProviders().map((provider) => ({
        account: undefined,
        key: provider,
        provider: provider as LinkedProvider
      }))
    ]
  }

  return (
    <div class={cn(props.class)}>
      <h2 class="mb-3 text-sm font-semibold">
        {auth.localization.settings.linkedAccounts}
      </h2>

      <Card class="z-card-padding-none">
        <CardContent class="z-card-content-padding-none">
          <Show
            fallback={
              <For each={socialProviders()}>
                {(_, index) => (
                  <>
                    <Show when={index() > 0}>
                      <Separator />
                    </Show>
                    <div class="p-4">
                      <LinkedAccountRowSkeleton />
                    </div>
                  </>
                )}
              </For>
            }
            when={!linkedAccounts.isPending}
          >
            <For each={accountRows()}>
              {(row, index) => (
                <>
                  <Show when={index() > 0}>
                    <Separator />
                  </Show>
                  <div class="p-4">
                    <LinkedAccountRow
                      account={row.account}
                      provider={row.provider}
                      userId={userId()}
                    />
                  </div>
                </>
              )}
            </For>
          </Show>
        </CardContent>
      </Card>
    </div>
  )
}
