// packages/heroui/src/components/auth/username/username-field.tsx
import {
  type UsernameAuthClient,
  useAuth,
  useAuthPlugin,
  useIsUsernameAvailable
} from "@better-auth-ui/react"
import { Check, Xmark } from "@gravity-ui/icons"
import {
  FieldError,
  InputGroup,
  Label,
  Spinner,
  TextField
} from "@heroui/react"
import { useDebouncer } from "@tanstack/react-pacer"
import { useState } from "react"
import { usernamePlugin } from "../../../lib/auth/username-plugin"
import type { AdditionalFieldProps } from "../additional-field"

/**
 * Renderer for the `username` additional field. Owns availability checking,
 * length limits, and visual indicators. `FieldError` automatically surfaces
 * native validation messages. Availability feedback is shown via the icon and
 * aria-label without affecting the field's invalid state.
 */
export function UsernameField({
  name,
  field,
  isPending,
  variant
}: AdditionalFieldProps) {
  const { authClient } = useAuth()
  const {
    localization,
    minUsernameLength,
    maxUsernameLength,
    isUsernameAvailable: checkAvailability
  } = useAuthPlugin(usernamePlugin)

  const currentUsername = String(field.defaultValue ?? "")
  const [value, setValue] = useState(currentUsername)

  const {
    mutate: requestAvailability,
    data: availability,
    error: availabilityError,
    reset: resetAvailability
  } = useIsUsernameAvailable(authClient as UsernameAuthClient, {
    // Bypass global error toast
    onError: () => {}
  })

  const debouncer = useDebouncer(
    (next: string) => {
      const trimmed = next.trim()
      // Skip blank input and the user's own current username (profile view).
      if (!trimmed || trimmed === currentUsername) {
        resetAvailability()
        return
      }

      requestAvailability({ username: trimmed })
    },
    { wait: 500 }
  )

  function handleChange(next: string) {
    setValue(next)
    resetAvailability()

    if (checkAvailability) {
      debouncer.maybeExecute(next)
    }
  }

  const isCheckingAvailability =
    !!checkAvailability && !!value.trim() && value.trim() !== currentUsername

  return (
    <TextField
      name={name}
      type="text"
      autoComplete="username"
      minLength={minUsernameLength}
      maxLength={maxUsernameLength}
      isDisabled={isPending}
      isReadOnly={field.readOnly}
      value={value}
      onChange={handleChange}
    >
      <Label>{field.label}</Label>

      <InputGroup variant={variant === "transparent" ? "primary" : "secondary"}>
        <InputGroup.Input
          placeholder={field.placeholder}
          required={field.required}
        />

        {isCheckingAvailability && (
          <InputGroup.Suffix
            aria-label={
              availability?.available
                ? localization.usernameAvailable
                : availability?.available === false
                  ? localization.usernameTaken
                  : undefined
            }
            className="px-2"
          >
            {availability?.available ? (
              <Check className="text-success" />
            ) : availabilityError || availability?.available === false ? (
              <Xmark className="text-danger" />
            ) : (
              <Spinner size="sm" color="current" />
            )}
          </InputGroup.Suffix>
        )}
      </InputGroup>

      <FieldError />
    </TextField>
  )
}

// examples/start-solid-zaidan-example/src/components/auth/username/username-field.tsx
import {
  isUsernameAvailableOptions,
  type UsernameAuthClient,
  useAuth
} from "@better-auth-ui/solid"
import { createMutation } from "@tanstack/solid-query"
import { Check, X } from "lucide-solid"
import { createSignal, Show } from "solid-js"
import type { AdditionalFieldProps } from "@/components/auth/additional-field"
import {
  InputGroup,
  InputGroupAddon,
  InputGroupInput
} from "@/components/ui/input-group"
import { Label } from "@/components/ui/label"
import { Spinner } from "@/components/ui/spinner"

export function UsernameField(props: AdditionalFieldProps) {
  const auth = useAuth()
  const usernamePlugin = () =>
    auth.plugins.find((plugin) => plugin.id === "username") as
      | {
          isUsernameAvailable?: boolean
          localization?: {
            usernameAvailable?: string
            usernameTaken?: string
          }
          usernamePrefix?: string
          maxUsernameLength?: number
          minUsernameLength?: number
        }
      | undefined
  const currentUsername = String(props.field.defaultValue ?? "")
  const [value, setValue] = createSignal(currentUsername)
  const [error, setError] = createSignal<string>()
  const availability = createMutation(() => ({
    ...isUsernameAvailableOptions(auth.authClient as UsernameAuthClient),
    onError: () => undefined
  }))
  const shouldCheckAvailability = () =>
    Boolean(usernamePlugin()?.isUsernameAvailable) &&
    Boolean(value().trim()) &&
    value().trim() !== currentUsername

  const handleInput = (next: string) => {
    setValue(next)
    setError(undefined)

    if (shouldCheckAvailability()) {
      availability.mutate({ username: next.trim() })
    } else {
      availability.reset()
    }
  }

  return (
    <div class="grid gap-2">
      <Label for={props.name}>{props.field.label}</Label>
      <InputGroup>
        <InputGroupInput
          aria-invalid={Boolean(error())}
          autocomplete="username"
          disabled={props.isPending}
          id={props.name}
          maxLength={usernamePlugin()?.maxUsernameLength}
          minLength={usernamePlugin()?.minUsernameLength}
          name={props.name}
          onInput={(event) => handleInput(event.currentTarget.value)}
          onInvalid={(event) => {
            event.preventDefault()
            setError(event.currentTarget.validationMessage)
          }}
          placeholder={props.field.placeholder}
          readonly={props.field.readOnly}
          required={props.field.required}
          type="text"
          value={value()}
        />
        <Show when={usernamePlugin()?.usernamePrefix}>
          {(usernamePrefix) => (
            <InputGroupAddon align="inline-start">
              {usernamePrefix()}
            </InputGroupAddon>
          )}
        </Show>
        <Show when={shouldCheckAvailability()}>
          <InputGroupAddon
            align="inline-end"
            aria-label={
              availability.data?.available
                ? usernamePlugin()?.localization?.usernameAvailable
                : availability.data?.available === false
                  ? usernamePlugin()?.localization?.usernameTaken
                  : undefined
            }
            role="status"
          >
            {availability.data?.available ? (
              <Check class="size-4" />
            ) : availability.error || availability.data?.available === false ? (
              <X class="size-4 text-destructive" />
            ) : (
              <Spinner />
            )}
          </InputGroupAddon>
        </Show>
      </InputGroup>
      <Show when={error()}>{(message) => <p role="alert">{message()}</p>}</Show>
    </div>
  )
}
