// apps/docs/src/demos/shadcn/organization/organization-demo-wrapper.tsx
import type { ReactNode } from "react"

import { AuthProvider } from "@/components/auth/auth-provider"
import { organizationPlugin } from "@/lib/auth/organization-plugin"
import { authClient } from "@/lib/auth-client"

export function OrganizationDemoWrapper({ children }: { children: ReactNode }) {
  return (
    <AuthProvider
      authClient={authClient}
      navigate={() => {}}
      plugins={[organizationPlugin()]}
      Link={(props) => (
        // biome-ignore lint/a11y/useValidAnchor: ignore
        <a {...props} href={undefined} />
      )}
    >
      <div className="w-full">{children}</div>
    </AuthProvider>
  )
}

// examples/start-solid-zaidan-example/src/demos/organization/organization-demo-wrapper.tsx
import type { JSX } from "solid-js"
import { AuthProvider } from "@/components/auth/auth-provider"
import { organizationPlugin } from "@/lib/auth/organization-plugin"
import { authClient } from "@/lib/auth-client"

export function OrganizationDemoWrapper(props: { children: JSX.Element }) {
  return (
    <AuthProvider
      authClient={authClient}
      navigate={() => {}}
      plugins={[organizationPlugin({ slug: "acme" })]}
    >
      <div class="w-full">{props.children}</div>
    </AuthProvider>
  )
}
