// examples/start-solid-zaidan-example/src/components/auth/settings/security/active-session.tsx
import type { ListSession } from "@better-auth-ui/solid"
import { useAuth } from "@better-auth-ui/solid"
import Bowser from "bowser"
import { LogOut, Monitor, Smartphone, X } from "lucide-solid"
import { createMemo, Show } from "solid-js"
import { timeAgo } from "@/components/auth/settings/shared/helpers"
import { Button } from "@/components/ui/button"
import { Skeleton } from "@/components/ui/skeleton"
import { Spinner } from "@/components/ui/spinner"

export function ActiveSessionRow(props: {
  activeSession: ListSession
  displayName: string
  isCurrentSession: boolean
  isRevoking: boolean
  onRevoke: (activeSession: ListSession) => void
  onSignOut: () => void
}) {
  const auth = useAuth()
  const userAgent = createMemo(() =>
    Bowser.parse(props.activeSession.userAgent || "")
  )
  const isMobile = () =>
    userAgent().platform.type === "mobile" ||
    userAgent().platform.type === "tablet"
  const browserAndOs = () => {
    const browser = userAgent().browser.name || "Unknown Browser"
    const os = userAgent().os.name

    return os ? `${browser}, ${os}` : browser
  }

  return (
    <div class="flex items-center justify-between gap-3">
      <div class="flex size-10 shrink-0 items-center justify-center rounded-md bg-muted">
        <Show fallback={<Monitor class="size-4.5" />} when={isMobile()}>
          <Smartphone class="size-4.5" />
        </Show>
      </div>

      <div class="flex min-w-0 flex-col">
        <span class="truncate font-medium text-sm">{browserAndOs()}</span>

        <Show
          fallback={
            <Show when={props.activeSession.createdAt}>
              <span class="truncate text-muted-foreground text-xs capitalize">
                {timeAgo(props.activeSession.createdAt)}
              </span>
            </Show>
          }
          when={props.isCurrentSession}
        >
          <span class="w-fit rounded-full bg-primary/10 px-2 py-0.5 font-medium text-primary text-xs">
            {auth.localization.settings.currentSession}
          </span>
        </Show>
      </div>

      <Button
        aria-label={
          props.isCurrentSession
            ? auth.localization.auth.signOut
            : auth.localization.settings.revokeSession
        }
        class="ml-auto shrink-0"
        disabled={props.isRevoking}
        onClick={() =>
          props.isCurrentSession
            ? props.onSignOut()
            : props.onRevoke(props.activeSession)
        }
        size="sm"
        type="button"
        variant="outline"
      >
        <Show
          fallback={
            <Show fallback={<X />} when={props.isCurrentSession}>
              <LogOut />
            </Show>
          }
          when={props.isRevoking}
        >
          <Spinner />
        </Show>
        {props.isCurrentSession
          ? auth.localization.auth.signOut
          : auth.localization.settings.revoke}
      </Button>
    </div>
  )
}

export function ActiveSessionRowSkeleton() {
  return (
    <div class="flex items-center gap-3">
      <Skeleton class="size-10 rounded-md" />
      <div class="flex flex-col gap-1">
        <Skeleton class="h-4 w-20" />
        <Skeleton class="h-3 w-32" />
      </div>
    </div>
  )
}

// packages/shadcn/src/components/settings/security/active-session.tsx
"use client"

import { useAuth, useRevokeSession, useSession } from "@better-auth-ui/react"
import type { Session } from "better-auth"
import Bowser from "bowser"
import { LogOut, Monitor, Smartphone } from "lucide-react"
import { toast } from "sonner"

import { Button } from "@/components/ui/button"
import { Item } from "@/components/ui/item"
import { Spinner } from "@/components/ui/spinner"

export type ActiveSessionProps = {
  session: Session
}

/**
 * Render a single active session card with device info and revoke control.
 *
 * Shows the session's browser, OS, IP address, and creation time. The current session is marked
 * and navigates to sign-out on click, while other sessions can be revoked individually.
 *
 * @param session - The session object containing id, token, userAgent, ipAddress, and createdAt
 * @returns A JSX element containing the active session card
 */
export function ActiveSession({ session }: ActiveSessionProps) {
  const { basePaths, localization, viewPaths, navigate } = useAuth()
  const { data: sessionData } = useSession()

  const { mutate: revokeSession, isPending: isRevoking } = useRevokeSession({
    onError: (error) => toast.error(error.error?.message || error.message),
    onSuccess: () => toast.success(localization.settings.revokeSessionSuccess)
  })

  const isCurrentSession = session.token === sessionData?.session.token
  const ua = Bowser.parse(session.userAgent || "")
  const isMobile =
    ua.platform.type === "mobile" || ua.platform.type === "tablet"

  return (
    <Item className="p-3 gap-3" variant="outline">
      <div className="flex size-10 items-center justify-center rounded-md bg-muted">
        {isMobile ? (
          <Smartphone className="size-5" />
        ) : (
          <Monitor className="size-5" />
        )}
      </div>

      <div className="flex flex-col">
        <div className="flex items-center gap-1.5">
          <span className="text-sm font-medium truncate">
            {ua.browser.name || "Unknown Browser"}
            {ua.os.name ? `, ${ua.os.name}` : ""}
          </span>

          {isCurrentSession && (
            <span className="rounded-full bg-primary/10 px-2 py-0.5 text-xs font-medium text-primary">
              {localization.settings.currentSession}
            </span>
          )}
        </div>

        <div className="flex items-center gap-1.5 text-xs text-muted-foreground">
          {session.ipAddress && <span>{session.ipAddress}</span>}

          {session.createdAt && (
            <>
              {session.ipAddress && <span>•</span>}
              <span>
                {session.createdAt.toLocaleString([], {
                  dateStyle: "short",
                  timeStyle: "short"
                })}
              </span>
            </>
          )}
        </div>
      </div>

      <Button
        className="ml-auto"
        variant="ghost"
        size="icon"
        onClick={() =>
          isCurrentSession
            ? navigate({
                to: `${basePaths.auth}/${viewPaths.auth.signOut}`
              })
            : revokeSession({ token: session.token })
        }
        disabled={isRevoking}
        aria-label={localization.settings.revokeSession}
      >
        {isRevoking ? (
          <Spinner className="size-4" />
        ) : (
          <LogOut className="size-4" />
        )}
      </Button>
    </Item>
  )
}
