// apps/docs/src/components/settings/security/delete-user.tsx
"use client"

import { useAuth, useDeleteUser, useListAccounts } from "@better-auth-ui/react"
import { TriangleAlert } from "lucide-react"
import { type SyntheticEvent, useState } from "react"
import { toast } from "sonner"
import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogMedia,
  AlertDialogTitle,
  AlertDialogTrigger
} from "@/components/ui/alert-dialog"
import { Button } from "@/components/ui/button"
import { Card, CardContent } from "@/components/ui/card"
import { Field, FieldError } from "@/components/ui/field"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { Spinner } from "@/components/ui/spinner"
import { cn } from "@/lib/utils"

export type DeleteUserProps = {
  className?: string
}

/**
 * Danger-zone card to delete the authenticated account, with a confirmation dialog and toasts.
 */
export function DeleteUser({ className }: DeleteUserProps) {
  const {
    authClient,
    basePaths,
    deleteUser: deleteUserConfig,
    localization,
    viewPaths,
    navigate
  } = useAuth()

  const { data: accounts } = useListAccounts(authClient)

  const [confirmOpen, setConfirmOpen] = useState(false)
  const [password, setPassword] = useState("")

  const hasCredentialAccount = accounts?.some(
    (account) => account.providerId === "credential"
  )
  const needsPassword =
    !deleteUserConfig?.sendDeleteAccountVerification && hasCredentialAccount

  const { mutate: deleteUser, isPending } = useDeleteUser(authClient)

  const handleDialogOpenChange = (open: boolean) => {
    setConfirmOpen(open)
    setPassword("")
  }

  const handleSubmit = async (e: SyntheticEvent<HTMLFormElement>) => {
    e.preventDefault()

    const params = {
      ...(needsPassword ? { password } : {})
    }

    deleteUser(params, {
      onSuccess: () => {
        setConfirmOpen(false)
        setPassword("")

        if (deleteUserConfig?.sendDeleteAccountVerification) {
          toast.success(localization.settings.deleteUserVerificationSent)
        } else {
          toast.success(localization.settings.deleteUserSuccess)
          navigate({
            to: `${basePaths.auth}/${viewPaths.auth.signIn}`,
            replace: true
          })
        }
      }
    })
  }

  return (
    <Card className={cn("border-destructive", className)}>
      <CardContent className="flex flex-col gap-6 sm:flex-row sm:items-center sm:justify-between">
        <div>
          <p className="text-sm font-medium leading-tight">
            {localization.settings.deleteUser}
          </p>

          <p className="text-muted-foreground text-xs mt-0.5">
            {localization.settings.deleteUserDescription}
          </p>
        </div>

        <AlertDialog open={confirmOpen} onOpenChange={handleDialogOpenChange}>
          <AlertDialogTrigger asChild>
            <Button variant="destructive" size="sm" disabled={!accounts}>
              {localization.settings.deleteUser}
            </Button>
          </AlertDialogTrigger>

          <AlertDialogContent>
            <form onSubmit={handleSubmit} className="flex flex-col gap-6">
              <AlertDialogHeader>
                <AlertDialogMedia className="bg-destructive/10 text-destructive dark:bg-destructive/20 dark:text-destructive">
                  <TriangleAlert />
                </AlertDialogMedia>

                <AlertDialogTitle>
                  {localization.settings.deleteUser}
                </AlertDialogTitle>

                <AlertDialogDescription>
                  {localization.settings.deleteUserDescription}
                </AlertDialogDescription>
              </AlertDialogHeader>

              {needsPassword && (
                <Field>
                  <Label htmlFor="delete-password">
                    {localization.auth.password}
                  </Label>

                  <Input
                    id="delete-password"
                    name="password"
                    type="password"
                    autoComplete="current-password"
                    placeholder={localization.auth.passwordPlaceholder}
                    value={password}
                    onChange={(e) => setPassword(e.target.value)}
                    disabled={isPending}
                    required
                  />

                  <FieldError />
                </Field>
              )}

              <AlertDialogFooter>
                <AlertDialogCancel>
                  {localization.settings.cancel}
                </AlertDialogCancel>

                <AlertDialogAction variant="destructive">
                  {isPending && <Spinner />}

                  {localization.settings.deleteUser}
                </AlertDialogAction>
              </AlertDialogFooter>
            </form>
          </AlertDialogContent>
        </AlertDialog>
      </CardContent>
    </Card>
  )
}

// examples/start-solid-zaidan-example/src/components/auth/delete-user/delete-user.tsx
import { authQueryKeys } from "@better-auth-ui/core"
import { deleteUserLocalization } from "@better-auth-ui/core/plugins"
import {
  deleteUserOptions,
  listAccountsOptions,
  useAuth,
  useSession
} from "@better-auth-ui/solid"
import {
  createMutation,
  createQuery,
  useQueryClient
} from "@tanstack/solid-query"
import { TriangleAlert } from "lucide-solid"
import { createSignal, Show } from "solid-js"
import { toast } from "solid-sonner"
import { shouldLoadAccounts } from "@/components/auth/settings/shared/helpers"
import type { DeleteUserPluginConfig } from "@/components/auth/settings/shared/types"
import { Button } from "@/components/ui/button"
import { Card, CardContent } from "@/components/ui/card"
import {
  Dialog,
  DialogClose,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
  DialogTrigger
} from "@/components/ui/dialog"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { cn } from "@/lib/utils"

const defaultDeleteUserLabel = "Delete user"

export type DeleteUserProps = {
  class?: string
}

export function DeleteUser(props: DeleteUserProps = {}) {
  const auth = useAuth()
  const session = useSession(auth.authClient)
  const queryClient = useQueryClient()
  const userId = () => session.data?.user.id
  const [confirmOpen, setConfirmOpen] = createSignal(false)
  const [password, setPassword] = createSignal("")
  const deleteUserPluginConfig = () =>
    auth.plugins.find((plugin) => plugin.id === "deleteUser") as
      | DeleteUserPluginConfig
      | undefined
  const deleteUserLabels = () => {
    const pluginLocalization = deleteUserPluginConfig()?.localization

    return {
      deleteUser:
        pluginLocalization?.deleteAccount ??
        deleteUserLocalization.deleteAccount ??
        defaultDeleteUserLabel,
      deleteUserDescription:
        pluginLocalization?.deleteAccountDescription ??
        deleteUserLocalization.deleteAccountDescription,
      deleteUserSuccess:
        pluginLocalization?.deleteUserSuccess ??
        deleteUserLocalization.deleteUserSuccess,
      deleteUserVerificationSent:
        pluginLocalization?.deleteUserVerificationSent ??
        deleteUserLocalization.deleteUserVerificationSent
    }
  }
  const sendDeleteAccountVerification = () =>
    Boolean(deleteUserPluginConfig()?.sendDeleteAccountVerification)
  const accounts = createQuery(() => ({
    ...listAccountsOptions(auth.authClient, userId()),
    enabled: shouldLoadAccounts({
      isSsr: import.meta.env.SSR,
      userId: userId()
    })
  }))
  const hasCredentialAccount = () =>
    accounts.data?.some(
      (account: { providerId?: string }) => account.providerId === "credential"
    )
  const needsPassword = () =>
    !sendDeleteAccountVerification() && Boolean(hasCredentialAccount())
  const deleteUser = createMutation(() => ({
    ...deleteUserOptions(auth.authClient),
    onSuccess: () => {
      setConfirmOpen(false)
      setPassword("")

      if (sendDeleteAccountVerification()) {
        toast.success(deleteUserLabels().deleteUserVerificationSent)
        return
      }

      toast.success(deleteUserLabels().deleteUserSuccess)
      queryClient.removeQueries({ queryKey: authQueryKeys.all })
      auth.navigate({
        replace: true,
        to: `${auth.basePaths.auth}/${auth.viewPaths.auth.signIn}`
      })
    }
  }))

  const handleDialogOpenChange = (open: boolean) => {
    setConfirmOpen(open)
    setPassword("")
  }

  const submitDeleteUser = (event: SubmitEvent) => {
    event.preventDefault()

    deleteUser.mutate(
      (needsPassword() ? { password: password() } : {}) as Parameters<
        typeof deleteUser.mutate
      >[0]
    )
  }

  return (
    <Card class={cn("border-destructive p-0", props.class)}>
      <CardContent class="flex flex-col gap-6 p-4 sm:flex-row sm:items-center sm:justify-between">
        <div>
          <p class="font-medium text-sm leading-tight">
            {deleteUserLabels().deleteUser}
          </p>
          <p class="mt-0.5 text-muted-foreground text-xs">
            {deleteUserLabels().deleteUserDescription}
          </p>
        </div>

        <Dialog open={confirmOpen()} onOpenChange={handleDialogOpenChange}>
          <DialogTrigger
            as={Button}
            disabled={!accounts.data || accounts.isPending}
            size="sm"
            variant="destructive"
          >
            {deleteUserLabels().deleteUser}
          </DialogTrigger>

          <DialogContent>
            <form class="flex flex-col gap-6" onSubmit={submitDeleteUser}>
              <DialogHeader>
                <div class="flex size-10 items-center justify-center rounded-md bg-destructive/10 text-destructive dark:bg-destructive/20">
                  <TriangleAlert class="size-4.5" />
                </div>
                <DialogTitle>{deleteUserLabels().deleteUser}</DialogTitle>
                <DialogDescription>
                  {deleteUserLabels().deleteUserDescription}
                </DialogDescription>
              </DialogHeader>

              <Show when={needsPassword()}>
                <div class="grid gap-2">
                  <Label for="delete-password">
                    {auth.localization.auth.password}
                  </Label>
                  <Input
                    autocomplete="current-password"
                    disabled={deleteUser.isPending}
                    id="delete-password"
                    name="password"
                    onInput={(event) => setPassword(event.currentTarget.value)}
                    placeholder={auth.localization.auth.passwordPlaceholder}
                    required
                    type="password"
                    value={password()}
                  />
                </div>
              </Show>

              <DialogFooter>
                <DialogClose
                  as={Button}
                  disabled={deleteUser.isPending}
                  type="button"
                  variant="outline"
                >
                  {auth.localization.settings.cancel}
                </DialogClose>
                <Button
                  disabled={deleteUser.isPending}
                  type="submit"
                  variant="destructive"
                >
                  {deleteUser.isPending
                    ? `${deleteUserLabels().deleteUser}…`
                    : deleteUserLabels().deleteUser}
                </Button>
              </DialogFooter>
            </form>
          </DialogContent>
        </Dialog>
      </CardContent>
    </Card>
  )
}
