// packages/heroui/src/components/auth/delete-user/delete-account.tsx
import { authQueryKeys } from "@better-auth-ui/core"
import {
  useAuth,
  useAuthPlugin,
  useDeleteUser,
  useListAccounts
} from "@better-auth-ui/react"
import { TriangleExclamation } from "@gravity-ui/icons"
import {
  AlertDialog,
  Button,
  Card,
  type CardProps,
  FieldError,
  Form,
  Input,
  Label,
  Spinner,
  TextField,
  toast
} from "@heroui/react"
import { useQueryClient } from "@tanstack/react-query"
import { type SyntheticEvent, useState } from "react"

import { deleteUserPlugin } from "../../../lib/auth/delete-user-plugin"

export type DeleteAccountProps = {
  className?: string
  variant?: CardProps["variant"]
}

/**
 * Danger-zone card to delete the authenticated account, with a confirmation dialog and toasts.
 */
export function DeleteAccount({
  className,
  variant,
  ...props
}: DeleteAccountProps & Omit<CardProps, "children">) {
  const { authClient, basePaths, localization, navigate, viewPaths } = useAuth()

  const {
    localization: deleteUserLocalization,
    sendDeleteAccountVerification
  } = useAuthPlugin(deleteUserPlugin)

  const { data: accounts } = useListAccounts(authClient)

  const queryClient = useQueryClient()

  const [confirmOpen, setConfirmOpen] = useState(false)
  const [password, setPassword] = useState("")

  const hasCredentialAccount = accounts?.some(
    (account) => account.providerId === "credential"
  )
  const needsPassword = !sendDeleteAccountVerification && hasCredentialAccount

  const { mutate: deleteUser, isPending } = useDeleteUser(authClient)

  const handleDialogOpenChange = (open: boolean) => {
    setConfirmOpen(open)
    setPassword("")
  }

  const handleSubmit = async (e: SyntheticEvent<HTMLFormElement>) => {
    e.preventDefault()

    const params = {
      ...(needsPassword ? { password } : {})
    }

    deleteUser(params, {
      onSuccess: () => {
        setConfirmOpen(false)
        setPassword("")

        if (sendDeleteAccountVerification) {
          toast.success(deleteUserLocalization.deleteUserVerificationSent)
        } else {
          toast.success(deleteUserLocalization.deleteUserSuccess)
          queryClient.removeQueries({ queryKey: authQueryKeys.all })
          navigate({
            to: `${basePaths.auth}/${viewPaths.auth.signIn}`,
            replace: true
          })
        }
      }
    })
  }

  return (
    <Card className={className} variant={variant} {...props}>
      <Card.Content className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between">
        <div>
          <p className="text-sm font-medium leading-tight">
            {deleteUserLocalization.deleteAccount}
          </p>

          <p className="text-muted text-xs mt-0.5">
            {deleteUserLocalization.deleteAccountDescription}
          </p>
        </div>

        <AlertDialog>
          <Button
            isDisabled={!accounts}
            size="sm"
            variant="danger-soft"
            onPress={() => setConfirmOpen(true)}
          >
            {deleteUserLocalization.deleteAccount}
          </Button>

          <AlertDialog.Backdrop
            isOpen={confirmOpen}
            onOpenChange={handleDialogOpenChange}
          >
            <AlertDialog.Container>
              <AlertDialog.Dialog>
                <Form onSubmit={handleSubmit}>
                  <AlertDialog.CloseTrigger />

                  <AlertDialog.Header>
                    <AlertDialog.Icon status="danger">
                      <TriangleExclamation />
                    </AlertDialog.Icon>

                    <AlertDialog.Heading>
                      {deleteUserLocalization.deleteAccount}
                    </AlertDialog.Heading>
                  </AlertDialog.Header>

                  <AlertDialog.Body className="overflow-visible">
                    <p className="text-muted text-sm">
                      {deleteUserLocalization.deleteAccountDescription}
                    </p>

                    {needsPassword && (
                      <TextField
                        className="mt-4"
                        name="password"
                        type="password"
                        isDisabled={isPending}
                        value={password}
                        onChange={setPassword}
                      >
                        <Label>{localization.auth.password}</Label>

                        <Input
                          autoComplete="current-password"
                          placeholder={localization.auth.passwordPlaceholder}
                          required
                          variant="secondary"
                        />

                        <FieldError />
                      </TextField>
                    )}
                  </AlertDialog.Body>

                  <AlertDialog.Footer>
                    <Button
                      slot="close"
                      variant="tertiary"
                      isDisabled={isPending}
                    >
                      {localization.settings.cancel}
                    </Button>

                    <Button
                      type="submit"
                      variant="danger"
                      isPending={isPending}
                    >
                      {isPending && <Spinner color="current" size="sm" />}

                      {deleteUserLocalization.deleteAccount}
                    </Button>
                  </AlertDialog.Footer>
                </Form>
              </AlertDialog.Dialog>
            </AlertDialog.Container>
          </AlertDialog.Backdrop>
        </AlertDialog>
      </Card.Content>
    </Card>
  )
}

// examples/start-solid-zaidan-example/src/components/auth/delete-user/delete-account.tsx
import { authQueryKeys } from "@better-auth-ui/core"
import { deleteUserLocalization } from "@better-auth-ui/core/plugins"
import {
  deleteUserOptions,
  listAccountsOptions,
  useAuth,
  useSession
} from "@better-auth-ui/solid"
import {
  createMutation,
  createQuery,
  useQueryClient
} from "@tanstack/solid-query"
import { TriangleAlert } from "lucide-solid"
import { createSignal, Show } from "solid-js"
import { toast } from "solid-sonner"
import { shouldLoadAccounts } from "@/components/auth/settings/shared/helpers"
import type { DeleteUserPluginConfig } from "@/components/auth/settings/shared/types"
import { Button } from "@/components/ui/button"
import { Card, CardContent } from "@/components/ui/card"
import {
  Dialog,
  DialogClose,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
  DialogTrigger
} from "@/components/ui/dialog"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { cn } from "@/lib/utils"

const defaultDeleteAccountLabel = "Delete account"

export type DeleteAccountProps = {
  class?: string
}

export function DeleteAccount(props: DeleteAccountProps = {}) {
  const auth = useAuth()
  const session = useSession(auth.authClient)
  const queryClient = useQueryClient()
  const userId = () => session.data?.user.id
  const [confirmOpen, setConfirmOpen] = createSignal(false)
  const [password, setPassword] = createSignal("")
  const deleteUserPluginConfig = () =>
    auth.plugins.find((plugin) => plugin.id === "deleteUser") as
      | DeleteUserPluginConfig
      | undefined
  const deleteUserLabels = () => {
    const pluginLocalization = deleteUserPluginConfig()?.localization

    return {
      deleteUser:
        pluginLocalization?.deleteAccount ??
        deleteUserLocalization.deleteAccount ??
        defaultDeleteAccountLabel,
      deleteUserDescription:
        pluginLocalization?.deleteAccountDescription ??
        deleteUserLocalization.deleteAccountDescription,
      deleteUserSuccess:
        pluginLocalization?.deleteUserSuccess ??
        deleteUserLocalization.deleteUserSuccess,
      deleteUserVerificationSent:
        pluginLocalization?.deleteUserVerificationSent ??
        deleteUserLocalization.deleteUserVerificationSent
    }
  }
  const sendDeleteAccountVerification = () =>
    Boolean(deleteUserPluginConfig()?.sendDeleteAccountVerification)
  const accounts = createQuery(() => ({
    ...listAccountsOptions(auth.authClient, userId()),
    enabled: shouldLoadAccounts({
      isSsr: import.meta.env.SSR,
      userId: userId()
    })
  }))
  const hasCredentialAccount = () =>
    accounts.data?.some(
      (account: { providerId?: string }) => account.providerId === "credential"
    )
  const needsPassword = () =>
    !sendDeleteAccountVerification() && Boolean(hasCredentialAccount())
  const deleteUser = createMutation(() => ({
    ...deleteUserOptions(auth.authClient),
    onSuccess: () => {
      setConfirmOpen(false)
      setPassword("")

      if (sendDeleteAccountVerification()) {
        toast.success(deleteUserLabels().deleteUserVerificationSent)
        return
      }

      toast.success(deleteUserLabels().deleteUserSuccess)
      queryClient.removeQueries({ queryKey: authQueryKeys.all })
      auth.navigate({
        replace: true,
        to: `${auth.basePaths.auth}/${auth.viewPaths.auth.signIn}`
      })
    }
  }))

  const handleDialogOpenChange = (open: boolean) => {
    setConfirmOpen(open)
    setPassword("")
  }

  const submitDeleteUser = (event: SubmitEvent) => {
    event.preventDefault()

    deleteUser.mutate(
      (needsPassword() ? { password: password() } : {}) as Parameters<
        typeof deleteUser.mutate
      >[0]
    )
  }

  return (
    <Card class={cn("border-destructive p-0", props.class)}>
      <CardContent class="flex flex-col gap-6 p-4 sm:flex-row sm:items-center sm:justify-between">
        <div>
          <p class="font-medium text-sm leading-tight">
            {deleteUserLabels().deleteUser}
          </p>
          <p class="mt-0.5 text-muted-foreground text-xs">
            {deleteUserLabels().deleteUserDescription}
          </p>
        </div>

        <Dialog open={confirmOpen()} onOpenChange={handleDialogOpenChange}>
          <DialogTrigger
            as={Button}
            disabled={!accounts.data || accounts.isPending}
            size="sm"
            variant="destructive"
          >
            {deleteUserLabels().deleteUser}
          </DialogTrigger>

          <DialogContent>
            <form class="flex flex-col gap-6" onSubmit={submitDeleteUser}>
              <DialogHeader>
                <div class="flex size-10 items-center justify-center rounded-md bg-destructive/10 text-destructive dark:bg-destructive/20">
                  <TriangleAlert class="size-4.5" />
                </div>
                <DialogTitle>{deleteUserLabels().deleteUser}</DialogTitle>
                <DialogDescription>
                  {deleteUserLabels().deleteUserDescription}
                </DialogDescription>
              </DialogHeader>

              <Show when={needsPassword()}>
                <div class="grid gap-2">
                  <Label for="delete-password">
                    {auth.localization.auth.password}
                  </Label>
                  <Input
                    autocomplete="current-password"
                    disabled={deleteUser.isPending}
                    id="delete-password"
                    name="password"
                    onInput={(event) => setPassword(event.currentTarget.value)}
                    placeholder={auth.localization.auth.passwordPlaceholder}
                    required
                    type="password"
                    value={password()}
                  />
                </div>
              </Show>

              <DialogFooter>
                <DialogClose
                  as={Button}
                  disabled={deleteUser.isPending}
                  type="button"
                  variant="outline"
                >
                  {auth.localization.settings.cancel}
                </DialogClose>
                <Button
                  disabled={deleteUser.isPending}
                  type="submit"
                  variant="destructive"
                >
                  {deleteUser.isPending
                    ? `${deleteUserLabels().deleteUser}…`
                    : deleteUserLabels().deleteUser}
                </Button>
              </DialogFooter>
            </form>
          </DialogContent>
        </Dialog>
      </CardContent>
    </Card>
  )
}
