// examples/start-solid-zaidan-example/src/components/auth/api-key/api-keys-empty.tsx
import { apiKeyLocalization } from "@better-auth-ui/core/plugins"
import { Key } from "lucide-solid"
import { Show } from "solid-js"
import { Button } from "@/components/ui/button"

export function ApiKeysEmpty(props: {
  hideCreate?: boolean
  onCreatePress: () => void
}) {
  return (
    <div class="flex flex-col items-center justify-center gap-4 p-6 text-center">
      <div class="flex size-10 items-center justify-center rounded-md bg-muted">
        <Key class="size-4.5" />
      </div>

      <div class="flex flex-col items-center justify-center gap-1">
        <p class="font-semibold text-sm">{apiKeyLocalization.noApiKeys}</p>
        <p class="text-muted-foreground text-xs">
          {apiKeyLocalization.apiKeysDescription}
        </p>
      </div>

      <Show when={!props.hideCreate}>
        <Button onClick={props.onCreatePress} size="sm" type="button">
          {apiKeyLocalization.createApiKey}
        </Button>
      </Show>
    </div>
  )
}

// packages/heroui/src/components/auth/api-key/api-keys-empty.tsx
import { useAuthPlugin } from "@better-auth-ui/react"
import { Key } from "@gravity-ui/icons"
import { Button } from "@heroui/react"

import { apiKeyPlugin } from "../../../lib/auth/api-key-plugin"

export type ApiKeysEmptyProps = {
  onCreatePress: () => void
}

export function ApiKeysEmpty({ onCreatePress }: ApiKeysEmptyProps) {
  const { localization: apiKeyLocalization } = useAuthPlugin(apiKeyPlugin)

  return (
    <div className="flex flex-col items-center justify-center gap-4">
      <div className="flex size-10 items-center justify-center rounded-xl bg-surface-secondary">
        <Key className="size-4.5" />
      </div>

      <div className="flex flex-col items-center justify-center gap-1 text-center">
        <p className="text-sm font-semibold">{apiKeyLocalization.noApiKeys}</p>

        <p className="text-muted text-xs">
          {apiKeyLocalization.apiKeysDescription}
        </p>
      </div>

      <Button size="sm" onPress={onCreatePress}>
        {apiKeyLocalization.createApiKey}
      </Button>
    </div>
  )
}
