// examples/start-solid-zaidan-example/src/components/auth/organization/create-organization-dialog.tsx
import type { OrganizationLocalization } from "@better-auth-ui/core/plugins"
import type { OrganizationAuthClient } from "@better-auth-ui/solid"
import { useAuth, useCreateOrganization } from "@better-auth-ui/solid"
import { BriefcaseBusiness, LoaderCircle } from "lucide-solid"
import { createEffect, createSignal } from "solid-js"
import { Button } from "@/components/ui/button"
import {
  Dialog,
  DialogClose,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle
} from "@/components/ui/dialog"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { organizationPlugin } from "@/lib/auth/organization-plugin"
import { SlugField, sanitizeSlug } from "./slug-field"

export type CreateOrganizationDialogProps = {
  open: boolean
  onOpenChange: (open: boolean) => void
}

const organizationFallbackLocalization = {
  createOrganization: "Create organization",
  name: "Name",
  namePlaceholder: "Enter the organization name",
  organizationsDescription:
    "Create an organization to collaborate with others and manage shared access."
} satisfies Pick<
  OrganizationLocalization,
  "createOrganization" | "name" | "namePlaceholder" | "organizationsDescription"
>

export function CreateOrganizationDialog(props: CreateOrganizationDialogProps) {
  const auth = useAuth()
  const [name, setName] = createSignal("")
  const [slug, setSlug] = createSignal("")
  const createOrganization = useCreateOrganization(
    auth.authClient as OrganizationAuthClient,
    {
      onSuccess: () => props.onOpenChange(false)
    }
  )
  const organizationPluginConfig = () =>
    auth.plugins.find((plugin) => plugin.id === organizationPlugin.id) as
      | { localization?: OrganizationLocalization }
      | undefined
  const localization = () =>
    organizationPluginConfig()?.localization ?? organizationFallbackLocalization

  createEffect(() => {
    if (!props.open) {
      setName("")
      setSlug("")
      return
    }

    setSlug(sanitizeSlug(name()))
  })

  const handleSubmit = (event: SubmitEvent) => {
    event.preventDefault()

    createOrganization.mutate({
      name: name(),
      slug: slug()
    })
  }

  return (
    <Dialog open={props.open} onOpenChange={props.onOpenChange}>
      <DialogContent>
        <form class="flex flex-col gap-6" onSubmit={handleSubmit}>
          <DialogHeader>
            <div class="flex size-10 items-center justify-center rounded-md bg-muted">
              <BriefcaseBusiness class="size-4.5" />
            </div>
            <DialogTitle>{localization().createOrganization}</DialogTitle>
            <DialogDescription>
              {localization().organizationsDescription}
            </DialogDescription>
          </DialogHeader>

          <div class="grid gap-2">
            <Label for="create-organization-name">{localization().name}</Label>
            <Input
              autofocus
              disabled={createOrganization.isPending}
              id="create-organization-name"
              name="name"
              onInput={(event) => setName(event.currentTarget.value)}
              placeholder={localization().namePlaceholder}
              required
              value={name()}
            />
          </div>

          <SlugField
            disabled={createOrganization.isPending}
            id="create-organization-slug"
            onChange={setSlug}
            value={slug()}
          />

          <DialogFooter>
            <DialogClose
              as={Button}
              disabled={createOrganization.isPending}
              type="button"
              variant="outline"
            >
              {auth.localization.settings.cancel}
            </DialogClose>
            <Button disabled={createOrganization.isPending} type="submit">
              {createOrganization.isPending ? (
                <>
                  <LoaderCircle class="size-4 animate-spin" />
                  {localization().createOrganization}
                </>
              ) : (
                localization().createOrganization
              )}
            </Button>
          </DialogFooter>
        </form>
      </DialogContent>
    </Dialog>
  )
}

// examples/start-shadcn-example/src/components/auth/organization/create-organization-dialog.tsx
"use client"

import {
  type OrganizationAuthClient,
  useAuth,
  useAuthPlugin,
  useCreateOrganization
} from "@better-auth-ui/react"
import { Briefcase } from "lucide-react"
import { type SyntheticEvent, useEffect, useState } from "react"

import {
  AlertDialog,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogMedia,
  AlertDialogTitle
} from "@/components/ui/alert-dialog"
import { Button } from "@/components/ui/button"
import { Field, FieldError } from "@/components/ui/field"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { Spinner } from "@/components/ui/spinner"
import { organizationPlugin } from "@/lib/auth/organization-plugin"
import { SlugField, sanitizeSlug } from "./slug-field"

/** Props for the `CreateOrganizationDialog` component. */
export type CreateOrganizationDialogProps = {
  open: boolean
  onOpenChange: (open: boolean) => void
}

export function CreateOrganizationDialog({
  open,
  onOpenChange
}: CreateOrganizationDialogProps) {
  const { authClient, localization } = useAuth()
  const { localization: organizationLocalization } =
    useAuthPlugin(organizationPlugin)

  const [name, setName] = useState("")
  const [slug, setSlug] = useState("")
  const [nameError, setNameError] = useState<string>()

  const { mutate: createOrganization, isPending: isCreating } =
    useCreateOrganization(authClient as OrganizationAuthClient, {
      onSuccess: () => onOpenChange(false)
    })

  const handleSubmit = (e: SyntheticEvent<HTMLFormElement>) => {
    e.preventDefault()
    createOrganization({ name, slug })
  }

  useEffect(() => {
    if (!open) {
      setSlug("")
      setName("")
      setNameError(undefined)
    }
  }, [open])

  useEffect(() => {
    setSlug(sanitizeSlug(name))
  }, [name])

  return (
    <AlertDialog open={open} onOpenChange={onOpenChange}>
      <AlertDialogContent>
        <form onSubmit={handleSubmit} className="flex flex-col gap-6">
          <AlertDialogHeader>
            <AlertDialogMedia>
              <Briefcase />
            </AlertDialogMedia>

            <AlertDialogTitle>
              {organizationLocalization.createOrganization}
            </AlertDialogTitle>

            <AlertDialogDescription>
              {organizationLocalization.organizationsDescription}
            </AlertDialogDescription>
          </AlertDialogHeader>

          <div className="flex flex-col gap-4">
            <Field data-invalid={!!nameError}>
              <Label htmlFor="create-organization-name">
                {organizationLocalization.name}
              </Label>

              <Input
                id="create-organization-name"
                name="name"
                autoFocus
                required
                placeholder={organizationLocalization.namePlaceholder}
                value={name}
                onChange={(e) => {
                  setName(e.target.value)
                  setNameError(undefined)
                }}
                onInvalid={(e) => {
                  e.preventDefault()
                  setNameError(localization.auth.fieldRequired)
                }}
                aria-invalid={!!nameError}
                disabled={isCreating}
              />

              <FieldError>{nameError}</FieldError>
            </Field>

            <SlugField
              id="create-organization-slug"
              value={slug}
              onChange={setSlug}
              disabled={isCreating}
            />
          </div>

          <AlertDialogFooter>
            <AlertDialogCancel disabled={isCreating}>
              {localization.settings.cancel}
            </AlertDialogCancel>

            <Button type="submit" disabled={isCreating}>
              {isCreating && <Spinner />}

              {organizationLocalization.createOrganization}
            </Button>
          </AlertDialogFooter>
        </form>
      </AlertDialogContent>
    </AlertDialog>
  )
}
