// packages/heroui/src/components/auth/email-otp/email-otp.tsx
import { authMutationKeys } from "@better-auth-ui/core"
import {
  type EmailOtpAuthClient,
  useAuth,
  useAuthPlugin,
  useSendVerificationOtp,
  useSignInEmailOtp
} from "@better-auth-ui/react"
import {
  Button,
  Card,
  type CardProps,
  cn,
  Description,
  FieldError,
  Form,
  Input,
  Label,
  Link,
  Spinner,
  TextField
} from "@heroui/react"
import { useIsMutating } from "@tanstack/react-query"
import { type SyntheticEvent, useState } from "react"

import { emailOtpPlugin } from "../../../lib/auth/email-otp-plugin"
import { useResendCooldown } from "../../../lib/auth/use-resend-cooldown"
import { useSignInContinuation } from "../../../lib/auth/use-sign-in-continuation"
import { FieldSeparator } from "../field-separator"
import { OpenEmailButton } from "../open-email-button"
import { OtpField } from "../otp-field"
import { ProviderButtons, type SocialLayout } from "../provider-buttons"

export type EmailOtpProps = {
  className?: string
  socialLayout?: SocialLayout
  socialPosition?: "top" | "bottom"
  variant?: CardProps["variant"]
}

/**
 * Passwordless sign-in with an emailed one-time code.
 *
 * Two steps on one route: enter an email, then enter the code that arrives.
 * The email step never reveals whether an account exists — the server decides
 * whether the code creates an account, mirroring `emailOTP({ disableSignUp })`.
 *
 * @param socialLayout - Provider button layout.
 * @param socialPosition - `"top"` or `"bottom"`. Defaults to `"bottom"`.
 * @param variant - Card variant.
 */
export function EmailOtp({
  className,
  socialLayout,
  socialPosition = "bottom",
  variant
}: EmailOtpProps) {
  const {
    authClient,
    basePaths,
    emailAndPassword,
    localization,
    plugins,
    socialProviders,
    viewPaths
  } = useAuth()
  const { localization: emailOtpLocalization, otpLength } =
    useAuthPlugin(emailOtpPlugin)

  const otpClient = authClient as EmailOtpAuthClient
  const continueSignIn = useSignInContinuation()
  const { cooldown, isCoolingDown, startCooldown } = useResendCooldown()

  const [email, setEmail] = useState("")
  const [code, setCode] = useState("")
  const [codeSent, setCodeSent] = useState(false)

  const { mutate: sendVerificationOtp, isPending: isSending } =
    useSendVerificationOtp(otpClient, {
      onSuccess: () => {
        setCodeSent(true)
        startCooldown()
      }
    })

  const { mutate: signInEmailOtp, isPending: isSigningIn } = useSignInEmailOtp(
    otpClient,
    {
      onError: () => setCode(""),
      onSuccess: (data) => continueSignIn(data)
    }
  )

  const signInMutating = useIsMutating({
    mutationKey: authMutationKeys.signIn.all
  })
  const signUpMutating = useIsMutating({
    mutationKey: authMutationKeys.signUp.all
  })
  const isPending = signInMutating + signUpMutating > 0 || isSending

  const sendCode = () => sendVerificationOtp({ email, type: "sign-in" })
  const verifyCode = (completedCode: string) => {
    if (isPending || isSigningIn) return

    signInEmailOtp({ email, otp: completedCode })
  }

  const handleSubmit = (e: SyntheticEvent<HTMLFormElement>) => {
    e.preventDefault()

    if (!codeSent) {
      sendCode()
      return
    }

    verifyCode(code)
  }

  const startOver = () => {
    setCodeSent(false)
    setCode("")
  }

  const showSeparator = !!socialProviders?.length

  return (
    <Card
      className={cn("w-full max-w-sm gap-4 md:p-6", className)}
      variant={variant}
    >
      <Card.Header>
        <Card.Title className="text-xl font-semibold mb-1">
          {localization.auth.signIn}
        </Card.Title>

        {codeSent && (
          <Card.Description>
            {emailOtpLocalization.codeSentTo.replace("{{email}}", email)}
          </Card.Description>
        )}
      </Card.Header>

      <Card.Content className="gap-4">
        {socialPosition === "top" && (
          <>
            {!!socialProviders?.length && (
              <ProviderButtons socialLayout={socialLayout} view="emailOtp" />
            )}

            {showSeparator && (
              <FieldSeparator>{localization.auth.or}</FieldSeparator>
            )}
          </>
        )}

        <Form onSubmit={handleSubmit} className="flex flex-col gap-4">
          {codeSent ? (
            <OtpField
              autoFocus
              isDisabled={isPending}
              label={emailOtpLocalization.code}
              length={otpLength}
              name="otp"
              value={code}
              variant={variant}
              onChange={setCode}
              onComplete={verifyCode}
            />
          ) : (
            <TextField
              name="email"
              type="email"
              autoComplete="email"
              isDisabled={isPending}
              value={email}
              onChange={setEmail}
              validate={(value) => {
                if (!value) return localization.auth.fieldRequired
                if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(value))
                  return localization.auth.invalidEmail
              }}
            >
              <Label>{localization.auth.email}</Label>

              <Input
                placeholder={localization.auth.emailPlaceholder}
                required
                variant={variant === "transparent" ? "primary" : "secondary"}
              />

              <FieldError />
            </TextField>
          )}

          <div className="flex flex-col gap-3">
            <Button
              type="submit"
              className="w-full"
              isDisabled={codeSent && code.length !== otpLength}
              isPending={isPending || isSigningIn}
            >
              {(isSending || isSigningIn) && (
                <Spinner color="current" size="sm" />
              )}

              {codeSent
                ? emailOtpLocalization.verifyCode
                : emailOtpLocalization.sendCode}
            </Button>

            {codeSent ? (
              <div className="flex flex-col gap-3">
                <OpenEmailButton email={email} variant="secondary" />

                <Button
                  className="w-full"
                  variant="tertiary"
                  isDisabled={isPending || isSigningIn || isCoolingDown}
                  onPress={sendCode}
                >
                  {isCoolingDown
                    ? localization.auth.resendIn.replace(
                        "{{seconds}}",
                        String(cooldown)
                      )
                    : localization.auth.resend}
                </Button>

                <Button
                  className="w-full"
                  variant="ghost"
                  isDisabled={isPending || isSigningIn}
                  onPress={startOver}
                >
                  {emailOtpLocalization.useDifferentEmail}
                </Button>
              </div>
            ) : (
              plugins.flatMap((plugin) =>
                (plugin.authButtons ?? []).map((AuthButton, index) => (
                  <AuthButton
                    key={`${plugin.id}-${index.toString()}`}
                    view="emailOtp"
                  />
                ))
              )
            )}
          </div>
        </Form>

        {socialPosition === "bottom" && !codeSent && (
          <>
            {showSeparator && (
              <FieldSeparator>{localization.auth.or}</FieldSeparator>
            )}

            {!!socialProviders?.length && (
              <ProviderButtons socialLayout={socialLayout} view="emailOtp" />
            )}
          </>
        )}
      </Card.Content>

      {emailAndPassword?.enabled && (
        <Card.Footer className="flex-col gap-3">
          <Description className="text-sm">
            {localization.auth.needToCreateAnAccount}{" "}
            <Link
              href={`${basePaths.auth}/${viewPaths.auth.signUp}`}
              className="text-accent no-underline hover:underline decoration-accent-hover"
            >
              {localization.auth.signUp}
            </Link>
          </Description>
        </Card.Footer>
      )}
    </Card>
  )
}

// examples/start-solid-zaidan-example/src/components/auth/email-otp/email-otp.tsx
import {
  type EmailOtpAuthClient,
  sendVerificationOtpOptions,
  signInEmailOtpOptions,
  useAuth,
  useAuthPlugin
} from "@better-auth-ui/solid"
import { createMutation } from "@tanstack/solid-query"
import { createSignal, Show } from "solid-js"

import { OpenEmailButton } from "@/components/auth/open-email-button"
import { OtpField } from "@/components/auth/otp-field"
import {
  ProviderButtons,
  type SocialLayout
} from "@/components/auth/provider-buttons"
import { Button } from "@/components/ui/button"
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle
} from "@/components/ui/card"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { Spinner } from "@/components/ui/spinner"
import { emailOtpPlugin } from "@/lib/auth/email-otp-plugin"
import { useResendCooldown } from "@/lib/auth/use-resend-cooldown"
import { useSignInContinuation } from "@/lib/auth/use-sign-in-continuation"
import { cn } from "@/lib/utils"

export type EmailOtpProps = {
  class?: string
  socialLayout?: SocialLayout
  socialPosition?: "bottom" | "top"
}

/**
 * Passwordless sign-in with an emailed one-time code.
 *
 * Two steps on one route: enter an email, then enter the code that arrives.
 * The email step never reveals whether an account exists — the server decides
 * whether the code creates an account, mirroring `emailOTP({ disableSignUp })`.
 */
export function EmailOtp(props: EmailOtpProps) {
  const auth = useAuth()
  const { localization: emailOtpLocalization, otpLength } =
    useAuthPlugin(emailOtpPlugin)
  const continueSignIn = useSignInContinuation()
  const { cooldown, isCoolingDown, startCooldown } = useResendCooldown()

  const [email, setEmail] = createSignal("")
  const [emailError, setEmailError] = createSignal<string>()
  const [code, setCode] = createSignal("")
  const [codeSent, setCodeSent] = createSignal(false)

  const otpClient = () => auth.authClient as EmailOtpAuthClient

  const sendCode = createMutation(() => ({
    ...sendVerificationOtpOptions(otpClient()),
    onSuccess: () => {
      setCodeSent(true)
      startCooldown()
    }
  }))

  const signIn = createMutation(() => ({
    ...signInEmailOtpOptions(otpClient()),
    onError: () => setCode(""),
    onSuccess: (data) => continueSignIn(data)
  }))

  const isPending = () => sendCode.isPending || signIn.isPending

  const requestCode = () =>
    sendCode.mutate({ email: email(), type: "sign-in" } as Parameters<
      typeof sendCode.mutate
    >[0])

  const verifyCode = (completedCode: string) => {
    if (isPending()) return

    signIn.mutate({ email: email(), otp: completedCode } as Parameters<
      typeof signIn.mutate
    >[0])
  }

  const submit = (event: SubmitEvent & { currentTarget: HTMLFormElement }) => {
    event.preventDefault()

    if (!codeSent()) {
      requestCode()
      return
    }

    verifyCode(code())
  }

  const socialPosition = () => props.socialPosition ?? "bottom"
  const showSeparator = () => Boolean(auth.socialProviders?.length)

  return (
    <Card class={cn("w-full max-w-sm", props.class)}>
      <CardHeader>
        <CardTitle class="text-xl font-semibold">
          {auth.localization.auth.signIn}
        </CardTitle>

        <Show when={codeSent()}>
          <CardDescription>
            {emailOtpLocalization.codeSentTo.replace("{{email}}", email())}
          </CardDescription>
        </Show>
      </CardHeader>

      <CardContent>
        <div class="flex flex-col gap-6">
          <Show
            when={
              socialPosition() === "top" &&
              !codeSent() &&
              auth.socialProviders?.length
            }
          >
            <ProviderButtons socialLayout={props.socialLayout} />

            <Show when={showSeparator()}>
              <div class="text-center text-muted-foreground text-xs">
                {auth.localization.auth.or}
              </div>
            </Show>
          </Show>

          <form aria-label={auth.localization.auth.signIn} onSubmit={submit}>
            <div class="grid gap-3">
              <Show
                when={codeSent()}
                fallback={
                  <>
                    <Label for="email-otp-email">
                      {auth.localization.auth.email}
                    </Label>

                    <Input
                      aria-invalid={Boolean(emailError())}
                      autocomplete="email"
                      disabled={isPending()}
                      id="email-otp-email"
                      name="email"
                      onInput={(event) => {
                        setEmail(event.currentTarget.value)
                        setEmailError(undefined)
                      }}
                      onInvalid={(event) => {
                        event.preventDefault()
                        setEmailError(event.currentTarget.validationMessage)
                      }}
                      placeholder={auth.localization.auth.emailPlaceholder}
                      required
                      type="email"
                      value={email()}
                    />

                    <Show when={emailError()}>
                      {(message) => (
                        <p class="text-sm text-destructive" role="alert">
                          {message()}
                        </p>
                      )}
                    </Show>
                  </>
                }
              >
                <OtpField
                  autofocus
                  disabled={isPending()}
                  id="email-otp-code"
                  label={emailOtpLocalization.code}
                  length={otpLength}
                  name="otp"
                  onInput={setCode}
                  onComplete={verifyCode}
                  value={code()}
                />
              </Show>

              <div class="flex flex-col gap-3">
                <Button
                  class="w-full"
                  disabled={
                    isPending() || (codeSent() && code().length !== otpLength)
                  }
                  type="submit"
                >
                  <Show when={isPending()}>
                    <Spinner />
                  </Show>

                  {codeSent()
                    ? emailOtpLocalization.verifyCode
                    : emailOtpLocalization.sendCode}
                </Button>

                <Show when={codeSent()}>
                  <OpenEmailButton email={email()} variant="secondary" />

                  <Button
                    class="w-full"
                    disabled={isPending() || isCoolingDown()}
                    onClick={requestCode}
                    type="button"
                    variant="outline"
                  >
                    {isCoolingDown()
                      ? auth.localization.auth.resendIn.replace(
                          "{{seconds}}",
                          String(cooldown())
                        )
                      : auth.localization.auth.resend}
                  </Button>

                  <Button
                    class="w-full"
                    disabled={isPending()}
                    onClick={() => {
                      setCodeSent(false)
                      setCode("")
                    }}
                    type="button"
                    variant="ghost"
                  >
                    {emailOtpLocalization.useDifferentEmail}
                  </Button>
                </Show>
              </div>
            </div>
          </form>

          <Show
            when={
              socialPosition() === "bottom" &&
              !codeSent() &&
              auth.socialProviders?.length
            }
          >
            <Show when={showSeparator()}>
              <div class="text-center text-muted-foreground text-xs">
                {auth.localization.auth.or}
              </div>
            </Show>

            <ProviderButtons socialLayout={props.socialLayout} />
          </Show>
        </div>
      </CardContent>
    </Card>
  )
}
