// packages/heroui/src/components/auth/api-key/api-key.tsx
import {
  type ListedApiKey,
  useAuth,
  useAuthPlugin
} from "@better-auth-ui/react"
import { Key, Xmark } from "@gravity-ui/icons"
import { Button } from "@heroui/react"
import { useState } from "react"

import { apiKeyPlugin } from "../../../lib/auth/api-key-plugin"
import { DeleteApiKeyDialog } from "./delete-api-key-dialog"

export type ApiKeyProps = {
  apiKey: ListedApiKey
}

export function ApiKey({ apiKey }: ApiKeyProps) {
  const { localization } = useAuth()
  const { localization: apiKeyLocalization } = useAuthPlugin(apiKeyPlugin)
  const [deleteOpen, setDeleteOpen] = useState(false)

  const preview = `${apiKey.start}${"*".repeat(16)}`

  return (
    <div className="flex items-center gap-3">
      <div className="flex size-10 shrink-0 items-center justify-center rounded-xl bg-surface-secondary">
        <Key className="size-4.5" />
      </div>

      <div className="flex flex-col min-w-0">
        <span className="text-sm font-medium leading-tight truncate">
          {apiKey.name || apiKeyLocalization.apiKey}
        </span>

        <span className="text-xs text-muted font-mono truncate">{preview}</span>

        <span className="text-xs text-muted">
          {new Date(apiKey.createdAt).toLocaleString(undefined, {
            dateStyle: "medium",
            timeStyle: "short"
          })}
        </span>
      </div>

      <Button
        className="ml-auto shrink-0"
        variant="outline"
        size="sm"
        onPress={() => setDeleteOpen(true)}
        aria-label={apiKeyLocalization.deleteApiKey}
      >
        <Xmark />

        {localization.settings.delete}
      </Button>

      <DeleteApiKeyDialog
        isOpen={deleteOpen}
        onOpenChange={setDeleteOpen}
        apiKey={apiKey}
      />
    </div>
  )
}

// examples/start-solid-zaidan-example/src/components/auth/api-key/api-key.tsx
import { apiKeyLocalization } from "@better-auth-ui/core/plugins"
import { useAuth } from "@better-auth-ui/solid"
import { Key, X } from "lucide-solid"
import { createSignal, Show } from "solid-js"
import { DeleteApiKeyDialog } from "@/components/auth/api-key/delete-api-key-dialog"
import type { ListedApiKey } from "@/components/auth/settings/shared/types"
import { Button } from "@/components/ui/button"
import { Dialog, DialogTrigger } from "@/components/ui/dialog"

export function ApiKey(props: {
  apiKey: ListedApiKey
  organizationId?: string
  hideDelete?: boolean
}) {
  const auth = useAuth()
  const [deleteOpen, setDeleteOpen] = createSignal(false)
  const preview = () => `${props.apiKey.start}${"*".repeat(16)}`

  return (
    <div class="flex items-center gap-3 p-6">
      <div class="flex size-10 shrink-0 items-center justify-center rounded-md bg-muted">
        <Key class="size-4.5" />
      </div>

      <div class="flex min-w-0 flex-col">
        <span class="truncate font-medium text-sm leading-tight">
          {props.apiKey.name || apiKeyLocalization.apiKey}
        </span>
        <span class="truncate font-mono text-muted-foreground text-xs">
          {preview()}
        </span>
        <span class="text-muted-foreground text-xs">
          {new Date(props.apiKey.createdAt).toLocaleString(undefined, {
            dateStyle: "medium",
            timeStyle: "short"
          })}
        </span>
      </div>

      <Show when={!props.hideDelete}>
        <Dialog open={deleteOpen()} onOpenChange={setDeleteOpen}>
          <DialogTrigger
            as={Button}
            aria-label={apiKeyLocalization.deleteApiKey}
            class="ml-auto shrink-0"
            size="sm"
            variant="outline"
          >
            <X />
            {auth.localization.settings.delete}
          </DialogTrigger>
          <DeleteApiKeyDialog
            apiKey={props.apiKey}
            organizationId={props.organizationId}
            onOpenChange={setDeleteOpen}
          />
        </Dialog>
      </Show>
    </div>
  )
}
