// packages/heroui/src/components/multi-session/switch-account-submenu.tsx
import { useAuth, useAuthPlugin, useSession } from "@better-auth-ui/react"
import { Persons } from "@gravity-ui/icons"
import { Dropdown, Label } from "@heroui/react"

import { multiSessionPlugin } from "../../lib/multi-session/multi-session-plugin"

import { SwitchAccountSubmenuContent } from "./switch-account-submenu-content"

export type SwitchAccountSubmenuProps = {
  className?: string
}

/**
 * Render a dropdown submenu for switching between multiple authenticated sessions.
 *
 * This component renders as a submenu trigger that opens the switch account menu.
 * It should be rendered inside a Dropdown.Menu.
 *
 * @param className - Optional additional CSS class names
 * @returns The switch account submenu as a JSX element
 */
export function SwitchAccountSubmenu({ className }: SwitchAccountSubmenuProps) {
  const { authClient } = useAuth()
  const { data: session } = useSession(authClient)
  const { localization: multiSessionLocalization } =
    useAuthPlugin(multiSessionPlugin)

  if (!session) {
    return null
  }

  return (
    <Dropdown.SubmenuTrigger>
      <Dropdown.Item
        className={className}
        textValue={multiSessionLocalization.switchAccount}
      >
        <Persons className="text-muted" />

        <Label>{multiSessionLocalization.switchAccount}</Label>

        <Dropdown.SubmenuIndicator />
      </Dropdown.Item>

      <Dropdown.Popover className="min-w-40 md:min-w-56 max-w-[48svw]">
        <SwitchAccountSubmenuContent />
      </Dropdown.Popover>
    </Dropdown.SubmenuTrigger>
  )
}

// examples/start-solid-zaidan-example/src/components/auth/multi-session/switch-account-submenu.tsx
import {
  multiSessionPlugin as coreMultiSessionPlugin,
  type MultiSessionLocalization,
  multiSessionLocalization
} from "@better-auth-ui/core/plugins"
import { useAuth, useSession } from "@better-auth-ui/solid"
import { ArrowLeftRight } from "lucide-solid"
import { Show } from "solid-js"
import {
  DropdownMenuSub,
  DropdownMenuSubTrigger
} from "@/components/ui/dropdown-menu"
import { SwitchAccountSubmenuContent } from "./switch-account-submenu-content"

export type SwitchAccountSubmenuProps = {
  class?: string
}

export function SwitchAccountSubmenu(props: SwitchAccountSubmenuProps) {
  const auth = useAuth()
  const session = useSession(auth.authClient, {
    enabled: !import.meta.env.SSR
  })
  const multiSessionPluginConfig = () =>
    auth.plugins.find((plugin) => plugin.id === coreMultiSessionPlugin.id)
  const multiSessionLabels = (): MultiSessionLocalization => ({
    ...multiSessionLocalization,
    ...(multiSessionPluginConfig()?.localization as
      | Partial<MultiSessionLocalization>
      | undefined)
  })

  return (
    <Show when={session.data}>
      <DropdownMenuSub>
        <DropdownMenuSubTrigger class={props.class}>
          <ArrowLeftRight class="size-4 text-muted-foreground" />
          {multiSessionLabels().switchAccount}
        </DropdownMenuSubTrigger>

        <SwitchAccountSubmenuContent />
      </DropdownMenuSub>
    </Show>
  )
}
