// examples/start-shadcn-example/src/components/user/switch-account-submenu-content.tsx
"use client"

import {
  type MultiSessionAuthClient,
  useAuth,
  useAuthPlugin,
  useListDeviceSessions,
  useSession
} from "@better-auth-ui/react"
import { Check, CirclePlus } from "lucide-react"

import {
  DropdownMenuItem,
  DropdownMenuSeparator,
  DropdownMenuSubContent
} from "@/components/ui/dropdown-menu"
import { multiSessionPlugin } from "@/lib/multi-session/multi-session-plugin"
import { SwitchAccountSubmenuItem } from "./switch-account-submenu-item"
import { UserView } from "./user-view"

/**
 * Render the submenu content for switching between multiple authenticated sessions.
 *
 * Shows the current session with a checkmark, lists other device sessions that can be activated,
 * and provides an option to add a new account. This component should be rendered inside a
 * DropdownMenuSub to defer the useListDeviceSessions query until the submenu is opened.
 *
 * @returns The switch account submenu content as a JSX element
 */
export function SwitchAccountSubmenuContent() {
  const { authClient, basePaths, viewPaths, Link } = useAuth()
  const { localization: multiSessionLocalization } =
    useAuthPlugin(multiSessionPlugin)
  const { data: session } = useSession(authClient)
  const { data: deviceSessions, isPending } = useListDeviceSessions(
    authClient as MultiSessionAuthClient
  )

  return (
    <DropdownMenuSubContent className="min-w-48 md:min-w-56 max-w-[48svw]">
      <DropdownMenuItem>
        <UserView isPending={isPending} />

        {!isPending && <Check className="ml-auto" />}
      </DropdownMenuItem>

      {deviceSessions
        ?.filter(
          (deviceSession) => deviceSession.session.id !== session?.session.id
        )
        .map((deviceSession) => (
          <SwitchAccountSubmenuItem
            key={deviceSession.session.id}
            deviceSession={deviceSession}
          />
        ))}

      <DropdownMenuSeparator />

      <DropdownMenuItem asChild>
        <Link href={`${basePaths.auth}/${viewPaths.auth.signIn}`}>
          <CirclePlus className="text-muted-foreground" />

          {multiSessionLocalization.addAccount}
        </Link>
      </DropdownMenuItem>
    </DropdownMenuSubContent>
  )
}

// examples/start-solid-zaidan-example/src/components/auth/multi-session/switch-account-submenu-content.tsx
import {
  multiSessionPlugin as coreMultiSessionPlugin,
  type MultiSessionLocalization,
  multiSessionLocalization
} from "@better-auth-ui/core/plugins"
import {
  listDeviceSessionsOptions,
  type MultiSessionAuthClient,
  useAuth,
  useSession
} from "@better-auth-ui/solid"
import { createQuery } from "@tanstack/solid-query"
import { Link } from "@tanstack/solid-router"
import { Check, CirclePlus } from "lucide-solid"
import { For, Show } from "solid-js"
import { shouldLoadDeviceSessions } from "@/components/auth/settings/shared/helpers"
import type { DeviceSession } from "@/components/auth/settings/shared/types"
import { UserView } from "@/components/auth/user/user-view"
import {
  DropdownMenuItem,
  DropdownMenuSeparator,
  DropdownMenuSubContent
} from "@/components/ui/dropdown-menu"
import { SwitchAccountSubmenuItem } from "./switch-account-submenu-item"

export function SwitchAccountSubmenuContent() {
  const auth = useAuth()
  const session = useSession(auth.authClient, {
    enabled: !import.meta.env.SSR
  })
  const userId = () => session.data?.user.id
  const multiSessionPluginConfig = () =>
    auth.plugins.find((plugin) => plugin.id === coreMultiSessionPlugin.id)
  const multiSessionLabels = (): MultiSessionLocalization => ({
    ...multiSessionLocalization,
    ...(multiSessionPluginConfig()?.localization as
      | Partial<MultiSessionLocalization>
      | undefined)
  })
  const deviceSessions = createQuery(() => ({
    ...listDeviceSessionsOptions(
      auth.authClient as MultiSessionAuthClient,
      userId()
    ),
    enabled: shouldLoadDeviceSessions({
      isSsr: import.meta.env.SSR,
      userId: userId()
    })
  }))
  const otherDeviceSessions = () => {
    const sessions = (deviceSessions.data ?? []) as DeviceSession[]

    return sessions.filter(
      (deviceSession) => deviceSession.session.id !== session.data?.session.id
    )
  }

  return (
    <DropdownMenuSubContent class="min-w-48 max-w-[48svw] md:min-w-56">
      <DropdownMenuItem>
        <UserView
          isPending={deviceSessions.isPending}
          user={session.data?.user}
        />
        <Show when={!deviceSessions.isPending}>
          <Check class="ml-auto size-4" />
        </Show>
      </DropdownMenuItem>

      <For each={otherDeviceSessions()}>
        {(deviceSession) => (
          <SwitchAccountSubmenuItem deviceSession={deviceSession} />
        )}
      </For>

      <DropdownMenuSeparator />

      <DropdownMenuItem class="gap-1.5 rounded-md px-1.5 py-1 text-sm focus:bg-accent focus:text-accent-foreground">
        <Link
          class="flex w-full items-center gap-1.5"
          params={{ path: auth.viewPaths.auth.signIn }}
          to="/auth/$path"
        >
          <CirclePlus class="size-4 text-muted-foreground" />
          {multiSessionLabels().addAccount}
        </Link>
      </DropdownMenuItem>
    </DropdownMenuSubContent>
  )
}
