// examples/start-solid-zaidan-example/src/demos/organization/organization-demo-wrapper.tsx
import type { JSX } from "solid-js"
import { AuthProvider } from "@/components/auth/auth-provider"
import { organizationPlugin } from "@/lib/auth/organization-plugin"
import { authClient } from "@/lib/auth-client"

export function OrganizationDemoWrapper(props: { children: JSX.Element }) {
  return (
    <AuthProvider
      authClient={authClient}
      navigate={() => {}}
      plugins={[organizationPlugin({ slug: "acme" })]}
    >
      <div class="w-full">{props.children}</div>
    </AuthProvider>
  )
}

// apps/docs/src/demos/heroui/organization/organization-demo-wrapper.tsx
import { AuthProvider } from "@better-auth-ui/heroui"
import { organizationPlugin } from "@better-auth-ui/heroui/plugins"
import type { ReactNode } from "react"

import { authClient } from "@/lib/auth-client"

export function OrganizationDemoWrapper({ children }: { children: ReactNode }) {
  return (
    <AuthProvider
      authClient={authClient}
      navigate={() => {}}
      plugins={[organizationPlugin()]}
    >
      <div className="w-full">{children}</div>
    </AuthProvider>
  )
}
