// packages/heroui/src/components/auth/passkey/passkey.tsx
import { useAuth, useAuthPlugin } from "@better-auth-ui/react"
import { Fingerprint, Xmark } from "@gravity-ui/icons"
import { Button } from "@heroui/react"
import { useState } from "react"

import { passkeyPlugin } from "../../../lib/auth/passkey-plugin"
import {
  DeletePasskeyDialog,
  type ListedPasskey
} from "./delete-passkey-dialog"

export type PasskeyProps = {
  passkey: ListedPasskey
}

export function Passkey({ passkey }: PasskeyProps) {
  const { localization } = useAuth()
  const { localization: passkeyLocalization } = useAuthPlugin(passkeyPlugin)
  const [deleteOpen, setDeleteOpen] = useState(false)

  const passkeyName = passkey.name || passkeyLocalization.passkey

  return (
    <div className="flex items-center gap-3">
      <div className="flex size-10 shrink-0 items-center justify-center rounded-xl bg-surface-secondary">
        <Fingerprint className="size-4.5" />
      </div>

      <div className="flex min-w-0 flex-col">
        <span className="truncate text-sm font-medium leading-tight">
          {passkeyName}
        </span>

        <span className="text-xs text-muted">
          {new Date(passkey.createdAt).toLocaleString(undefined, {
            dateStyle: "medium",
            timeStyle: "short"
          })}
        </span>
      </div>

      <Button
        className="ml-auto shrink-0"
        variant="outline"
        size="sm"
        onPress={() => setDeleteOpen(true)}
        aria-label={passkeyLocalization.deletePasskey.replace(
          "{{name}}",
          passkeyName
        )}
      >
        <Xmark />

        {localization.settings.delete}
      </Button>

      <DeletePasskeyDialog
        isOpen={deleteOpen}
        onOpenChange={setDeleteOpen}
        passkey={passkey}
      />
    </div>
  )
}

// examples/start-solid-zaidan-example/src/components/auth/passkey/passkey.tsx
import { useAuth } from "@better-auth-ui/solid"
import { Fingerprint, X } from "lucide-solid"
import { createSignal } from "solid-js"
import { DeletePasskeyDialog } from "@/components/auth/passkey/delete-passkey-dialog"
import { passkeyLabels } from "@/components/auth/passkey/passkey-localization"
import type { ListedPasskey } from "@/components/auth/settings/shared/types"
import { Button } from "@/components/ui/button"
import { Dialog, DialogTrigger } from "@/components/ui/dialog"

export function Passkey(props: { passkey: ListedPasskey }) {
  const auth = useAuth()
  const labels = () => passkeyLabels(auth)
  const [deleteOpen, setDeleteOpen] = createSignal(false)
  const passkeyName = () => props.passkey.name || labels().passkey

  return (
    <div class="flex items-center gap-3 p-4 text-sm">
      <div class="flex size-10 shrink-0 items-center justify-center rounded-md bg-muted">
        <Fingerprint class="size-4.5" />
      </div>

      <div class="flex min-w-0 flex-col">
        <span class="truncate font-medium leading-tight">{passkeyName()}</span>
        <span class="text-muted-foreground text-xs">
          {new Date(props.passkey.createdAt).toLocaleString(undefined, {
            dateStyle: "medium",
            timeStyle: "short"
          })}
        </span>
      </div>

      <Dialog open={deleteOpen()} onOpenChange={setDeleteOpen}>
        <DialogTrigger
          as={Button}
          aria-label={labels().deletePasskey.replace("{{name}}", passkeyName())}
          class="ml-auto shrink-0"
          size="sm"
          variant="outline"
        >
          <X />
          {auth.localization.settings.delete}
        </DialogTrigger>
        <DeletePasskeyDialog
          onOpenChange={setDeleteOpen}
          passkey={props.passkey}
        />
      </Dialog>
    </div>
  )
}
