// examples/start-shadcn-example/src/components/settings/security/passkeys.tsx
"use client"

import {
  type PasskeyAuthClient,
  useAddPasskey,
  useAuth,
  useAuthPlugin,
  useListPasskeys
} from "@better-auth-ui/react"
import { Button } from "@/components/ui/button"
import { Card, CardContent } from "@/components/ui/card"
import { Separator } from "@/components/ui/separator"
import { Skeleton } from "@/components/ui/skeleton"
import { Spinner } from "@/components/ui/spinner"
import { passkeyPlugin } from "@/lib/passkey/passkey-plugin"
import { cn } from "@/lib/utils"
import { Passkey } from "./passkey"

export type PasskeysProps = {
  className?: string
}

export function Passkeys({ className }: PasskeysProps) {
  const { authClient } = useAuth()
  const { localization: passkeyLocalization } = useAuthPlugin(passkeyPlugin)

  const { data: passkeys, isPending } = useListPasskeys(
    authClient as PasskeyAuthClient
  )

  const { mutate: addPasskey, isPending: isAdding } = useAddPasskey(
    authClient as PasskeyAuthClient
  )

  return (
    <div>
      <h2 className="text-sm font-semibold mb-3">
        {passkeyLocalization.passkeys}
      </h2>

      <Card className={cn("p-0", className)}>
        <CardContent className="p-0">
          <Card className="bg-transparent border-0 ring-0 shadow-none">
            <CardContent className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between">
              <div>
                <p className="text-sm font-medium leading-tight">
                  {passkeyLocalization.passkeysDescription}
                </p>

                <p className="text-muted-foreground text-xs mt-0.5">
                  {passkeyLocalization.passkeysInstructions}
                </p>
              </div>

              <Button
                className="shrink-0"
                size="sm"
                disabled={isPending || isAdding}
                onClick={() => addPasskey()}
              >
                {isAdding && <Spinner />}
                {passkeyLocalization.addPasskey}
              </Button>
            </CardContent>
          </Card>

          {isPending ? (
            <>
              <Separator />
              <PasskeySkeleton />
            </>
          ) : (
            passkeys?.map((passkey) => (
              <div key={passkey.id}>
                <Separator />
                <Passkey passkey={passkey} />
              </div>
            ))
          )}
        </CardContent>
      </Card>
    </div>
  )
}

function PasskeySkeleton() {
  return (
    <Card className="bg-transparent border-0 ring-0 shadow-none">
      <CardContent className="flex items-center gap-3">
        <Skeleton className="size-10 rounded-md" />

        <div className="flex flex-col gap-1">
          <Skeleton className="h-4 w-24" />
          <Skeleton className="h-3 w-20" />
        </div>
      </CardContent>
    </Card>
  )
}

// examples/start-solid-zaidan-example/src/components/auth/passkey/passkeys.tsx
import {
  listPasskeysOptions,
  type PasskeyAuthClient,
  useAuth,
  useSession
} from "@better-auth-ui/solid"
import { createQuery } from "@tanstack/solid-query"
import { createSignal, For, Show } from "solid-js"
import { AddPasskeyDialog } from "@/components/auth/passkey/add-passkey-dialog"
import { Passkey } from "@/components/auth/passkey/passkey"
import { passkeyLabels } from "@/components/auth/passkey/passkey-localization"
import { PasskeySkeleton } from "@/components/auth/passkey/passkey-skeleton"
import { PasskeysEmpty } from "@/components/auth/passkey/passkeys-empty"
import { shouldLoadDeviceSessions } from "@/components/auth/settings/shared/helpers"
import type { ListedPasskey } from "@/components/auth/settings/shared/types"
import { Button } from "@/components/ui/button"
import { Card, CardContent } from "@/components/ui/card"
import { Dialog, DialogTrigger } from "@/components/ui/dialog"
import { ItemSeparator } from "@/components/ui/item"
import { cn } from "@/lib/utils"

export type PasskeysSettingsProps = {
  class?: string
}

export function PasskeysSettings(props: PasskeysSettingsProps) {
  const auth = useAuth()
  const labels = () => passkeyLabels(auth)
  const session = useSession(auth.authClient)
  const userId = () => session.data?.user.id
  const [isAddDialogOpen, setIsAddDialogOpen] = createSignal(false)
  const passkeys = createQuery(() => ({
    ...listPasskeysOptions(auth.authClient as PasskeyAuthClient, userId()),
    enabled: shouldLoadDeviceSessions({
      isSsr: import.meta.env.SSR,
      userId: userId()
    })
  }))
  const items = () => passkeys.data ?? []

  return (
    <div class={cn("flex flex-col gap-3", props.class)}>
      <div class="flex items-end justify-between gap-3">
        <h2 class="truncate text-sm font-semibold">{labels().passkeys}</h2>
        <Dialog open={isAddDialogOpen()} onOpenChange={setIsAddDialogOpen}>
          <DialogTrigger
            as={Button}
            class="shrink-0"
            disabled={passkeys.isPending}
            size="sm"
          >
            {labels().addPasskey}
          </DialogTrigger>
          <AddPasskeyDialog
            onOpenChange={setIsAddDialogOpen}
            onPasskeyAdded={() => passkeys.refetch()}
          />
        </Dialog>
      </div>

      <Card class="z-card-padding-none">
        <CardContent class="z-card-content-padding-none">
          <Show when={!passkeys.isPending} fallback={<PasskeySkeleton />}>
            <Show
              when={items().length > 0}
              fallback={
                <PasskeysEmpty onAddPress={() => setIsAddDialogOpen(true)} />
              }
            >
              <For each={items()}>
                {(passkey, index) => (
                  <>
                    <Show when={index() > 0}>
                      <ItemSeparator />
                    </Show>
                    <Passkey passkey={passkey as ListedPasskey} />
                  </>
                )}
              </For>
            </Show>
          </Show>
        </CardContent>
      </Card>
    </div>
  )
}
