// examples/start-solid-zaidan-example/src/components/auth/device-authorization/device-authorization.tsx
import type { DeviceAuthorizationLocalization } from "@better-auth-ui/core/plugins"
import {
  approveDeviceOptions,
  type DeviceAuthorizationAuthClient,
  denyDeviceOptions,
  useAuth,
  useAuthPlugin,
  useSession,
  verifyDeviceCodeOptions
} from "@better-auth-ui/solid"
import { createMutation } from "@tanstack/solid-query"
import type { BetterFetchError } from "better-auth/client"
import { Check, CircleCheck, CircleX, X } from "lucide-solid"
import {
  createEffect,
  createSignal,
  For,
  Match,
  onMount,
  Show,
  Switch
} from "solid-js"

import { Button } from "@/components/ui/button"
import {
  Card,
  CardContent,
  CardDescription,
  CardFooter,
  CardHeader,
  CardTitle
} from "@/components/ui/card"
import {
  InputOTP,
  InputOTPGroup,
  InputOTPSeparator,
  InputOTPSlot
} from "@/components/ui/input-otp"
import { Label } from "@/components/ui/label"
import { Separator } from "@/components/ui/separator"
import { Spinner } from "@/components/ui/spinner"
import { deviceAuthorizationPlugin } from "@/lib/auth/device-authorization-plugin"
import { cn } from "@/lib/utils"

type DeviceAuthorizationStep = "code" | "approval" | "approved" | "denied"

type VerifyDeviceCodeData = Awaited<
  ReturnType<DeviceAuthorizationAuthClient["device"]>
>
type VerifyDeviceCodeVariables = Parameters<
  DeviceAuthorizationAuthClient["device"]
>[0]
type ApproveDeviceData = Awaited<
  ReturnType<DeviceAuthorizationAuthClient["device"]["approve"]>
>
type ApproveDeviceVariables = Parameters<
  DeviceAuthorizationAuthClient["device"]["approve"]
>[0]
type DenyDeviceData = Awaited<
  ReturnType<DeviceAuthorizationAuthClient["device"]["deny"]>
>
type DenyDeviceVariables = Parameters<
  DeviceAuthorizationAuthClient["device"]["deny"]
>[0]

function normalizeDeviceCode(value: string) {
  return value.replace(/-/g, "").trim().toUpperCase()
}

function createDeviceCodeSlots(length: number) {
  return Array.from({ length }, (_, slotIndex) => ({
    id: `device-code-character-${String(slotIndex + 1)}`,
    index: slotIndex
  }))
}

export type DeviceAuthorizationProps = {
  class?: string
}

/**
 * Render Better Auth's browser-side device authorization ceremony.
 *
 * The view accepts a user code, sends unauthenticated users through sign-in
 * with a return URL, verifies and claims the code for the current session,
 * and lets the user approve or deny the device.
 */
export function DeviceAuthorization(props: DeviceAuthorizationProps) {
  const auth = useAuth()
  const {
    localization,
    userCodeLength,
    viewPaths: deviceAuthorizationViewPaths
  } = useAuthPlugin(deviceAuthorizationPlugin)
  const deviceAuthClient = auth.authClient as DeviceAuthorizationAuthClient
  const session = useSession(deviceAuthClient)
  const [step, setStep] = createSignal<DeviceAuthorizationStep>("code")
  const [userCode, setUserCode] = createSignal("")
  const [codeError, setCodeError] = createSignal("")
  const normalizedUserCode = () => normalizeDeviceCode(userCode())
  let submittedCode: string | undefined

  const handleAuthorizationError = () => {
    setStep("code")
    setCodeError(localization.invalidDeviceCode)
  }

  onMount(() => {
    const code = new URLSearchParams(window.location.search).get("user_code")
    if (!code) return

    setUserCode(
      normalizeDeviceCode(code)
        .replace(/[^A-Z0-9]/g, "")
        .slice(0, userCodeLength)
    )
  })

  const verifyDeviceCode = createMutation<
    VerifyDeviceCodeData,
    BetterFetchError,
    VerifyDeviceCodeVariables
  >(() => ({
    ...verifyDeviceCodeOptions(deviceAuthClient),
    onError: handleAuthorizationError,
    onSuccess: ({ status }) => {
      if (status === "approved" || status === "denied") {
        setStep(status)
        return
      }

      setStep("approval")
    }
  }))

  const approveDevice = createMutation<
    ApproveDeviceData,
    BetterFetchError,
    ApproveDeviceVariables
  >(() => ({
    ...approveDeviceOptions(deviceAuthClient),
    onError: handleAuthorizationError,
    onSuccess: () => setStep("approved")
  }))

  const denyDevice = createMutation<
    DenyDeviceData,
    BetterFetchError,
    DenyDeviceVariables
  >(() => ({
    ...denyDeviceOptions(deviceAuthClient),
    onError: handleAuthorizationError,
    onSuccess: () => setStep("denied")
  }))

  const handleCodeChange = (value: string) => {
    const nextCode = normalizeDeviceCode(value)
      .replace(/[^A-Z0-9]/g, "")
      .slice(0, userCodeLength)

    if (nextCode !== submittedCode) {
      submittedCode = undefined
    }

    setUserCode(nextCode)
    setCodeError("")
  }

  const submitCode = (completedCode: string) => {
    const normalizedCode = normalizeDeviceCode(completedCode)

    if (
      session.isPending ||
      verifyDeviceCode.isPending ||
      normalizedCode.length !== userCodeLength ||
      normalizedCode === submittedCode
    ) {
      return
    }

    submittedCode = normalizedCode

    if (!session.data) {
      const verificationPath = `${auth.basePaths.auth}/${deviceAuthorizationViewPaths.auth.deviceAuthorization}?user_code=${encodeURIComponent(normalizedCode)}`
      const signInPath = `${auth.basePaths.auth}/${auth.viewPaths.auth.signIn}?redirectTo=${encodeURIComponent(verificationPath)}`
      auth.navigate({ to: signInPath })
      return
    }

    verifyDeviceCode.mutate({
      query: { user_code: normalizedCode }
    })
  }

  createEffect(() => {
    const currentCode = normalizedUserCode()

    if (currentCode.length === userCodeLength) {
      submitCode(currentCode)
    }
  })

  const handleSubmit = (event: SubmitEvent) => {
    event.preventDefault()

    if (normalizedUserCode().length !== userCodeLength) {
      handleAuthorizationError()
      return
    }

    submitCode(normalizedUserCode())
  }

  const cardClass = () => cn("w-full max-w-sm", props.class)

  return (
    <Switch>
      <Match when={step() === "approval" ? session.data : undefined}>
        {(currentSession) => (
          <DeviceApproval
            class={cardClass()}
            isApproving={approveDevice.isPending}
            isDenying={denyDevice.isPending}
            localization={localization}
            user={currentSession().user}
            userCode={normalizedUserCode()}
            onApprove={() =>
              approveDevice.mutate({ userCode: normalizedUserCode() })
            }
            onDeny={() => denyDevice.mutate({ userCode: normalizedUserCode() })}
          />
        )}
      </Match>

      <Match when={step() === "approved" || step() === "denied"}>
        <DeviceAuthorizationResult
          class={cardClass()}
          localization={localization}
          status={step() as "approved" | "denied"}
          onReturn={() => auth.navigate({ to: auth.redirectTo })}
        />
      </Match>

      <Match when>
        <DeviceCodeForm
          class={cardClass()}
          codeError={codeError()}
          isSessionPending={session.isPending}
          isVerifying={verifyDeviceCode.isPending}
          localization={localization}
          userCode={userCode()}
          userCodeLength={userCodeLength}
          onCodeChange={handleCodeChange}
          onCodeComplete={submitCode}
          onSubmit={handleSubmit}
        />
      </Match>
    </Switch>
  )
}

type DeviceCodeFormProps = {
  class: string
  codeError: string
  isSessionPending: boolean
  isVerifying: boolean
  localization: DeviceAuthorizationLocalization
  userCode: string
  userCodeLength: number
  onCodeChange: (value: string) => void
  onCodeComplete: (value: string) => void
  onSubmit: (event: SubmitEvent) => void
}

function DeviceCodeForm(props: DeviceCodeFormProps) {
  const slots = createDeviceCodeSlots(props.userCodeLength)
  const groupBreak = Math.ceil(props.userCodeLength / 2)
  const firstGroup = slots.slice(0, groupBreak)
  const secondGroup = slots.slice(groupBreak)
  const errorId = "device-code-error"

  return (
    <Card class={props.class}>
      <CardHeader>
        <CardTitle class="text-xl">
          {props.localization.deviceAuthorization}
        </CardTitle>
        <CardDescription>
          {props.localization.deviceAuthorizationDescription}
        </CardDescription>
      </CardHeader>

      <CardContent>
        <form
          aria-label={props.localization.deviceAuthorization}
          onSubmit={props.onSubmit}
        >
          <div class="flex flex-col gap-5">
            <div class="flex flex-col gap-2">
              <Label for="device-code">{props.localization.deviceCode}</Label>

              <InputOTP
                maxLength={props.userCodeLength}
                id="device-code"
                aria-describedby={props.codeError ? errorId : undefined}
                aria-invalid={Boolean(props.codeError)}
                aria-label={props.localization.deviceCode}
                autocomplete="one-time-code"
                containerClass="w-full justify-center"
                disabled={props.isVerifying}
                inputmode="text"
                name="userCode"
                pattern="^[A-Za-z0-9]*$"
                value={props.userCode}
                onValueChange={props.onCodeChange}
                onComplete={props.onCodeComplete}
              >
                <InputOTPGroup>
                  <For each={firstGroup}>
                    {(slot) => <InputOTPSlot index={slot.index} />}
                  </For>
                </InputOTPGroup>

                <Show when={secondGroup.length > 0}>
                  <InputOTPSeparator />
                  <InputOTPGroup>
                    <For each={secondGroup}>
                      {(slot) => <InputOTPSlot index={slot.index} />}
                    </For>
                  </InputOTPGroup>
                </Show>
              </InputOTP>

              <Show when={props.codeError}>
                <p class="text-sm text-destructive" id={errorId} role="alert">
                  {props.codeError}
                </p>
              </Show>
            </div>

            <Button
              class="w-full"
              disabled={
                props.userCode.length !== props.userCodeLength ||
                props.isSessionPending ||
                props.isVerifying
              }
              type="submit"
            >
              <Show when={props.isVerifying}>
                <Spinner />
              </Show>
              {props.localization.continue}
            </Button>
          </div>
        </form>
      </CardContent>
    </Card>
  )
}

type DeviceApprovalProps = {
  class: string
  isApproving: boolean
  isDenying: boolean
  localization: DeviceAuthorizationLocalization
  user: {
    email: string
    name: string
  }
  userCode: string
  onApprove: () => void
  onDeny: () => void
}

function DeviceApproval(props: DeviceApprovalProps) {
  const isPending = () => props.isApproving || props.isDenying

  return (
    <Card class={props.class}>
      <CardHeader>
        <CardTitle class="text-xl">
          {props.localization.approveDevice}
        </CardTitle>
        <CardDescription>
          {props.localization.approveDeviceDescription}
        </CardDescription>
      </CardHeader>

      <CardContent>
        <div class="flex flex-col gap-3 rounded-lg border bg-muted/50 p-3">
          <div class="flex flex-col gap-1">
            <p class="text-xs text-muted-foreground">
              {props.localization.deviceCode}
            </p>
            <p class="font-mono text-sm font-medium tracking-wider">
              {props.userCode}
            </p>
          </div>

          <Separator />

          <div class="flex flex-col gap-1">
            <p class="text-xs text-muted-foreground">
              {props.localization.signedInAs}
            </p>
            <p class="text-sm font-medium">
              {props.user.name || props.user.email}
            </p>
            <Show when={props.user.name}>
              <p class="text-xs text-muted-foreground">{props.user.email}</p>
            </Show>
          </div>
        </div>
      </CardContent>

      <CardFooter class="grid grid-cols-2 gap-2">
        <Button disabled={isPending()} variant="outline" onClick={props.onDeny}>
          <Show when={props.isDenying} fallback={<X />}>
            <Spinner />
          </Show>
          {props.localization.deny}
        </Button>

        <Button disabled={isPending()} onClick={props.onApprove}>
          <Show when={props.isApproving} fallback={<Check />}>
            <Spinner />
          </Show>
          {props.localization.approve}
        </Button>
      </CardFooter>
    </Card>
  )
}

type DeviceAuthorizationResultProps = {
  class: string
  localization: DeviceAuthorizationLocalization
  status: "approved" | "denied"
  onReturn: () => void
}

function DeviceAuthorizationResult(props: DeviceAuthorizationResultProps) {
  const approved = () => props.status === "approved"

  return (
    <Card class={props.class}>
      <CardHeader class="justify-items-center text-center">
        <Show
          when={approved()}
          fallback={
            <CircleX aria-hidden="true" class="mb-1 size-10 text-destructive" />
          }
        >
          <CircleCheck aria-hidden="true" class="mb-1 size-10 text-primary" />
        </Show>
        <CardTitle class="text-xl">
          {approved()
            ? props.localization.deviceApproved
            : props.localization.deviceDenied}
        </CardTitle>
        <CardDescription>
          {approved()
            ? props.localization.deviceApprovedDescription
            : props.localization.deviceDeniedDescription}
        </CardDescription>
      </CardHeader>

      <CardFooter>
        <Button class="w-full" onClick={props.onReturn}>
          {props.localization.returnToApplication}
        </Button>
      </CardFooter>
    </Card>
  )
}

// packages/heroui/src/components/auth/device-authorization/device-authorization.tsx
import type { DeviceAuthorizationLocalization } from "@better-auth-ui/core/plugins"
import {
  type DeviceAuthorizationAuthClient,
  useApproveDevice,
  useAuth,
  useAuthPlugin,
  useDenyDevice,
  useSession,
  useVerifyDeviceCode
} from "@better-auth-ui/react"
import { Check, CircleCheck, CircleXmark, Xmark } from "@gravity-ui/icons"
import {
  Button,
  Card,
  type CardProps,
  cn,
  Form,
  InputOTP,
  Label,
  REGEXP_ONLY_DIGITS_AND_CHARS,
  Spinner
} from "@heroui/react"
import {
  type FormEvent,
  type ReactNode,
  useCallback,
  useEffect,
  useReducer,
  useRef,
  useState
} from "react"

import { deviceAuthorizationPlugin } from "../../../lib/auth/device-authorization-plugin"

type DeviceAuthorizationStep = "code" | "approval" | "approved" | "denied"

type DeviceAuthorizationState = {
  step: DeviceAuthorizationStep
  codeError: string
}

type DeviceAuthorizationAction =
  | { type: "codeChanged" }
  | { type: "verificationFailed"; message: string }
  | { type: "verificationSucceeded"; status: string }
  | { type: "approved" }
  | { type: "denied" }

const initialDeviceAuthorizationState: DeviceAuthorizationState = {
  step: "code",
  codeError: ""
}

function deviceAuthorizationReducer(
  state: DeviceAuthorizationState,
  action: DeviceAuthorizationAction
): DeviceAuthorizationState {
  switch (action.type) {
    case "codeChanged":
      return state.codeError ? { ...state, codeError: "" } : state
    case "verificationFailed":
      return { step: "code", codeError: action.message }
    case "verificationSucceeded":
      if (action.status === "approved") {
        return { step: "approved", codeError: "" }
      }
      if (action.status === "denied") {
        return { step: "denied", codeError: "" }
      }
      return { step: "approval", codeError: "" }
    case "approved":
      return { step: "approved", codeError: "" }
    case "denied":
      return { step: "denied", codeError: "" }
  }
}

function normalizeDeviceCode(value: string) {
  return value.replace(/-/g, "").trim().toUpperCase()
}

function createDeviceCodeSlots(length: number) {
  return Array.from({ length }, (_, slotIndex) => ({
    id: `device-code-character-${String(slotIndex + 1)}`,
    index: slotIndex
  }))
}

export type DeviceAuthorizationProps = {
  className?: string
  variant?: CardProps["variant"]
}

/**
 * Render Better Auth's browser-side device authorization ceremony.
 *
 * The view accepts a user code, sends unauthenticated users through sign-in
 * with a return URL, verifies and claims the code for the current session,
 * and lets the user approve or deny the device.
 *
 * @param className - Additional CSS classes applied to the card.
 * @param variant - HeroUI card variant.
 */
export function DeviceAuthorization({
  className,
  variant
}: DeviceAuthorizationProps) {
  const { authClient, basePaths, navigate, redirectTo, viewPaths } = useAuth()
  const {
    localization,
    userCodeLength,
    viewPaths: deviceAuthorizationViewPaths
  } = useAuthPlugin(deviceAuthorizationPlugin)

  const deviceAuthClient = authClient as DeviceAuthorizationAuthClient
  const { data: session, isPending: isSessionPending } =
    useSession(deviceAuthClient)
  const [userCode, setUserCode] = useState("")
  const [state, dispatch] = useReducer(
    deviceAuthorizationReducer,
    initialDeviceAuthorizationState
  )
  const submittedCodeRef = useRef<string | null>(null)
  const normalizedUserCode = normalizeDeviceCode(userCode)

  const handleAuthorizationError = () => {
    dispatch({
      type: "verificationFailed",
      message: localization.invalidDeviceCode
    })
  }

  useEffect(() => {
    const code = new URLSearchParams(window.location.search).get("user_code")
    if (!code) return

    setUserCode(
      normalizeDeviceCode(code)
        .replace(/[^A-Z0-9]/g, "")
        .slice(0, userCodeLength)
    )
  }, [userCodeLength])

  const { mutate: verifyDeviceCode, isPending: isVerifying } =
    useVerifyDeviceCode(deviceAuthClient, {
      onError: handleAuthorizationError,
      onSuccess: ({ status }) => {
        dispatch({ type: "verificationSucceeded", status })
      }
    })

  const { mutate: approveDevice, isPending: isApproving } = useApproveDevice(
    deviceAuthClient,
    {
      onError: handleAuthorizationError,
      onSuccess: () => dispatch({ type: "approved" })
    }
  )

  const { mutate: denyDevice, isPending: isDenying } = useDenyDevice(
    deviceAuthClient,
    {
      onError: handleAuthorizationError,
      onSuccess: () => dispatch({ type: "denied" })
    }
  )

  const handleCodeChange = (value: string) => {
    const nextCode = normalizeDeviceCode(value)
      .replace(/[^A-Z0-9]/g, "")
      .slice(0, userCodeLength)

    if (nextCode !== submittedCodeRef.current) {
      submittedCodeRef.current = null
    }

    setUserCode(nextCode)
    dispatch({ type: "codeChanged" })
  }

  const submitCode = useCallback(
    (completedCode: string) => {
      const normalizedCode = normalizeDeviceCode(completedCode)

      if (
        isSessionPending ||
        isVerifying ||
        normalizedCode.length !== userCodeLength ||
        normalizedCode === submittedCodeRef.current
      ) {
        return
      }

      submittedCodeRef.current = normalizedCode

      if (!session) {
        const verificationPath = `${basePaths.auth}/${deviceAuthorizationViewPaths.auth.deviceAuthorization}?user_code=${encodeURIComponent(normalizedCode)}`
        const signInPath = `${basePaths.auth}/${viewPaths.auth.signIn}?redirectTo=${encodeURIComponent(verificationPath)}`
        navigate({ to: signInPath })
        return
      }

      verifyDeviceCode({
        query: { user_code: normalizedCode }
      })
    },
    [
      basePaths.auth,
      deviceAuthorizationViewPaths.auth.deviceAuthorization,
      isSessionPending,
      isVerifying,
      navigate,
      session,
      userCodeLength,
      verifyDeviceCode,
      viewPaths.auth.signIn
    ]
  )

  useEffect(() => {
    if (normalizedUserCode.length === userCodeLength) {
      submitCode(normalizedUserCode)
    }
  }, [normalizedUserCode, submitCode, userCodeLength])

  const handleSubmit = (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault()

    if (normalizedUserCode.length !== userCodeLength) {
      dispatch({
        type: "verificationFailed",
        message: localization.invalidDeviceCode
      })
      return
    }

    submitCode(normalizedUserCode)
  }

  const cardClassName = cn("w-full max-w-sm gap-4 md:p-6", className) ?? ""

  if (state.step === "approval" && session) {
    return (
      <DeviceApproval
        className={cardClassName}
        localization={localization}
        userCode={normalizedUserCode}
        user={session.user}
        variant={variant}
        isApproving={isApproving}
        isDenying={isDenying}
        onApprove={() => approveDevice({ userCode: normalizedUserCode })}
        onDeny={() => denyDevice({ userCode: normalizedUserCode })}
      />
    )
  }

  if (state.step === "approved" || state.step === "denied") {
    return (
      <DeviceAuthorizationResult
        className={cardClassName}
        localization={localization}
        status={state.step}
        variant={variant}
        action={
          <Button
            className="w-full"
            onPress={() => navigate({ to: redirectTo })}
          >
            {localization.returnToApplication}
          </Button>
        }
      />
    )
  }

  return (
    <DeviceCodeForm
      className={cardClassName}
      codeError={state.codeError}
      isSessionPending={isSessionPending}
      isVerifying={isVerifying}
      localization={localization}
      userCode={userCode}
      userCodeLength={userCodeLength}
      variant={variant}
      onCodeChange={handleCodeChange}
      onSubmit={handleSubmit}
    />
  )
}

type DeviceCodeFormProps = {
  className: string
  codeError: string
  isSessionPending: boolean
  isVerifying: boolean
  localization: DeviceAuthorizationLocalization
  userCode: string
  userCodeLength: number
  variant?: CardProps["variant"]
  onCodeChange: (value: string) => void
  onSubmit: (event: FormEvent<HTMLFormElement>) => void
}

function DeviceCodeForm({
  className,
  codeError,
  isSessionPending,
  isVerifying,
  localization,
  userCode,
  userCodeLength,
  variant,
  onCodeChange,
  onSubmit
}: DeviceCodeFormProps) {
  const slots = createDeviceCodeSlots(userCodeLength)
  const groupBreak = Math.ceil(userCodeLength / 2)
  const firstGroup = slots.slice(0, groupBreak)
  const secondGroup = slots.slice(groupBreak)
  const errorId = "device-code-error"

  return (
    <Card className={className} variant={variant}>
      <Card.Header>
        <Card.Title className="text-xl font-semibold mb-1">
          {localization.deviceAuthorization}
        </Card.Title>
        <Card.Description>
          {localization.deviceAuthorizationDescription}
        </Card.Description>
      </Card.Header>

      <Card.Content>
        <Form className="flex flex-col gap-4" onSubmit={onSubmit}>
          <div className="flex flex-col gap-2">
            <Label htmlFor="device-code">{localization.deviceCode}</Label>

            <InputOTP
              id="device-code"
              aria-describedby={codeError ? errorId : undefined}
              aria-label={localization.deviceCode}
              className="w-full flex-col items-center justify-center gap-2 sm:flex-row"
              inputMode="text"
              isDisabled={isVerifying}
              isInvalid={Boolean(codeError)}
              maxLength={userCodeLength}
              name="userCode"
              pasteTransformer={normalizeDeviceCode}
              pattern={REGEXP_ONLY_DIGITS_AND_CHARS}
              value={userCode}
              variant={variant === "transparent" ? "primary" : "secondary"}
              onChange={onCodeChange}
            >
              <InputOTP.Group className="gap-1">
                {firstGroup.map((slot) => (
                  <InputOTP.Slot
                    className="size-8 text-sm sm:size-9"
                    key={slot.id}
                    index={slot.index}
                  />
                ))}
              </InputOTP.Group>

              {secondGroup.length > 0 ? (
                <>
                  <InputOTP.Separator className="hidden sm:block" />
                  <InputOTP.Group className="gap-1">
                    {secondGroup.map((slot) => (
                      <InputOTP.Slot
                        className="size-8 text-sm sm:size-9"
                        key={slot.id}
                        index={slot.index}
                      />
                    ))}
                  </InputOTP.Group>
                </>
              ) : null}
            </InputOTP>

            <span
              className="field-error"
              data-visible={Boolean(codeError)}
              id={errorId}
            >
              {codeError}
            </span>
          </div>

          <Button
            className="w-full"
            isDisabled={userCode.length !== userCodeLength || isSessionPending}
            isPending={isVerifying}
            type="submit"
          >
            {isVerifying ? <Spinner color="current" size="sm" /> : null}
            {localization.continue}
          </Button>
        </Form>
      </Card.Content>
    </Card>
  )
}

type DeviceApprovalProps = {
  className: string
  isApproving: boolean
  isDenying: boolean
  localization: DeviceAuthorizationLocalization
  user: {
    email: string
    name: string
  }
  userCode: string
  variant?: CardProps["variant"]
  onApprove: () => void
  onDeny: () => void
}

function DeviceApproval({
  className,
  isApproving,
  isDenying,
  localization,
  user,
  userCode,
  variant,
  onApprove,
  onDeny
}: DeviceApprovalProps) {
  const isPending = isApproving || isDenying

  return (
    <Card className={className} variant={variant}>
      <Card.Header>
        <Card.Title className="text-xl font-semibold mb-1">
          {localization.approveDevice}
        </Card.Title>
        <Card.Description>
          {localization.approveDeviceDescription}
        </Card.Description>
      </Card.Header>

      <Card.Content>
        <dl className="flex flex-col gap-3 rounded-lg border border-border bg-surface-secondary p-4">
          <div className="flex flex-col gap-1">
            <dt className="text-xs text-muted">{localization.deviceCode}</dt>
            <dd className="font-mono text-sm font-medium tracking-wider">
              {userCode}
            </dd>
          </div>

          <div className="border-t border-border pt-3">
            <dt className="text-xs text-muted">{localization.signedInAs}</dt>
            <dd className="mt-1 flex flex-col text-sm">
              <span className="font-medium">{user.name || user.email}</span>
              {user.name ? (
                <span className="text-muted">{user.email}</span>
              ) : null}
            </dd>
          </div>
        </dl>
      </Card.Content>

      <Card.Footer className="grid grid-cols-2 gap-3">
        <Button
          className="w-full"
          isDisabled={isPending}
          isPending={isDenying}
          variant="secondary"
          onPress={onDeny}
        >
          {isDenying ? <Spinner color="current" size="sm" /> : <Xmark />}
          {localization.deny}
        </Button>

        <Button
          className="w-full"
          isDisabled={isPending}
          isPending={isApproving}
          onPress={onApprove}
        >
          {isApproving ? <Spinner color="current" size="sm" /> : <Check />}
          {localization.approve}
        </Button>
      </Card.Footer>
    </Card>
  )
}

type DeviceAuthorizationResultProps = {
  action: ReactNode
  className: string
  localization: DeviceAuthorizationLocalization
  status: "approved" | "denied"
  variant?: CardProps["variant"]
}

function DeviceAuthorizationResult({
  action,
  className,
  localization,
  status,
  variant
}: DeviceAuthorizationResultProps) {
  const approved = status === "approved"
  const Icon = approved ? CircleCheck : CircleXmark

  return (
    <Card className={className} variant={variant}>
      <Card.Header className="items-center text-center">
        <Icon
          aria-hidden="true"
          className={cn(
            "mb-2 size-10",
            approved ? "text-success" : "text-danger"
          )}
        />
        <Card.Title className="text-xl font-semibold">
          {approved ? localization.deviceApproved : localization.deviceDenied}
        </Card.Title>
        <Card.Description>
          {approved
            ? localization.deviceApprovedDescription
            : localization.deviceDeniedDescription}
        </Card.Description>
      </Card.Header>

      <Card.Footer>{action}</Card.Footer>
    </Card>
  )
}
