// examples/start-solid-zaidan-example/src/components/auth/organization/create-organization-dialog.tsx
import type { OrganizationLocalization } from "@better-auth-ui/core/plugins"
import type { OrganizationAuthClient } from "@better-auth-ui/solid"
import { useAuth, useCreateOrganization } from "@better-auth-ui/solid"
import { BriefcaseBusiness, LoaderCircle } from "lucide-solid"
import { createEffect, createSignal } from "solid-js"
import { Button } from "@/components/ui/button"
import {
  Dialog,
  DialogClose,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle
} from "@/components/ui/dialog"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { organizationPlugin } from "@/lib/auth/organization-plugin"
import { SlugField, sanitizeSlug } from "./slug-field"

export type CreateOrganizationDialogProps = {
  open: boolean
  onOpenChange: (open: boolean) => void
}

const organizationFallbackLocalization = {
  createOrganization: "Create organization",
  name: "Name",
  namePlaceholder: "Enter the organization name",
  organizationsDescription:
    "Create an organization to collaborate with others and manage shared access."
} satisfies Pick<
  OrganizationLocalization,
  "createOrganization" | "name" | "namePlaceholder" | "organizationsDescription"
>

export function CreateOrganizationDialog(props: CreateOrganizationDialogProps) {
  const auth = useAuth()
  const [name, setName] = createSignal("")
  const [slug, setSlug] = createSignal("")
  const createOrganization = useCreateOrganization(
    auth.authClient as OrganizationAuthClient,
    {
      onSuccess: () => props.onOpenChange(false)
    }
  )
  const organizationPluginConfig = () =>
    auth.plugins.find((plugin) => plugin.id === organizationPlugin.id) as
      | { localization?: OrganizationLocalization }
      | undefined
  const localization = () =>
    organizationPluginConfig()?.localization ?? organizationFallbackLocalization

  createEffect(() => {
    if (!props.open) {
      setName("")
      setSlug("")
      return
    }

    setSlug(sanitizeSlug(name()))
  })

  const handleSubmit = (event: SubmitEvent) => {
    event.preventDefault()

    createOrganization.mutate({
      name: name(),
      slug: slug()
    })
  }

  return (
    <Dialog open={props.open} onOpenChange={props.onOpenChange}>
      <DialogContent>
        <form class="flex flex-col gap-6" onSubmit={handleSubmit}>
          <DialogHeader>
            <div class="flex size-10 items-center justify-center rounded-md bg-muted">
              <BriefcaseBusiness class="size-4.5" />
            </div>
            <DialogTitle>{localization().createOrganization}</DialogTitle>
            <DialogDescription>
              {localization().organizationsDescription}
            </DialogDescription>
          </DialogHeader>

          <div class="grid gap-2">
            <Label for="create-organization-name">{localization().name}</Label>
            <Input
              autofocus
              disabled={createOrganization.isPending}
              id="create-organization-name"
              name="name"
              onInput={(event) => setName(event.currentTarget.value)}
              placeholder={localization().namePlaceholder}
              required
              value={name()}
            />
          </div>

          <SlugField
            disabled={createOrganization.isPending}
            id="create-organization-slug"
            onChange={setSlug}
            value={slug()}
          />

          <DialogFooter>
            <DialogClose
              as={Button}
              disabled={createOrganization.isPending}
              type="button"
              variant="outline"
            >
              {auth.localization.settings.cancel}
            </DialogClose>
            <Button disabled={createOrganization.isPending} type="submit">
              {createOrganization.isPending ? (
                <>
                  <LoaderCircle class="size-4 animate-spin" />
                  {localization().createOrganization}
                </>
              ) : (
                localization().createOrganization
              )}
            </Button>
          </DialogFooter>
        </form>
      </DialogContent>
    </Dialog>
  )
}

// packages/heroui/src/components/auth/organization/create-organization-dialog.tsx
import {
  type OrganizationAuthClient,
  useAuth,
  useAuthPlugin,
  useCreateOrganization
} from "@better-auth-ui/react"
import { Briefcase } from "@gravity-ui/icons"
import {
  AlertDialog,
  Button,
  FieldError,
  Form,
  Input,
  Label,
  Spinner,
  TextField
} from "@heroui/react"
import { type SyntheticEvent, useEffect, useState } from "react"

import { organizationPlugin } from "../../../lib/auth/organization-plugin"
import { SlugField, sanitizeSlug } from "./slug-field"

/** Props for the {@link CreateOrganizationDialog} component. */
export type CreateOrganizationDialogProps = {
  isOpen: boolean
  onOpenChange: (open: boolean) => void
}

/**
 * Render a dialog for creating a new organization.
 *
 * @param isOpen - Whether the dialog is open
 * @param onOpenChange - Callback for when the dialog open state changes
 * @returns The create organization dialog as a JSX element
 */
export function CreateOrganizationDialog({
  isOpen,
  onOpenChange
}: CreateOrganizationDialogProps) {
  const { authClient, localization } = useAuth()
  const { localization: organizationLocalization } =
    useAuthPlugin(organizationPlugin)

  const [name, setName] = useState("")
  const [slug, setSlug] = useState("")

  const { mutate: createOrganization, isPending: isCreating } =
    useCreateOrganization(authClient as OrganizationAuthClient, {
      onSuccess: () => onOpenChange(false)
    })

  const handleSubmit = (e: SyntheticEvent<HTMLFormElement>) => {
    e.preventDefault()
    createOrganization({ name, slug })
  }

  useEffect(() => {
    if (!isOpen) {
      setSlug("")
      setName("")
    }
  }, [isOpen])

  useEffect(() => {
    setSlug(sanitizeSlug(name))
  }, [name])

  return (
    <AlertDialog.Backdrop isOpen={isOpen} onOpenChange={onOpenChange}>
      <AlertDialog.Container>
        <AlertDialog.Dialog>
          <Form onSubmit={handleSubmit}>
            <AlertDialog.CloseTrigger />

            <AlertDialog.Header>
              <AlertDialog.Icon status="default">
                <Briefcase />
              </AlertDialog.Icon>

              <AlertDialog.Heading>
                {organizationLocalization.createOrganization}
              </AlertDialog.Heading>
            </AlertDialog.Header>

            <AlertDialog.Body className="flex flex-col gap-4 overflow-visible">
              <p className="text-muted text-sm">
                {organizationLocalization.organizationsDescription}
              </p>

              <TextField
                id="name"
                name="name"
                isDisabled={isCreating}
                value={name}
                onChange={setName}
              >
                <Label>{organizationLocalization.name}</Label>

                <Input
                  required
                  autoFocus
                  placeholder={organizationLocalization.namePlaceholder}
                  variant="secondary"
                />

                <FieldError />
              </TextField>

              <SlugField
                value={slug}
                onChange={setSlug}
                isDisabled={isCreating}
                variant="secondary"
              />
            </AlertDialog.Body>

            <AlertDialog.Footer>
              <Button slot="close" variant="tertiary" isDisabled={isCreating}>
                {localization.settings.cancel}
              </Button>

              <Button type="submit" isPending={isCreating}>
                {isCreating && <Spinner color="current" size="sm" />}

                {organizationLocalization.createOrganization}
              </Button>
            </AlertDialog.Footer>
          </Form>
        </AlertDialog.Dialog>
      </AlertDialog.Container>
    </AlertDialog.Backdrop>
  )
}
