// examples/start-solid-zaidan-example/src/components/auth/organization/organization-settings.tsx
import { useAuth } from "@better-auth-ui/solid"
import { For } from "solid-js"
import type { OrganizationCardsPlugin } from "@/components/auth/settings/shared/types"
import { OrganizationDangerZone } from "./organization-danger-zone"
import { OrganizationProfile } from "./organization-profile"

export type OrganizationSettingsProps = {
  class?: string
}

export function OrganizationSettings(props: OrganizationSettingsProps) {
  const auth = useAuth()
  const organizationCards = () =>
    (auth.plugins as OrganizationCardsPlugin[]).flatMap(
      (plugin) => plugin.organizationCards ?? []
    )

  return (
    <div class={props.class ?? "grid gap-4 md:gap-6"}>
      <OrganizationProfile />
      <For each={organizationCards()}>
        {(OrganizationCard) => <OrganizationCard />}
      </For>
      <OrganizationDangerZone />
    </div>
  )
}

// packages/heroui/src/components/auth/organization/organization-settings.tsx
import { type CardProps, cn } from "@heroui/react"
import type { ComponentProps } from "react"

import { OrganizationDangerZone } from "./organization-danger-zone"
import { OrganizationProfile } from "./organization-profile"

/** Props for the {@link OrganizationSettings} component. */
export type OrganizationSettingsProps = {
  className?: string
  variant?: CardProps["variant"]
}

/**
 * Organization settings UI: profile card, then danger zone.
 */
export function OrganizationSettings({
  className,
  variant,
  ...props
}: OrganizationSettingsProps & ComponentProps<"div">) {
  return (
    <div className={cn("flex flex-col gap-4 md:gap-6", className)} {...props}>
      <OrganizationProfile variant={variant} />
      <OrganizationDangerZone variant={variant} />
    </div>
  )
}
