// examples/start-solid-zaidan-example/src/components/auth/organization/organizations.tsx
import type { OrganizationLocalization } from "@better-auth-ui/core/plugins"
import { organizationLocalization } from "@better-auth-ui/core/plugins"
import type { OrganizationAuthClient } from "@better-auth-ui/solid"
import { useAuth, useListOrganizations } from "@better-auth-ui/solid"
import { createSignal, For, Show } from "solid-js"
import { Button } from "@/components/ui/button"
import { Card, CardContent } from "@/components/ui/card"
import { Separator } from "@/components/ui/separator"
import { organizationPlugin } from "@/lib/auth/organization-plugin"
import { CreateOrganizationDialog } from "./create-organization-dialog"
import { OrganizationRow } from "./organization-row"
import { OrganizationViewSkeleton } from "./organization-view-skeleton"
import { OrganizationsEmpty } from "./organizations-empty"

export type OrganizationsProps = {
  class?: string
}

type OrganizationPluginConfig = {
  localization?: OrganizationLocalization
}

export function Organizations(props: OrganizationsProps = {}) {
  const auth = useAuth()
  const client = auth.authClient as OrganizationAuthClient
  const localization = () =>
    (
      auth.plugins.find((plugin) => plugin.id === organizationPlugin.id) as
        | OrganizationPluginConfig
        | undefined
    )?.localization ?? organizationLocalization
  const organizations = useListOrganizations(client)
  const [createOpen, setCreateOpen] = createSignal(false)

  return (
    <>
      <div class={props.class}>
        <div class="flex flex-col gap-3">
          <div class="flex items-end justify-between gap-3">
            <h2 class="truncate font-semibold text-sm">
              {localization().organizations}
            </h2>

            <Button
              class="shrink-0"
              size="sm"
              disabled={organizations.isPending}
              onClick={() => setCreateOpen(true)}
            >
              {localization().createOrganization}
            </Button>
          </div>

          <Card class="!p-0">
            <CardContent class="!p-0">
              <Show
                when={!organizations.isPending}
                fallback={
                  <div class="p-4">
                    <OrganizationViewSkeleton />
                  </div>
                }
              >
                <Show
                  when={(organizations.data ?? []).length > 0}
                  fallback={
                    <OrganizationsEmpty
                      onCreatePress={() => setCreateOpen(true)}
                    />
                  }
                >
                  <For each={organizations.data ?? []}>
                    {(organization, index) => (
                      <>
                        <Show when={index() > 0}>
                          <Separator />
                        </Show>

                        <div class="p-4">
                          <OrganizationRow organization={organization} />
                        </div>
                      </>
                    )}
                  </For>
                </Show>
              </Show>
            </CardContent>
          </Card>
        </div>
      </div>

      <CreateOrganizationDialog
        open={createOpen()}
        onOpenChange={setCreateOpen}
      />
    </>
  )
}

// packages/heroui/src/components/auth/organization/organizations.tsx
import {
  type OrganizationAuthClient,
  useAuth,
  useAuthPlugin,
  useListOrganizations
} from "@better-auth-ui/react"
import { Button, Card, type CardProps } from "@heroui/react"
import { useState } from "react"

import { organizationPlugin } from "../../../lib/auth/organization-plugin"
import { CreateOrganizationDialog } from "./create-organization-dialog"
import { OrganizationRow } from "./organization-row"
import { OrganizationViewSkeleton } from "./organization-view-skeleton"
import { OrganizationsEmpty } from "./organizations-empty"

export type OrganizationsProps = {
  variant?: CardProps["variant"]
}

/**
 * Lists organizations the user belongs to (via {@link useListOrganizations}): loading skeleton,
 * empty state with create, or a card of rows with a Manage control per organization.
 * Owns {@link CreateOrganizationDialog} open state and the create actions.
 */
export function Organizations({ variant }: OrganizationsProps) {
  const { authClient } = useAuth()
  const { localization: organizationLocalization } =
    useAuthPlugin(organizationPlugin)

  const [createOpen, setCreateOpen] = useState(false)

  const { data: organizations, isPending: organizationsPending } =
    useListOrganizations(authClient as OrganizationAuthClient)

  return (
    <>
      <div className="flex flex-col gap-3">
        <div className="flex items-end justify-between gap-3">
          <h2 className="truncate text-sm font-semibold">
            {organizationLocalization.organizations}
          </h2>

          <Button
            className="shrink-0"
            size="sm"
            isDisabled={organizationsPending}
            onPress={() => setCreateOpen(true)}
          >
            {organizationLocalization.createOrganization}
          </Button>
        </div>

        <Card variant={variant}>
          <Card.Content className="gap-0">
            {organizationsPending ? (
              <OrganizationViewSkeleton />
            ) : !organizations?.length ? (
              <OrganizationsEmpty onCreatePress={() => setCreateOpen(true)} />
            ) : (
              organizations.map((organization, index) => (
                <div key={organization.id}>
                  {index > 0 && (
                    <div className="-mx-4 my-4 border-b border-dashed" />
                  )}

                  <OrganizationRow organization={organization} />
                </div>
              ))
            )}
          </Card.Content>
        </Card>
      </div>

      <CreateOrganizationDialog
        isOpen={createOpen}
        onOpenChange={setCreateOpen}
      />
    </>
  )
}
