// examples/start-solid-zaidan-example/src/components/auth/organization/organization-row.tsx
import type { OrganizationLocalization } from "@better-auth-ui/core/plugins"
import { organizationLocalization } from "@better-auth-ui/core/plugins"
import type { OrganizationAuthClient } from "@better-auth-ui/solid"
import { useAuth, useSetActiveOrganization } from "@better-auth-ui/solid"
import type { Organization } from "better-auth/client"
import { Settings as SettingsIcon } from "lucide-solid"
import { Show } from "solid-js"
import { Button } from "@/components/ui/button"
import { Spinner } from "@/components/ui/spinner"
import { organizationPlugin } from "@/lib/auth/organization-plugin"
import { createOrganizationPath } from "./organization-path"
import { OrganizationView } from "./organization-view"

export type OrganizationRowProps = {
  organization: Organization
}

type OrganizationPluginConfig = {
  slug?: string | null
  slugPrefix?: string
  localization?: Pick<OrganizationLocalization, "manage">
}

export function OrganizationRow(props: OrganizationRowProps) {
  const auth = useAuth()
  const client = auth.authClient as OrganizationAuthClient
  const organizationPluginConfig = () =>
    auth.plugins.find((plugin) => plugin.id === organizationPlugin.id) as
      | OrganizationPluginConfig
      | undefined
  const localization = () =>
    organizationPluginConfig()?.localization ?? organizationLocalization
  const isSlugMode = () => {
    const plugin = organizationPluginConfig()

    if (!plugin) return false

    return plugin.slug !== undefined
  }
  const organizationViewPaths = () =>
    organizationPlugin().viewPaths.organization ?? { settings: "settings" }

  const navigateToOrganization = () => {
    auth.navigate({
      to: createOrganizationPath({
        basePath: auth.basePaths.organization,
        slugPrefix: organizationPluginConfig()?.slugPrefix,
        slug: props.organization.slug,
        path: organizationViewPaths().settings
      })
    })
  }
  const setActiveOrganization = useSetActiveOrganization(client, {
    onSuccess: () => {
      auth.navigate({
        to: `${auth.basePaths.organization}/${organizationViewPaths().settings}`
      })
    }
  })

  const manageOrganization = () => {
    if (isSlugMode()) {
      navigateToOrganization()
      return
    }

    setActiveOrganization.mutate({
      organizationId: props.organization.id
    })
  }

  return (
    <div class="flex items-center gap-3">
      <OrganizationView organization={props.organization} />

      <Button
        class="ml-auto shrink-0"
        variant="outline"
        size="sm"
        disabled={setActiveOrganization.isPending}
        onClick={manageOrganization}
        aria-label={localization().manage}
      >
        <Show
          when={setActiveOrganization.isPending}
          fallback={<SettingsIcon />}
        >
          <Spinner />
        </Show>

        {localization().manage}
      </Button>
    </div>
  )
}

// packages/heroui/src/components/auth/organization/organization-row.tsx
import {
  type OrganizationAuthClient,
  useAuth,
  useAuthPlugin,
  useSetActiveOrganization
} from "@better-auth-ui/react"
import { Gear } from "@gravity-ui/icons"
import { Button, Spinner } from "@heroui/react"
import type { Organization } from "better-auth/client"

import { organizationPlugin } from "../../../lib/auth/organization-plugin"
import { OrganizationView } from "./organization-view"

export type OrganizationRowProps = {
  organization: Organization
}

/**
 * Single organization row: logo and labels via {@link OrganizationView}, plus Manage.
 */
export function OrganizationRow({ organization }: OrganizationRowProps) {
  const { authClient, basePaths, navigate } = useAuth()
  const {
    localization: organizationLocalization,
    viewPaths: organizationViewPaths,
    slug
  } = useAuthPlugin(organizationPlugin)

  const { mutate: setActiveOrganization, isPending: setActivePending } =
    useSetActiveOrganization(authClient as OrganizationAuthClient, {
      onSuccess: () => {
        navigate({
          to: `${basePaths.organization}/${organizationViewPaths.organization.settings}`
        })
      }
    })

  function manageOrganization() {
    if (slug !== undefined) {
      navigate({
        to: `${basePaths.organization}/${organization.slug}/${organizationViewPaths.organization.settings}`
      })
    } else {
      setActiveOrganization({ organizationId: organization.id })
    }
  }

  return (
    <div className="flex items-center gap-3">
      <OrganizationView organization={organization} />

      <Button
        className="ml-auto shrink-0"
        variant="outline"
        size="sm"
        isPending={setActivePending}
        onPress={manageOrganization}
        aria-label={organizationLocalization.manage}
      >
        {setActivePending ? <Spinner color="current" size="sm" /> : <Gear />}

        {organizationLocalization.manage}
      </Button>
    </div>
  )
}
