// examples/start-solid-zaidan-example/src/components/auth/api-key/organization-api-keys.tsx
import {
  type OrganizationAuthClient,
  useActiveOrganization,
  useAuth,
  useListOrganizationMembers,
  useSession
} from "@better-auth-ui/solid"
import { createMemo, Show } from "solid-js"
import { ApiKeys } from "@/components/auth/api-key/api-keys"

export type OrganizationApiKeysProps = {
  class?: string
}

/**
 * {@link ApiKeys} scoped to the active organization.
 *
 * Hidden for members whose role isn't `owner`. Better Auth's
 * `/organization/has-permission` endpoint isn't usable for `apiKey:*` checks
 * (it doesn't pass `allowCreatorAllPermissions` and the default org AC has no
 * `apiKey` statements), so we gate on role directly.
 */
export function OrganizationApiKeys(props: OrganizationApiKeysProps) {
  const auth = useAuth()
  const session = useSession(auth.authClient)
  const activeOrganization = useActiveOrganization(
    auth.authClient as OrganizationAuthClient
  )
  const members = useListOrganizationMembers(
    auth.authClient as OrganizationAuthClient
  )
  const canManageApiKeys = createMemo(() =>
    Boolean(
      members.data?.members.some(
        (member: { role?: string | null; userId?: string | null }) =>
          member.role === "owner" && member.userId === session.data?.user.id
      )
    )
  )

  return (
    <Show when={canManageApiKeys()}>
      <ApiKeys
        class={props.class}
        organizationId={activeOrganization.data?.id}
        isPending={activeOrganization.isPending}
      />
    </Show>
  )
}

// examples/start-shadcn-example/src/components/auth/api-key/organization-api-keys.tsx
"use client"

import {
  type OrganizationAuthClient,
  useActiveOrganization,
  useAuth,
  useListOrganizationMembers,
  useSession
} from "@better-auth-ui/react"

import { ApiKeys } from "./api-keys"

export type OrganizationApiKeysProps = {
  className?: string
}

/**
 * {@link ApiKeys} scoped to the active organization.
 *
 * Hidden for members whose role isn't `owner`. Better Auth's
 * `/organization/has-permission` endpoint isn't usable for `apiKey:*` checks
 * (it doesn't pass `allowCreatorAllPermissions` and the default org AC has no
 * `apiKey` statements), so we gate on role directly.
 */
export function OrganizationApiKeys({ className }: OrganizationApiKeysProps) {
  const { authClient } = useAuth()
  const { data: session } = useSession(authClient)

  const { data: activeOrganization, isPending: activeOrganizationPending } =
    useActiveOrganization(authClient as OrganizationAuthClient)

  const { data: membersData } = useListOrganizationMembers(
    authClient as OrganizationAuthClient
  )

  const memberRoles =
    membersData?.members
      .find((member) => member.userId === session?.user.id)
      ?.role.split(",")
      .map((role) => role.trim()) ?? []

  const canManageApiKeys = memberRoles.includes("owner")

  if (!canManageApiKeys) {
    return null
  }

  return (
    <ApiKeys
      className={className}
      organizationId={activeOrganization?.id}
      isPending={activeOrganizationPending}
    />
  )
}
