// apps/docs/src/components/ui/table.tsx
import * as React from "react"

import { cn } from "@/lib/utils"

function Table({ className, ...props }: React.ComponentProps<"table">) {
  return (
    <div
      data-slot="table-container"
      className="relative w-full overflow-x-auto"
    >
      <table
        data-slot="table"
        className={cn("w-full caption-bottom text-sm", className)}
        {...props}
      />
    </div>
  )
}

function TableHeader({ className, ...props }: React.ComponentProps<"thead">) {
  return (
    <thead
      data-slot="table-header"
      className={cn("[&_tr]:border-b", className)}
      {...props}
    />
  )
}

function TableBody({ className, ...props }: React.ComponentProps<"tbody">) {
  return (
    <tbody
      data-slot="table-body"
      className={cn("[&_tr:last-child]:border-0", className)}
      {...props}
    />
  )
}

function TableFooter({ className, ...props }: React.ComponentProps<"tfoot">) {
  return (
    <tfoot
      data-slot="table-footer"
      className={cn(
        "border-t bg-muted/50 font-medium [&>tr]:last:border-b-0",
        className
      )}
      {...props}
    />
  )
}

function TableRow({ className, ...props }: React.ComponentProps<"tr">) {
  return (
    <tr
      data-slot="table-row"
      className={cn(
        "border-b transition-colors hover:bg-muted/50 has-aria-expanded:bg-muted/50 data-[state=selected]:bg-muted",
        className
      )}
      {...props}
    />
  )
}

function TableHead({ className, ...props }: React.ComponentProps<"th">) {
  return (
    <th
      data-slot="table-head"
      className={cn(
        "h-10 px-2 text-left align-middle font-medium whitespace-nowrap text-foreground [&:has([role=checkbox])]:pr-0",
        className
      )}
      {...props}
    />
  )
}

function TableCell({ className, ...props }: React.ComponentProps<"td">) {
  return (
    <td
      data-slot="table-cell"
      className={cn(
        "p-2 align-middle whitespace-nowrap [&:has([role=checkbox])]:pr-0",
        className
      )}
      {...props}
    />
  )
}

function TableCaption({
  className,
  ...props
}: React.ComponentProps<"caption">) {
  return (
    <caption
      data-slot="table-caption"
      className={cn("mt-4 text-sm text-muted-foreground", className)}
      {...props}
    />
  )
}

export {
  Table,
  TableHeader,
  TableBody,
  TableFooter,
  TableHead,
  TableRow,
  TableCell,
  TableCaption
}

// examples/start-solid-zaidan-example/src/components/ui/table.tsx
import { type ComponentProps, splitProps } from "solid-js"
import { cn } from "@/lib/utils"

type TableProps = ComponentProps<"table">

const Table = (props: TableProps) => {
  const [local, others] = splitProps(props, ["class"])

  return (
    <div class="z-table-container" data-slot="table-container">
      <table class={cn("z-table", local.class)} data-slot="table" {...others} />
    </div>
  )
}

type TableHeaderProps = ComponentProps<"thead">

const TableHeader = (props: TableHeaderProps) => {
  const [local, others] = splitProps(props, ["class"])

  return (
    <thead
      class={cn("z-table-header", local.class)}
      data-slot="table-header"
      {...others}
    />
  )
}

type TableBodyProps = ComponentProps<"tbody">

const TableBody = (props: TableBodyProps) => {
  const [local, others] = splitProps(props, ["class"])

  return (
    <tbody
      class={cn("z-table-body", local.class)}
      data-slot="table-body"
      {...others}
    />
  )
}

type TableFooterProps = ComponentProps<"tfoot">

const TableFooter = (props: TableFooterProps) => {
  const [local, others] = splitProps(props, ["class"])

  return (
    <tfoot
      class={cn("z-table-footer", local.class)}
      data-slot="table-footer"
      {...others}
    />
  )
}

type TableRowProps = ComponentProps<"tr">

const TableRow = (props: TableRowProps) => {
  const [local, others] = splitProps(props, ["class"])

  return (
    <tr
      class={cn("z-table-row", local.class)}
      data-slot="table-row"
      {...others}
    />
  )
}

type TableHeadProps = ComponentProps<"th">

const TableHead = (props: TableHeadProps) => {
  const [local, others] = splitProps(props, ["class"])

  return (
    <th
      class={cn("z-table-head", local.class)}
      data-slot="table-head"
      {...others}
    />
  )
}

type TableCellProps = ComponentProps<"td">

const TableCell = (props: TableCellProps) => {
  const [local, others] = splitProps(props, ["class"])

  return (
    <td
      class={cn("z-table-cell", local.class)}
      data-slot="table-cell"
      {...others}
    />
  )
}

type TableCaptionProps = ComponentProps<"caption">

const TableCaption = (props: TableCaptionProps) => {
  const [local, others] = splitProps(props, ["class"])

  return (
    <caption
      class={cn("z-table-caption", local.class)}
      data-slot="table-caption"
      {...others}
    />
  )
}

export {
  Table,
  TableBody,
  TableCaption,
  TableCell,
  TableFooter,
  TableHead,
  TableHeader,
  TableRow
}
