// examples/start-solid-zaidan-example/src/components/auth/theme/theme-toggle-item.tsx
import { useAuth } from "@better-auth-ui/solid"
import { Monitor, Moon, PaletteIcon, Sun } from "lucide-solid"
import { createSignal, For, onMount } from "solid-js"
import {
  resolveThemePluginState,
  type ThemeOption
} from "@/components/auth/theme/theme-plugin-state"
import { DropdownMenuItem } from "@/components/ui/dropdown-menu"
import { Tabs, TabsList, TabsTrigger } from "@/components/ui/tabs"
import { applyThemePreference, isThemeMode, type ThemeMode } from "@/lib/theme"
import { cn } from "@/lib/utils"

export type ThemeToggleItemProps = {
  class?: string
}

const themeIcon = (value: ThemeMode) => {
  if (value === "light") return Sun
  if (value === "dark") return Moon

  return Monitor
}

const themeLabel = (
  localization: ReturnType<typeof resolveThemePluginState>["localization"],
  option: ThemeOption
) => localization[option.value]

export function ThemeToggleItem(props: ThemeToggleItemProps = {}) {
  const auth = useAuth()
  const themeState = () => resolveThemePluginState(auth.plugins)
  const [theme, setTheme] = createSignal<ThemeMode>(themeState().theme)
  let tabsListElement!: HTMLDivElement

  onMount(() => {
    const initialTheme = themeState().theme

    setTheme(initialTheme)
    applyThemePreference(initialTheme)
  })

  const selectTheme = (nextTheme: ThemeMode) => {
    setTheme(nextTheme)
    themeState().setTheme(nextTheme)
  }

  const focusActiveTab = () => {
    const activeTab = tabsListElement?.querySelector<HTMLElement>(
      '[role="tab"][data-selected]'
    )

    activeTab?.focus({ preventScroll: true })
  }

  const handleTabsKeyDown = (event: KeyboardEvent) => {
    if (event.key !== "ArrowUp" && event.key !== "ArrowDown") return

    const target = event.target as HTMLElement
    if (target.getAttribute("role") !== "tab") return

    const wrapper = target.closest<HTMLElement>('[role="menuitem"]')
    const content = wrapper?.closest<HTMLElement>(
      '[data-slot="dropdown-menu-content"]'
    )
    if (!wrapper || !content) return

    const items = Array.from(
      content.querySelectorAll<HTMLElement>(
        '[role="menuitem"]:not([aria-disabled="true"])'
      )
    )
    const currentIndex = items.indexOf(wrapper)
    const nextIndex =
      event.key === "ArrowDown" ? currentIndex + 1 : currentIndex - 1
    const next = items[nextIndex]
    if (!next) return

    event.preventDefault()
    next.focus()
  }

  return (
    <DropdownMenuItem
      class={cn(
        "z-dropdown-menu-item-auth hover:bg-accent hover:text-accent-foreground focus:bg-accent focus:text-accent-foreground data-expanded:bg-accent data-expanded:text-accent-foreground",
        props.class
      )}
      closeOnSelect={false}
      onFocus={(event) => {
        if (event.target === event.currentTarget) focusActiveTab()
      }}
    >
      <div class="flex w-full items-center gap-2">
        <PaletteIcon class="size-4 text-muted-foreground" />
        <span>{themeState().localization.theme}</span>

        <Tabs
          class="ml-auto"
          onKeyDown={handleTabsKeyDown}
          onChange={(nextTheme) => {
            if (isThemeMode(nextTheme)) selectTheme(nextTheme)
          }}
          value={theme()}
        >
          <TabsList class="z-tabs-list-theme-toggle" ref={tabsListElement}>
            <For each={themeState().themes}>
              {(option) => {
                const Icon = themeIcon(option.value)

                return (
                  <TabsTrigger
                    aria-label={themeLabel(themeState().localization, option)}
                    class="size-5 p-0"
                    value={option.value}
                  >
                    <Icon class="size-3" />
                  </TabsTrigger>
                )
              }}
            </For>
          </TabsList>
        </Tabs>
      </div>
    </DropdownMenuItem>
  )
}

// packages/heroui/src/components/theme/theme-toggle-item.tsx
import { useAuthPlugin } from "@better-auth-ui/react"
import { Display, Moon, Sun } from "@gravity-ui/icons"
import { Dropdown, Label, Tabs } from "@heroui/react"

import { themePlugin } from "../../lib/theme/theme-plugin"

const ACTIVE_TAB_SELECTOR = '[role="tab"][aria-selected="true"]'

/**
 * Theme toggle dropdown item used inside `UserButton`. Callers are responsible
 * for ensuring theming is configured before rendering this component.
 */
export function ThemeToggleItem() {
  const { useTheme, localization } = useAuthPlugin(themePlugin)
  const { theme, setTheme, themes = [] } = useTheme()

  // Up/Down on a Tab escapes back to the previous/next sibling menu item so
  // users can keep navigating the menu with the arrow keys after they've
  // entered the Tabs.
  const handleTabsKeyDown = (event: React.KeyboardEvent<HTMLDivElement>) => {
    if (event.key !== "ArrowUp" && event.key !== "ArrowDown") return

    const target = event.target as HTMLElement
    if (target.getAttribute("role") !== "tab") return

    const wrapper = target.closest<HTMLElement>('[role="menuitem"]')
    const menu = wrapper?.closest<HTMLElement>('[role="menu"]')
    if (!wrapper || !menu) return

    const items = Array.from(
      menu.querySelectorAll<HTMLElement>(
        '[role="menuitem"]:not([data-disabled])'
      )
    )
    const currentIndex = items.indexOf(wrapper)
    const nextIndex =
      event.key === "ArrowDown" ? currentIndex + 1 : currentIndex - 1
    const next = items[nextIndex]
    if (!next) return

    event.preventDefault()
    next.focus()
  }

  return (
    <Dropdown.Item
      className="py-1 pe-2"
      // The Tabs aren't part of the menu's keyboard-navigation list, so
      // arrow-key nav can't reach them. When the wrapper menu item receives
      // focus we delegate focus to the active Tab so the user can switch
      // themes with Left/Right arrows. React Aria's useFocus only fires when
      // the wrapper itself receives focus (not when a child does), so no
      // re-entry guard is required.
      onFocus={(e) => {
        const activeTab =
          e.currentTarget.querySelector<HTMLElement>(ACTIVE_TAB_SELECTOR)
        activeTab?.focus({ preventScroll: true })
      }}
      // Without this the menu auto-closes after the user changes themes
      // because clicking on a Tab bubbles up as a menu-item activation.
      shouldCloseOnSelect={false}
    >
      <Label>{localization.theme}</Label>

      <Tabs
        className="ml-auto"
        selectedKey={theme}
        onSelectionChange={(key) => setTheme(key as string)}
      >
        <Tabs.ListContainer onKeyDown={handleTabsKeyDown}>
          <Tabs.List
            aria-label={localization.theme}
            className="*:h-5 *:w-5 *:p-0"
          >
            {themes.includes("system") && (
              <Tabs.Tab id="system" aria-label={localization.system}>
                <Display className="size-3" />

                <Tabs.Indicator />
              </Tabs.Tab>
            )}

            {themes.includes("light") && (
              <Tabs.Tab id="light" aria-label={localization.light}>
                <Sun className="size-3" />

                <Tabs.Indicator />
              </Tabs.Tab>
            )}

            {themes.includes("dark") && (
              <Tabs.Tab id="dark" aria-label={localization.dark}>
                <Moon className="size-3" />

                <Tabs.Indicator />
              </Tabs.Tab>
            )}
          </Tabs.List>
        </Tabs.ListContainer>
      </Tabs>
    </Dropdown.Item>
  )
}
